{"nodes":[{"content":"The exception that is thrown when there is a syntax error in XML parsing. This class cannot be inherited.","nodes":[{"pos":[0,105],"content":"The exception that is thrown when there is a syntax error in XML parsing. This class cannot be inherited.","nodes":[{"content":"The exception that is thrown when there is a syntax error in XML parsing. This class cannot be inherited.","pos":[0,105],"nodes":[{"content":"The exception that is thrown when there is a syntax error in XML parsing.","pos":[0,73]},{"content":"This class cannot be inherited.","pos":[74,105]}]}]}],"pos":[721,827],"yaml":true},{"content":"<xref:System.Security.XmlSyntaxException> uses the default <xref:System.Object.Equals%2A> implementation, which supports reference equality.  \n  \n For a list of initial property values for an instance of <xref:System.Security.XmlSyntaxException>, see the constructor.","nodes":[{"pos":[0,140],"content":"<xref:System.Security.XmlSyntaxException> uses the default <xref:System.Object.Equals%2A> implementation, which supports reference equality.","nodes":[{"content":"<ph id=\"ph1\">&lt;xref:System.Security.XmlSyntaxException&gt;</ph> uses the default <ph id=\"ph2\">&lt;xref:System.Object.Equals%2A&gt;</ph> implementation, which supports reference equality.","pos":[0,140],"source":"<xref:System.Security.XmlSyntaxException> uses the default <xref:System.Object.Equals%2A> implementation, which supports reference equality."}]},{"pos":[147,267],"content":"For a list of initial property values for an instance of <xref:System.Security.XmlSyntaxException>, see the constructor.","nodes":[{"content":"For a list of initial property values for an instance of <ph id=\"ph1\">&lt;xref:System.Security.XmlSyntaxException&gt;</ph>, see the constructor.","pos":[0,120],"source":"For a list of initial property values for an instance of <xref:System.Security.XmlSyntaxException>, see the constructor."}]}],"pos":[838,1110],"yaml":true,"extradata":"MT"},{"content":"Initializes a new instance of the <xref href=\"System.Security.XmlSyntaxException\"></xref> class with default properties.","nodes":[{"pos":[0,120],"content":"Initializes a new instance of the <ph id=\"ph1\">&lt;xref href=\"System.Security.XmlSyntaxException\"&gt;&lt;/xref&gt;</ph> class with default properties.","source":"Initializes a new instance of the <xref href=\"System.Security.XmlSyntaxException\"></xref> class with default properties."}],"pos":[3307,3428],"yaml":true},{"content":"The following table shows the initial property values for an instance of <xref:System.Security.XmlSyntaxException>.  \n  \n|Property|Value|  \n|--------------|-----------|  \n|<xref:System.Exception.InnerException%2A>|`null`.|  \n|<xref:System.Exception.Message%2A>|\"Invalid syntax.\"|","nodes":[{"pos":[0,115],"content":"The following table shows the initial property values for an instance of <xref:System.Security.XmlSyntaxException>.","nodes":[{"content":"The following table shows the initial property values for an instance of <ph id=\"ph1\">&lt;xref:System.Security.XmlSyntaxException&gt;</ph>.","pos":[0,115],"source":"The following table shows the initial property values for an instance of <xref:System.Security.XmlSyntaxException>."}]},{"pos":[122,130],"content":"Property","nodes":[{"content":"Property","pos":[0,8]}]},{"pos":[131,136],"content":"Value","nodes":[{"content":"Value","pos":[0,5]}]},{"pos":[172,213],"content":"<xref:System.Exception.InnerException%2A>","nodes":[]},{"pos":[214,221],"content":"<ph id=\"ph1\">`null`</ph>.","source":"`null`."},{"pos":[226,260],"content":"<xref:System.Exception.Message%2A>","nodes":[]},{"pos":[261,278],"content":"\"Invalid syntax.\"","nodes":[{"content":"\"Invalid syntax.\"","pos":[0,17]}]}],"pos":[3439,3728],"yaml":true,"extradata":"MT"},{"content":"Initializes a new instance of the <xref href=\"System.Security.XmlSyntaxException\"></xref> class with the line number where the exception was detected.","nodes":[{"pos":[0,150],"content":"Initializes a new instance of the <ph id=\"ph1\">&lt;xref href=\"System.Security.XmlSyntaxException\"&gt;&lt;/xref&gt;</ph> class with the line number where the exception was detected.","source":"Initializes a new instance of the <xref href=\"System.Security.XmlSyntaxException\"></xref> class with the line number where the exception was detected."}],"pos":[5055,5206],"yaml":true},{"content":"The line number of an XML stream is updated whenever a newline character is detected. Numbering begins with 1 for the first line.  \n  \n The following table shows the initial property values for an instance of <xref:System.Security.XmlSyntaxException>.  \n  \n|Property|Value|  \n|--------------|-----------|  \n|<xref:System.Exception.InnerException%2A>|`null`.|  \n|<xref:System.Exception.Message%2A>|\"Invalid syntax on line `lineNumber`.\"|","nodes":[{"pos":[0,129],"content":"The line number of an XML stream is updated whenever a newline character is detected. Numbering begins with 1 for the first line.","nodes":[{"content":"The line number of an XML stream is updated whenever a newline character is detected. Numbering begins with 1 for the first line.","pos":[0,129],"nodes":[{"content":"The line number of an XML stream is updated whenever a newline character is detected.","pos":[0,85]},{"content":"Numbering begins with 1 for the first line.","pos":[86,129]}]}]},{"pos":[136,251],"content":"The following table shows the initial property values for an instance of <xref:System.Security.XmlSyntaxException>.","nodes":[{"content":"The following table shows the initial property values for an instance of <ph id=\"ph1\">&lt;xref:System.Security.XmlSyntaxException&gt;</ph>.","pos":[0,115],"source":"The following table shows the initial property values for an instance of <xref:System.Security.XmlSyntaxException>."}]},{"pos":[258,266],"content":"Property","nodes":[{"content":"Property","pos":[0,8]}]},{"pos":[267,272],"content":"Value","nodes":[{"content":"Value","pos":[0,5]}]},{"pos":[308,349],"content":"<xref:System.Exception.InnerException%2A>","nodes":[]},{"pos":[350,357],"content":"<ph id=\"ph1\">`null`</ph>.","source":"`null`."},{"pos":[362,396],"content":"<xref:System.Exception.Message%2A>","nodes":[]},{"pos":[397,435],"content":"\"Invalid syntax on line <ph id=\"ph1\">`lineNumber`</ph>.\"","source":"\"Invalid syntax on line `lineNumber`.\""}],"pos":[5217,5665],"yaml":true,"extradata":"MT"},{"content":"The line number of the XML stream where the XML syntax error was detected.","nodes":[{"pos":[0,74],"content":"The line number of the XML stream where the XML syntax error was detected.","nodes":[{"content":"The line number of the XML stream where the XML syntax error was detected.","pos":[0,74]}]}],"pos":[5813,5888],"yaml":true},{"content":"Initializes a new instance of the <xref href=\"System.Security.XmlSyntaxException\"></xref> class with a specified error message.","nodes":[{"pos":[0,127],"content":"Initializes a new instance of the <ph id=\"ph1\">&lt;xref href=\"System.Security.XmlSyntaxException\"&gt;&lt;/xref&gt;</ph> class with a specified error message.","source":"Initializes a new instance of the <xref href=\"System.Security.XmlSyntaxException\"></xref> class with a specified error message."}],"pos":[7149,7277],"yaml":true},{"content":"The following table shows the initial property values for an instance of <xref:System.Security.XmlSyntaxException>.  \n  \n|Property|Value|  \n|--------------|-----------|  \n|<xref:System.Exception.InnerException%2A>|`null`.|  \n|<xref:System.Exception.Message%2A>|The error message string.|","nodes":[{"pos":[0,115],"content":"The following table shows the initial property values for an instance of <xref:System.Security.XmlSyntaxException>.","nodes":[{"content":"The following table shows the initial property values for an instance of <ph id=\"ph1\">&lt;xref:System.Security.XmlSyntaxException&gt;</ph>.","pos":[0,115],"source":"The following table shows the initial property values for an instance of <xref:System.Security.XmlSyntaxException>."}]},{"pos":[122,130],"content":"Property","nodes":[{"content":"Property","pos":[0,8]}]},{"pos":[131,136],"content":"Value","nodes":[{"content":"Value","pos":[0,5]}]},{"pos":[172,213],"content":"<xref:System.Exception.InnerException%2A>","nodes":[]},{"pos":[214,221],"content":"<ph id=\"ph1\">`null`</ph>.","source":"`null`."},{"pos":[226,260],"content":"<xref:System.Exception.Message%2A>","nodes":[]},{"pos":[261,286],"content":"The error message string.","nodes":[{"content":"The error message string.","pos":[0,25]}]}],"pos":[7288,7583],"yaml":true,"extradata":"MT"},{"content":"The error message that explains the reason for the exception.","nodes":[{"pos":[0,61],"content":"The error message that explains the reason for the exception.","nodes":[{"content":"The error message that explains the reason for the exception.","pos":[0,61]}]}],"pos":[7729,7791],"yaml":true},{"content":"Initializes a new instance of the <xref href=\"System.Security.XmlSyntaxException\"></xref> class with a specified error message and the line number where the exception was detected.","nodes":[{"pos":[0,180],"content":"Initializes a new instance of the <ph id=\"ph1\">&lt;xref href=\"System.Security.XmlSyntaxException\"&gt;&lt;/xref&gt;</ph> class with a specified error message and the line number where the exception was detected.","source":"Initializes a new instance of the <xref href=\"System.Security.XmlSyntaxException\"></xref> class with a specified error message and the line number where the exception was detected."}],"pos":[9112,9293],"yaml":true},{"content":"The line number of an XML stream is updated whenever a newline character is detected. Numbering begins with 1 for the first line.  \n  \n The following table shows the initial property values for an instance of <xref:System.Security.XmlSyntaxException>.  \n  \n|Property|Value|  \n|--------------|-----------|  \n|<xref:System.Exception.InnerException%2A>|`null`.|  \n|<xref:System.Exception.Message%2A>|\"Invalid syntax on line `lineNumber` - `message` \"|","nodes":[{"pos":[0,129],"content":"The line number of an XML stream is updated whenever a newline character is detected. Numbering begins with 1 for the first line.","nodes":[{"content":"The line number of an XML stream is updated whenever a newline character is detected. Numbering begins with 1 for the first line.","pos":[0,129],"nodes":[{"content":"The line number of an XML stream is updated whenever a newline character is detected.","pos":[0,85]},{"content":"Numbering begins with 1 for the first line.","pos":[86,129]}]}]},{"pos":[136,251],"content":"The following table shows the initial property values for an instance of <xref:System.Security.XmlSyntaxException>.","nodes":[{"content":"The following table shows the initial property values for an instance of <ph id=\"ph1\">&lt;xref:System.Security.XmlSyntaxException&gt;</ph>.","pos":[0,115],"source":"The following table shows the initial property values for an instance of <xref:System.Security.XmlSyntaxException>."}]},{"pos":[258,266],"content":"Property","nodes":[{"content":"Property","pos":[0,8]}]},{"pos":[267,272],"content":"Value","nodes":[{"content":"Value","pos":[0,5]}]},{"pos":[308,349],"content":"<xref:System.Exception.InnerException%2A>","nodes":[]},{"pos":[350,357],"content":"<ph id=\"ph1\">`null`</ph>.","source":"`null`."},{"pos":[362,396],"content":"<xref:System.Exception.Message%2A>","nodes":[]},{"pos":[397,447],"content":"\"Invalid syntax on line <ph id=\"ph1\">`lineNumber`</ph><ph id=\"ph2\"> - </ph><ph id=\"ph3\">`message`</ph> \"","source":"\"Invalid syntax on line `lineNumber` - `message` \""}],"pos":[9304,9764],"yaml":true,"extradata":"MT"},{"content":"The line number of the XML stream where the XML syntax error was detected.","nodes":[{"pos":[0,74],"content":"The line number of the XML stream where the XML syntax error was detected.","nodes":[{"content":"The line number of the XML stream where the XML syntax error was detected.","pos":[0,74]}]}],"pos":[9928,10003],"yaml":true},{"content":"The error message that explains the reason for the exception.","nodes":[{"pos":[0,61],"content":"The error message that explains the reason for the exception.","nodes":[{"content":"The error message that explains the reason for the exception.","pos":[0,61]}]}],"pos":[10066,10128],"yaml":true},{"content":"Initializes a new instance of the <xref href=\"System.Security.XmlSyntaxException\"></xref> class with a specified error message and a reference to the inner exception that is the cause of this exception.","nodes":[{"pos":[0,202],"content":"Initializes a new instance of the <ph id=\"ph1\">&lt;xref href=\"System.Security.XmlSyntaxException\"&gt;&lt;/xref&gt;</ph> class with a specified error message and a reference to the inner exception that is the cause of this exception.","source":"Initializes a new instance of the <xref href=\"System.Security.XmlSyntaxException\"></xref> class with a specified error message and a reference to the inner exception that is the cause of this exception."}],"pos":[11473,11676],"yaml":true},{"content":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property. The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or `null` if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor.  \n  \n The following table shows the initial property values for an instance of <xref:System.Security.XmlSyntaxException>.  \n  \n|Property|Value|  \n|--------------|-----------|  \n|<xref:System.Exception.InnerException%2A>|The inner exception reference.|  \n|<xref:System.Exception.Message%2A>|The error message string.|","nodes":[{"pos":[0,427],"content":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property. The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or `null` if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor.","nodes":[{"content":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <ph id=\"ph1\">&lt;xref:System.Exception.InnerException%2A&gt;</ph> property.","pos":[0,182],"source":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property."},{"content":"The <ph id=\"ph1\">&lt;xref:System.Exception.InnerException%2A&gt;</ph> property returns the same value that is passed into the constructor, or <ph id=\"ph2\">`null`</ph> if the <ph id=\"ph3\">&lt;xref:System.Exception.InnerException%2A&gt;</ph> property does not supply the inner exception value to the constructor.","pos":[183,427],"source":" The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or `null` if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor."}]},{"pos":[434,549],"content":"The following table shows the initial property values for an instance of <xref:System.Security.XmlSyntaxException>.","nodes":[{"content":"The following table shows the initial property values for an instance of <ph id=\"ph1\">&lt;xref:System.Security.XmlSyntaxException&gt;</ph>.","pos":[0,115],"source":"The following table shows the initial property values for an instance of <xref:System.Security.XmlSyntaxException>."}]},{"pos":[556,564],"content":"Property","nodes":[{"content":"Property","pos":[0,8]}]},{"pos":[565,570],"content":"Value","nodes":[{"content":"Value","pos":[0,5]}]},{"pos":[606,647],"content":"<xref:System.Exception.InnerException%2A>","nodes":[]},{"pos":[648,678],"content":"The inner exception reference.","nodes":[{"content":"The inner exception reference.","pos":[0,30]}]},{"pos":[683,717],"content":"<xref:System.Exception.Message%2A>","nodes":[]},{"pos":[718,743],"content":"The error message string.","nodes":[{"content":"The error message string.","pos":[0,25]}]}],"pos":[11687,12441],"yaml":true,"extradata":"MT"},{"content":"The error message that explains the reason for the exception.","nodes":[{"pos":[0,61],"content":"The error message that explains the reason for the exception.","nodes":[{"content":"The error message that explains the reason for the exception.","pos":[0,61]}]}],"pos":[12604,12666],"yaml":true},{"content":"The exception that is the cause of the current exception. If the <code>inner</code> parameter is not `null`, the current exception is raised in a `catch` block that handles the inner exception.","nodes":[{"pos":[0,193],"content":"The exception that is the cause of the current exception. If the <code>inner</code> parameter is not `null`, the current exception is raised in a `catch` block that handles the inner exception.","nodes":[{"content":"The exception that is the cause of the current exception.","pos":[0,57]},{"content":"If the <bpt id=\"p1\">&lt;code&gt;</bpt><ph id=\"ph1\">inner</ph><ept id=\"p1\">&lt;/code&gt;</ept> parameter is not <ph id=\"ph2\">`null`</ph>, the current exception is raised in a <ph id=\"ph3\">`catch`</ph> block that handles the inner exception.","pos":[58,193],"source":" If the <code>inner</code> parameter is not `null`, the current exception is raised in a `catch` block that handles the inner exception."}]}],"pos":[12730,12924],"yaml":true}],"content":"### YamlMime:ManagedReference\nitems:\n- uid: System.Security.XmlSyntaxException\n  commentId: T:System.Security.XmlSyntaxException\n  id: XmlSyntaxException\n  children:\n  - System.Security.XmlSyntaxException.#ctor\n  - System.Security.XmlSyntaxException.#ctor(System.Int32)\n  - System.Security.XmlSyntaxException.#ctor(System.String)\n  - System.Security.XmlSyntaxException.#ctor(System.Int32,System.String)\n  - System.Security.XmlSyntaxException.#ctor(System.String,System.Exception)\n  langs:\n  - csharp\n  name: XmlSyntaxException\n  nameWithType: XmlSyntaxException\n  fullName: System.Security.XmlSyntaxException\n  type: Class\n  assemblies:\n  - mscorlib\n  - System.Security.Permissions\n  namespace: System.Security\n  summary: The exception that is thrown when there is a syntax error in XML parsing. This class cannot be inherited.\n  remarks: \"<xref:System.Security.XmlSyntaxException> uses the default <xref:System.Object.Equals%2A> implementation, which supports reference equality.  \\n  \\n For a list of initial property values for an instance of <xref:System.Security.XmlSyntaxException>, see the constructor.\"\n  syntax:\n    content: >-\n      [System.Runtime.InteropServices.ComVisible(true)]\n\n      public sealed class XmlSyntaxException : SystemException\n  inheritance:\n  - System.Object\n  - System.Exception\n  - System.SystemException\n  implements: []\n  inheritedMembers:\n  - System.Exception.Data\n  - System.Exception.GetBaseException\n  - System.Exception.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  - System.Exception.GetType\n  - System.Exception.HelpLink\n  - System.Exception.HResult\n  - System.Exception.InnerException\n  - System.Exception.Message\n  - System.Exception.SerializeObjectState\n  - System.Exception.Source\n  - System.Exception.StackTrace\n  - System.Exception.TargetSite\n  - System.Exception.ToString\n  - System.Object.Equals(System.Object)\n  - System.Object.Equals(System.Object,System.Object)\n  - System.Object.GetHashCode\n  - System.Object.MemberwiseClone\n  - System.Object.ReferenceEquals(System.Object,System.Object)\n  attributes:\n  - type: System.Runtime.InteropServices.ComVisibleAttribute\n  version:\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  monikers:\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Security/XmlSyntaxException.xml\n  ms.technology:\n  - dotnet-standard\n  author: mairaw\n  ms.author: mairaw\n  manager: wpickett\n- uid: System.Security.XmlSyntaxException.#ctor\n  commentId: M:System.Security.XmlSyntaxException.#ctor\n  id: '#ctor'\n  parent: System.Security.XmlSyntaxException\n  langs:\n  - csharp\n  name: XmlSyntaxException()\n  nameWithType: XmlSyntaxException.XmlSyntaxException()\n  fullName: XmlSyntaxException.XmlSyntaxException()\n  type: Constructor\n  assemblies:\n  - mscorlib\n  - System.Security.Permissions\n  namespace: System.Security\n  summary: Initializes a new instance of the <xref href=\"System.Security.XmlSyntaxException\"></xref> class with default properties.\n  remarks: \"The following table shows the initial property values for an instance of <xref:System.Security.XmlSyntaxException>.  \\n  \\n|Property|Value|  \\n|--------------|-----------|  \\n|<xref:System.Exception.InnerException%2A>|`null`.|  \\n|<xref:System.Exception.Message%2A>|\\\"Invalid syntax.\\\"|\"\n  syntax:\n    content: public XmlSyntaxException ();\n    parameters: []\n  overload: System.Security.XmlSyntaxException.#ctor*\n  exceptions: []\n  version:\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  monikers:\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Security/XmlSyntaxException.xml\n  ms.technology:\n  - dotnet-standard\n  author: mairaw\n  ms.author: mairaw\n  manager: wpickett\n- uid: System.Security.XmlSyntaxException.#ctor(System.Int32)\n  commentId: M:System.Security.XmlSyntaxException.#ctor(System.Int32)\n  id: '#ctor(System.Int32)'\n  parent: System.Security.XmlSyntaxException\n  langs:\n  - csharp\n  name: XmlSyntaxException(Int32)\n  nameWithType: XmlSyntaxException.XmlSyntaxException(Int32)\n  fullName: XmlSyntaxException.XmlSyntaxException(Int32)\n  type: Constructor\n  assemblies:\n  - mscorlib\n  - System.Security.Permissions\n  namespace: System.Security\n  summary: Initializes a new instance of the <xref href=\"System.Security.XmlSyntaxException\"></xref> class with the line number where the exception was detected.\n  remarks: \"The line number of an XML stream is updated whenever a newline character is detected. Numbering begins with 1 for the first line.  \\n  \\n The following table shows the initial property values for an instance of <xref:System.Security.XmlSyntaxException>.  \\n  \\n|Property|Value|  \\n|--------------|-----------|  \\n|<xref:System.Exception.InnerException%2A>|`null`.|  \\n|<xref:System.Exception.Message%2A>|\\\"Invalid syntax on line `lineNumber`.\\\"|\"\n  syntax:\n    content: public XmlSyntaxException (int lineNumber);\n    parameters:\n    - id: lineNumber\n      type: System.Int32\n      description: The line number of the XML stream where the XML syntax error was detected.\n  overload: System.Security.XmlSyntaxException.#ctor*\n  exceptions: []\n  version:\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  monikers:\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Security/XmlSyntaxException.xml\n  ms.technology:\n  - dotnet-standard\n  author: mairaw\n  ms.author: mairaw\n  manager: wpickett\n- uid: System.Security.XmlSyntaxException.#ctor(System.String)\n  commentId: M:System.Security.XmlSyntaxException.#ctor(System.String)\n  id: '#ctor(System.String)'\n  parent: System.Security.XmlSyntaxException\n  langs:\n  - csharp\n  name: XmlSyntaxException(String)\n  nameWithType: XmlSyntaxException.XmlSyntaxException(String)\n  fullName: XmlSyntaxException.XmlSyntaxException(String)\n  type: Constructor\n  assemblies:\n  - mscorlib\n  - System.Security.Permissions\n  namespace: System.Security\n  summary: Initializes a new instance of the <xref href=\"System.Security.XmlSyntaxException\"></xref> class with a specified error message.\n  remarks: \"The following table shows the initial property values for an instance of <xref:System.Security.XmlSyntaxException>.  \\n  \\n|Property|Value|  \\n|--------------|-----------|  \\n|<xref:System.Exception.InnerException%2A>|`null`.|  \\n|<xref:System.Exception.Message%2A>|The error message string.|\"\n  syntax:\n    content: public XmlSyntaxException (string message);\n    parameters:\n    - id: message\n      type: System.String\n      description: The error message that explains the reason for the exception.\n  overload: System.Security.XmlSyntaxException.#ctor*\n  exceptions: []\n  version:\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  monikers:\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Security/XmlSyntaxException.xml\n  ms.technology:\n  - dotnet-standard\n  author: mairaw\n  ms.author: mairaw\n  manager: wpickett\n- uid: System.Security.XmlSyntaxException.#ctor(System.Int32,System.String)\n  commentId: M:System.Security.XmlSyntaxException.#ctor(System.Int32,System.String)\n  id: '#ctor(System.Int32,System.String)'\n  parent: System.Security.XmlSyntaxException\n  langs:\n  - csharp\n  name: XmlSyntaxException(Int32, String)\n  nameWithType: XmlSyntaxException.XmlSyntaxException(Int32, String)\n  fullName: XmlSyntaxException.XmlSyntaxException(Int32, String)\n  type: Constructor\n  assemblies:\n  - mscorlib\n  - System.Security.Permissions\n  namespace: System.Security\n  summary: Initializes a new instance of the <xref href=\"System.Security.XmlSyntaxException\"></xref> class with a specified error message and the line number where the exception was detected.\n  remarks: \"The line number of an XML stream is updated whenever a newline character is detected. Numbering begins with 1 for the first line.  \\n  \\n The following table shows the initial property values for an instance of <xref:System.Security.XmlSyntaxException>.  \\n  \\n|Property|Value|  \\n|--------------|-----------|  \\n|<xref:System.Exception.InnerException%2A>|`null`.|  \\n|<xref:System.Exception.Message%2A>|\\\"Invalid syntax on line `lineNumber` - `message` \\\"|\"\n  syntax:\n    content: public XmlSyntaxException (int lineNumber, string message);\n    parameters:\n    - id: lineNumber\n      type: System.Int32\n      description: The line number of the XML stream where the XML syntax error was detected.\n    - id: message\n      type: System.String\n      description: The error message that explains the reason for the exception.\n  overload: System.Security.XmlSyntaxException.#ctor*\n  exceptions: []\n  version:\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  monikers:\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Security/XmlSyntaxException.xml\n  ms.technology:\n  - dotnet-standard\n  author: mairaw\n  ms.author: mairaw\n  manager: wpickett\n- uid: System.Security.XmlSyntaxException.#ctor(System.String,System.Exception)\n  commentId: M:System.Security.XmlSyntaxException.#ctor(System.String,System.Exception)\n  id: '#ctor(System.String,System.Exception)'\n  parent: System.Security.XmlSyntaxException\n  langs:\n  - csharp\n  name: XmlSyntaxException(String, Exception)\n  nameWithType: XmlSyntaxException.XmlSyntaxException(String, Exception)\n  fullName: XmlSyntaxException.XmlSyntaxException(String, Exception)\n  type: Constructor\n  assemblies:\n  - mscorlib\n  - System.Security.Permissions\n  namespace: System.Security\n  summary: Initializes a new instance of the <xref href=\"System.Security.XmlSyntaxException\"></xref> class with a specified error message and a reference to the inner exception that is the cause of this exception.\n  remarks: \"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property. The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or `null` if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor.  \\n  \\n The following table shows the initial property values for an instance of <xref:System.Security.XmlSyntaxException>.  \\n  \\n|Property|Value|  \\n|--------------|-----------|  \\n|<xref:System.Exception.InnerException%2A>|The inner exception reference.|  \\n|<xref:System.Exception.Message%2A>|The error message string.|\"\n  syntax:\n    content: public XmlSyntaxException (string message, Exception inner);\n    parameters:\n    - id: message\n      type: System.String\n      description: The error message that explains the reason for the exception.\n    - id: inner\n      type: System.Exception\n      description: The exception that is the cause of the current exception. If the <code>inner</code> parameter is not `null`, the current exception is raised in a `catch` block that handles the inner exception.\n  overload: System.Security.XmlSyntaxException.#ctor*\n  exceptions: []\n  version:\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  monikers:\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Security/XmlSyntaxException.xml\n  ms.technology:\n  - dotnet-standard\n  author: mairaw\n  ms.author: mairaw\n  manager: wpickett\nreferences:\n- uid: System.SystemException\n  parent: System\n  isExternal: false\n  name: SystemException\n  nameWithType: SystemException\n  fullName: System.SystemException\n- uid: System.Security.XmlSyntaxException.#ctor\n  parent: System.Security.XmlSyntaxException\n  isExternal: false\n  name: XmlSyntaxException()\n  nameWithType: XmlSyntaxException.XmlSyntaxException()\n  fullName: XmlSyntaxException.XmlSyntaxException()\n- uid: System.Security.XmlSyntaxException.#ctor(System.Int32)\n  parent: System.Security.XmlSyntaxException\n  isExternal: false\n  name: XmlSyntaxException(Int32)\n  nameWithType: XmlSyntaxException.XmlSyntaxException(Int32)\n  fullName: XmlSyntaxException.XmlSyntaxException(Int32)\n- uid: System.Int32\n  parent: System\n  isExternal: false\n  name: Int32\n  nameWithType: Int32\n  fullName: System.Int32\n- uid: System.Security.XmlSyntaxException.#ctor(System.String)\n  parent: System.Security.XmlSyntaxException\n  isExternal: false\n  name: XmlSyntaxException(String)\n  nameWithType: XmlSyntaxException.XmlSyntaxException(String)\n  fullName: XmlSyntaxException.XmlSyntaxException(String)\n- uid: System.String\n  parent: System\n  isExternal: false\n  name: String\n  nameWithType: String\n  fullName: System.String\n- uid: System.Security.XmlSyntaxException.#ctor(System.Int32,System.String)\n  parent: System.Security.XmlSyntaxException\n  isExternal: false\n  name: XmlSyntaxException(Int32, String)\n  nameWithType: XmlSyntaxException.XmlSyntaxException(Int32, String)\n  fullName: XmlSyntaxException.XmlSyntaxException(Int32, String)\n- uid: System.Security.XmlSyntaxException.#ctor(System.String,System.Exception)\n  parent: System.Security.XmlSyntaxException\n  isExternal: false\n  name: XmlSyntaxException(String, Exception)\n  nameWithType: XmlSyntaxException.XmlSyntaxException(String, Exception)\n  fullName: XmlSyntaxException.XmlSyntaxException(String, Exception)\n- uid: System.Exception\n  parent: System\n  isExternal: false\n  name: Exception\n  nameWithType: Exception\n  fullName: System.Exception\n- uid: System.Security.XmlSyntaxException.#ctor*\n  parent: System.Security.XmlSyntaxException\n  isExternal: false\n  name: XmlSyntaxException\n  nameWithType: XmlSyntaxException.XmlSyntaxException\n  fullName: XmlSyntaxException.XmlSyntaxException\n  monikers:\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Security/XmlSyntaxException.xml\n- uid: System.Object.Equals(System.Object)\n  parent: System.Object\n  isExternal: false\n  name: Equals(Object)\n  nameWithType: Object.Equals(Object)\n  fullName: Object.Equals(Object)\n- uid: System.Object.Equals(System.Object,System.Object)\n  parent: System.Object\n  isExternal: false\n  name: Equals(Object, Object)\n  nameWithType: Object.Equals(Object, Object)\n  fullName: Object.Equals(Object, Object)\n- uid: System.Object.GetHashCode\n  parent: System.Object\n  isExternal: false\n  name: GetHashCode()\n  nameWithType: Object.GetHashCode()\n  fullName: Object.GetHashCode()\n- uid: System.Exception.GetType\n  parent: System.Exception\n  isExternal: false\n  name: GetType()\n  nameWithType: Exception.GetType()\n  fullName: Exception.GetType()\n- uid: System.Object.MemberwiseClone\n  parent: System.Object\n  isExternal: false\n  name: MemberwiseClone()\n  nameWithType: Object.MemberwiseClone()\n  fullName: Object.MemberwiseClone()\n- uid: System.Object.ReferenceEquals(System.Object,System.Object)\n  parent: System.Object\n  isExternal: false\n  name: ReferenceEquals(Object, Object)\n  nameWithType: Object.ReferenceEquals(Object, Object)\n  fullName: Object.ReferenceEquals(Object, Object)\n- uid: System.Exception.ToString\n  parent: System.Exception\n  isExternal: false\n  name: ToString()\n  nameWithType: Exception.ToString()\n  fullName: Exception.ToString()\n- uid: System.Exception.Data\n  parent: System.Exception\n  isExternal: false\n  name: Data\n  nameWithType: Exception.Data\n  fullName: Exception.Data\n- uid: System.Exception.GetBaseException\n  parent: System.Exception\n  isExternal: false\n  name: GetBaseException()\n  nameWithType: Exception.GetBaseException()\n  fullName: Exception.GetBaseException()\n- uid: System.Exception.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  parent: System.Exception\n  isExternal: false\n  name: GetObjectData(SerializationInfo, StreamingContext)\n  nameWithType: Exception.GetObjectData(SerializationInfo, StreamingContext)\n  fullName: Exception.GetObjectData(SerializationInfo, StreamingContext)\n- uid: System.Exception.HelpLink\n  parent: System.Exception\n  isExternal: false\n  name: HelpLink\n  nameWithType: Exception.HelpLink\n  fullName: Exception.HelpLink\n- uid: System.Exception.HResult\n  parent: System.Exception\n  isExternal: false\n  name: HResult\n  nameWithType: Exception.HResult\n  fullName: Exception.HResult\n- uid: System.Exception.InnerException\n  parent: System.Exception\n  isExternal: false\n  name: InnerException\n  nameWithType: Exception.InnerException\n  fullName: Exception.InnerException\n- uid: System.Exception.Message\n  parent: System.Exception\n  isExternal: false\n  name: Message\n  nameWithType: Exception.Message\n  fullName: Exception.Message\n- uid: System.Exception.SerializeObjectState\n  parent: System.Exception\n  isExternal: false\n  name: SerializeObjectState\n  nameWithType: Exception.SerializeObjectState\n  fullName: Exception.SerializeObjectState\n- uid: System.Exception.Source\n  parent: System.Exception\n  isExternal: false\n  name: Source\n  nameWithType: Exception.Source\n  fullName: Exception.Source\n- uid: System.Exception.StackTrace\n  parent: System.Exception\n  isExternal: false\n  name: StackTrace\n  nameWithType: Exception.StackTrace\n  fullName: Exception.StackTrace\n- uid: System.Exception.TargetSite\n  parent: System.Exception\n  isExternal: false\n  name: TargetSite\n  nameWithType: Exception.TargetSite\n  fullName: Exception.TargetSite\n"}