{"nodes":[{"content":"The exception that is thrown in a thread upon cancellation of an operation that the thread was executing.","nodes":[{"pos":[0,105],"content":"The exception that is thrown in a thread upon cancellation of an operation that the thread was executing.","nodes":[{"content":"The exception that is thrown in a thread upon cancellation of an operation that the thread was executing.","pos":[0,105]}]}],"pos":[1088,1194],"yaml":true},{"content":"If the task that was canceled had an associated cancellation token, it is returned by the <xref:System.OperationCanceledException.CancellationToken%2A> property, and the <xref:System.Threading.CancellationToken.IsCancellationRequested%2A?displayProperty=fullName> property of the token is set to `true`.","nodes":[{"pos":[0,303],"content":"If the task that was canceled had an associated cancellation token, it is returned by the <ph id=\"ph1\">&lt;xref:System.OperationCanceledException.CancellationToken%2A&gt;</ph> property, and the <ph id=\"ph2\">&lt;xref:System.Threading.CancellationToken.IsCancellationRequested%2A?displayProperty=fullName&gt;</ph> property of the token is set to <ph id=\"ph3\">`true`</ph>.","source":"If the task that was canceled had an associated cancellation token, it is returned by the <xref:System.OperationCanceledException.CancellationToken%2A> property, and the <xref:System.Threading.CancellationToken.IsCancellationRequested%2A?displayProperty=fullName> property of the token is set to `true`."}],"pos":[1205,1509],"yaml":true,"extradata":"MT"},{"content":"Initializes a new instance of the <xref href=\"System.OperationCanceledException\"></xref> class with a system-supplied error message.","nodes":[{"pos":[0,132],"content":"Initializes a new instance of the <ph id=\"ph1\">&lt;xref href=\"System.OperationCanceledException\"&gt;&lt;/xref&gt;</ph> class with a system-supplied error message.","source":"Initializes a new instance of the <xref href=\"System.OperationCanceledException\"></xref> class with a system-supplied error message."}],"pos":[4132,4265],"yaml":true},{"content":"This constructor initializes the <xref:System.Exception.Message%2A> property of the new instance to a system-supplied message that describes the error, such as \"The operation was canceled.\" This message takes into account the current system culture.  \n  \n The following table shows the initial property values for an instance of <xref:System.OperationCanceledException>.  \n  \n|Property|Value|  \n|--------------|-----------|  \n|<xref:System.Exception.InnerException%2A>|A nullreference (`Nothing` in Visual Basic).|  \n|<xref:System.Exception.Message%2A>|The localized error message string.|  \n|<xref:System.OperationCanceledException.CancellationToken%2A>|A cancellation token created in the non-canceled state.|","nodes":[{"pos":[0,249],"content":"This constructor initializes the <xref:System.Exception.Message%2A> property of the new instance to a system-supplied message that describes the error, such as \"The operation was canceled.\" This message takes into account the current system culture.","nodes":[{"content":"This constructor initializes the <xref:System.Exception.Message%2A> property of the new instance to a system-supplied message that describes the error, such as \"The operation was canceled.\" This message takes into account the current system culture.","pos":[0,249],"nodes":[{"content":"This constructor initializes the <ph id=\"ph1\">&lt;xref:System.Exception.Message%2A&gt;</ph> property of the new instance to a system-supplied message that describes the error, such as \"The operation was canceled.\"","pos":[0,189],"source":"This constructor initializes the <xref:System.Exception.Message%2A> property of the new instance to a system-supplied message that describes the error, such as \"The operation was canceled.\""},{"content":"This message takes into account the current system culture.","pos":[190,249]}]}]},{"pos":[256,370],"content":"The following table shows the initial property values for an instance of <xref:System.OperationCanceledException>.","nodes":[{"content":"The following table shows the initial property values for an instance of <ph id=\"ph1\">&lt;xref:System.OperationCanceledException&gt;</ph>.","pos":[0,114],"source":"The following table shows the initial property values for an instance of <xref:System.OperationCanceledException>."}]},{"pos":[377,385],"content":"Property","nodes":[{"content":"Property","pos":[0,8]}]},{"pos":[386,391],"content":"Value","nodes":[{"content":"Value","pos":[0,5]}]},{"pos":[427,468],"content":"<xref:System.Exception.InnerException%2A>","nodes":[]},{"pos":[469,513],"content":"A nullreference (<ph id=\"ph1\">`Nothing`</ph> in Visual Basic).","source":"A nullreference (`Nothing` in Visual Basic)."},{"pos":[518,552],"content":"<xref:System.Exception.Message%2A>","nodes":[]},{"pos":[553,588],"content":"The localized error message string.","nodes":[{"content":"The localized error message string.","pos":[0,35]}]},{"pos":[593,654],"content":"<xref:System.OperationCanceledException.CancellationToken%2A>","nodes":[]},{"pos":[655,710],"content":"A cancellation token created in the non-canceled state.","nodes":[{"content":"A cancellation token created in the non-canceled state.","pos":[0,55]}]}],"pos":[4276,5000],"yaml":true,"extradata":"MT"},{"content":"Initializes a new instance of the <xref href=\"System.OperationCanceledException\"></xref> class with a specified error message.","nodes":[{"pos":[0,126],"content":"Initializes a new instance of the <ph id=\"ph1\">&lt;xref href=\"System.OperationCanceledException\"&gt;&lt;/xref&gt;</ph> class with a specified error message.","source":"Initializes a new instance of the <xref href=\"System.OperationCanceledException\"></xref> class with a specified error message."}],"pos":[6725,6852],"yaml":true},{"content":"The content of `message` is intended to be understood by humans. The caller of this constructor is required to ensure that this string has been localized for the current system culture.  \n  \n The following table shows the initial property values for an instance of <xref:System.OperationCanceledException>.  \n  \n|Property|Value|  \n|--------------|-----------|  \n|<xref:System.Exception.InnerException%2A>|A null reference (`Nothing` in Visual Basic).|  \n|<xref:System.Exception.Message%2A>|The error message string.|  \n|<xref:System.OperationCanceledException.CancellationToken%2A>|A cancellation token created in the non-canceled state.|","nodes":[{"pos":[0,185],"content":"The content of `message` is intended to be understood by humans. The caller of this constructor is required to ensure that this string has been localized for the current system culture.","nodes":[{"content":"The content of <ph id=\"ph1\">`message`</ph> is intended to be understood by humans.","pos":[0,64],"source":"The content of `message` is intended to be understood by humans."},{"content":"The caller of this constructor is required to ensure that this string has been localized for the current system culture.","pos":[65,185]}]},{"pos":[192,306],"content":"The following table shows the initial property values for an instance of <xref:System.OperationCanceledException>.","nodes":[{"content":"The following table shows the initial property values for an instance of <ph id=\"ph1\">&lt;xref:System.OperationCanceledException&gt;</ph>.","pos":[0,114],"source":"The following table shows the initial property values for an instance of <xref:System.OperationCanceledException>."}]},{"pos":[313,321],"content":"Property","nodes":[{"content":"Property","pos":[0,8]}]},{"pos":[322,327],"content":"Value","nodes":[{"content":"Value","pos":[0,5]}]},{"pos":[363,404],"content":"<xref:System.Exception.InnerException%2A>","nodes":[]},{"pos":[405,450],"content":"A null reference (<ph id=\"ph1\">`Nothing`</ph> in Visual Basic).","source":"A null reference (`Nothing` in Visual Basic)."},{"pos":[455,489],"content":"<xref:System.Exception.Message%2A>","nodes":[]},{"pos":[490,515],"content":"The error message string.","nodes":[{"content":"The error message string.","pos":[0,25]}]},{"pos":[520,581],"content":"<xref:System.OperationCanceledException.CancellationToken%2A>","nodes":[]},{"pos":[582,637],"content":"A cancellation token created in the non-canceled state.","nodes":[{"content":"A cancellation token created in the non-canceled state.","pos":[0,55]}]}],"pos":[6863,7512],"yaml":true,"extradata":"MT"},{"content":"A <xref href=\"System.String\"></xref> that describes the error.","nodes":[{"pos":[0,62],"content":"A <ph id=\"ph1\">&lt;xref href=\"System.String\"&gt;&lt;/xref&gt;</ph> that describes the error.","source":"A <xref href=\"System.String\"></xref> that describes the error."}],"pos":[7666,7729],"yaml":true},{"content":"Initializes a new instance of the <xref href=\"System.OperationCanceledException\"></xref> class with a cancellation token.","nodes":[{"pos":[0,121],"content":"Initializes a new instance of the <ph id=\"ph1\">&lt;xref href=\"System.OperationCanceledException\"&gt;&lt;/xref&gt;</ph> class with a cancellation token.","source":"Initializes a new instance of the <xref href=\"System.OperationCanceledException\"></xref> class with a cancellation token."}],"pos":[9470,9592],"yaml":true},{"content":"This constructor initializes the <xref:System.Exception.Message%2A> property of the new instance to a system-supplied message that describes the error, such as \"The operation was canceled.\" This message takes into account the current system culture.  \n  \n The following table shows the initial property values for an instance of <xref:System.OperationCanceledException>.  \n  \n|Property|Value|  \n|--------------|-----------|  \n|<xref:System.Exception.InnerException%2A>|A nullreference (`Nothing` in Visual Basic).|  \n|<xref:System.Exception.Message%2A>|The localized error message string.|  \n|<xref:System.OperationCanceledException.CancellationToken%2A>|`token`.|","nodes":[{"pos":[0,249],"content":"This constructor initializes the <xref:System.Exception.Message%2A> property of the new instance to a system-supplied message that describes the error, such as \"The operation was canceled.\" This message takes into account the current system culture.","nodes":[{"content":"This constructor initializes the <xref:System.Exception.Message%2A> property of the new instance to a system-supplied message that describes the error, such as \"The operation was canceled.\" This message takes into account the current system culture.","pos":[0,249],"nodes":[{"content":"This constructor initializes the <ph id=\"ph1\">&lt;xref:System.Exception.Message%2A&gt;</ph> property of the new instance to a system-supplied message that describes the error, such as \"The operation was canceled.\"","pos":[0,189],"source":"This constructor initializes the <xref:System.Exception.Message%2A> property of the new instance to a system-supplied message that describes the error, such as \"The operation was canceled.\""},{"content":"This message takes into account the current system culture.","pos":[190,249]}]}]},{"pos":[256,370],"content":"The following table shows the initial property values for an instance of <xref:System.OperationCanceledException>.","nodes":[{"content":"The following table shows the initial property values for an instance of <ph id=\"ph1\">&lt;xref:System.OperationCanceledException&gt;</ph>.","pos":[0,114],"source":"The following table shows the initial property values for an instance of <xref:System.OperationCanceledException>."}]},{"pos":[377,385],"content":"Property","nodes":[{"content":"Property","pos":[0,8]}]},{"pos":[386,391],"content":"Value","nodes":[{"content":"Value","pos":[0,5]}]},{"pos":[427,468],"content":"<xref:System.Exception.InnerException%2A>","nodes":[]},{"pos":[469,513],"content":"A nullreference (<ph id=\"ph1\">`Nothing`</ph> in Visual Basic).","source":"A nullreference (`Nothing` in Visual Basic)."},{"pos":[518,552],"content":"<xref:System.Exception.Message%2A>","nodes":[]},{"pos":[553,588],"content":"The localized error message string.","nodes":[{"content":"The localized error message string.","pos":[0,35]}]},{"pos":[593,654],"content":"<xref:System.OperationCanceledException.CancellationToken%2A>","nodes":[]},{"pos":[655,663],"content":"<ph id=\"ph1\">`token`</ph>.","source":"`token`."}],"pos":[9603,10280],"yaml":true,"extradata":"MT"},{"content":"A cancellation token associated with the operation that was canceled.","nodes":[{"pos":[0,69],"content":"A cancellation token associated with the operation that was canceled.","nodes":[{"content":"A cancellation token associated with the operation that was canceled.","pos":[0,69]}]}],"pos":[10479,10549],"yaml":true},{"content":"Initializes a new instance of the <xref href=\"System.OperationCanceledException\"></xref> class with serialized data.","nodes":[{"pos":[0,116],"content":"Initializes a new instance of the <ph id=\"ph1\">&lt;xref href=\"System.OperationCanceledException\"&gt;&lt;/xref&gt;</ph> class with serialized data.","source":"Initializes a new instance of the <xref href=\"System.OperationCanceledException\"></xref> class with serialized data."}],"pos":[12518,12635],"yaml":true},{"content":"This constructor is called during deserialization to reconstitute the exception object transmitted over a stream. For more information, see [XML and SOAP Serialization](~/docs/framework/serialization/xml-and-soap-serialization.md)","nodes":[{"pos":[0,230],"content":"This constructor is called during deserialization to reconstitute the exception object transmitted over a stream. For more information, see [XML and SOAP Serialization](~/docs/framework/serialization/xml-and-soap-serialization.md)","nodes":[{"content":"This constructor is called during deserialization to reconstitute the exception object transmitted over a stream.","pos":[0,113]},{"content":"For more information, see <bpt id=\"p1\">[</bpt>XML and SOAP Serialization<ept id=\"p1\">](~/docs/framework/serialization/xml-and-soap-serialization.md)</ept>","pos":[114,230],"source":" For more information, see [XML and SOAP Serialization](~/docs/framework/serialization/xml-and-soap-serialization.md)"}]}],"pos":[12646,12877],"yaml":true,"extradata":"MT"},{"content":"The object that holds the serialized object data.","nodes":[{"pos":[0,49],"content":"The object that holds the serialized object data.","nodes":[{"content":"The object that holds the serialized object data.","pos":[0,49]}]}],"pos":[13156,13206],"yaml":true},{"content":"The contextual information about the source or destination.","nodes":[{"pos":[0,59],"content":"The contextual information about the source or destination.","nodes":[{"content":"The contextual information about the source or destination.","pos":[0,59]}]}],"pos":[13301,13361],"yaml":true},{"content":"Initializes a new instance of the <xref href=\"System.OperationCanceledException\"></xref> class with a specified error message and a reference to the inner exception that is the cause of this exception.","nodes":[{"pos":[0,201],"content":"Initializes a new instance of the <ph id=\"ph1\">&lt;xref href=\"System.OperationCanceledException\"&gt;&lt;/xref&gt;</ph> class with a specified error message and a reference to the inner exception that is the cause of this exception.","source":"Initializes a new instance of the <xref href=\"System.OperationCanceledException\"></xref> class with a specified error message and a reference to the inner exception that is the cause of this exception."}],"pos":[14786,14988],"yaml":true},{"content":"The content of `message` is intended to be understood by humans. The caller of this constructor is required to ensure that this string has been localized for the current system culture.  \n  \n An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property. The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or `null` if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor.  \n  \n The following table shows the initial property values for an instance of <xref:System.OperationCanceledException>.  \n  \n|Property Type|Condition|  \n|-------------------|---------------|  \n|<xref:System.Exception.InnerException%2A>|`innerException`.|  \n|<xref:System.Exception.Message%2A>|`message`.|  \n|<xref:System.OperationCanceledException.CancellationToken%2A>|A cancellation token created in the non-canceled state.|","nodes":[{"pos":[0,185],"content":"The content of `message` is intended to be understood by humans. The caller of this constructor is required to ensure that this string has been localized for the current system culture.","nodes":[{"content":"The content of <ph id=\"ph1\">`message`</ph> is intended to be understood by humans.","pos":[0,64],"source":"The content of `message` is intended to be understood by humans."},{"content":"The caller of this constructor is required to ensure that this string has been localized for the current system culture.","pos":[65,185]}]},{"pos":[192,619],"content":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property. The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or `null` if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor.","nodes":[{"content":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <ph id=\"ph1\">&lt;xref:System.Exception.InnerException%2A&gt;</ph> property.","pos":[0,182],"source":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property."},{"content":"The <ph id=\"ph1\">&lt;xref:System.Exception.InnerException%2A&gt;</ph> property returns the same value that is passed into the constructor, or <ph id=\"ph2\">`null`</ph> if the <ph id=\"ph3\">&lt;xref:System.Exception.InnerException%2A&gt;</ph> property does not supply the inner exception value to the constructor.","pos":[183,427],"source":" The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or `null` if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor."}]},{"pos":[626,740],"content":"The following table shows the initial property values for an instance of <xref:System.OperationCanceledException>.","nodes":[{"content":"The following table shows the initial property values for an instance of <ph id=\"ph1\">&lt;xref:System.OperationCanceledException&gt;</ph>.","pos":[0,114],"source":"The following table shows the initial property values for an instance of <xref:System.OperationCanceledException>."}]},{"pos":[747,760],"content":"Property Type","nodes":[{"content":"Property Type","pos":[0,13]}]},{"pos":[761,770],"content":"Condition","nodes":[{"content":"Condition","pos":[0,9]}]},{"pos":[815,856],"content":"<xref:System.Exception.InnerException%2A>","nodes":[]},{"pos":[857,874],"content":"<ph id=\"ph1\">`innerException`</ph>.","source":"`innerException`."},{"pos":[879,913],"content":"<xref:System.Exception.Message%2A>","nodes":[]},{"pos":[914,924],"content":"<ph id=\"ph1\">`message`</ph>.","source":"`message`."},{"pos":[929,990],"content":"<xref:System.OperationCanceledException.CancellationToken%2A>","nodes":[]},{"pos":[991,1046],"content":"A cancellation token created in the non-canceled state.","nodes":[{"content":"A cancellation token created in the non-canceled state.","pos":[0,55]}]}],"pos":[14999,16059],"yaml":true,"extradata":"MT"},{"content":"The error message that explains the reason for the exception.","nodes":[{"pos":[0,61],"content":"The error message that explains the reason for the exception.","nodes":[{"content":"The error message that explains the reason for the exception.","pos":[0,61]}]}],"pos":[16239,16301],"yaml":true},{"content":"The exception that is the cause of the current exception. If the <code>innerException</code> parameter is not `null`, the current exception is raised in a `catch` block that handles the inner exception.","nodes":[{"pos":[0,202],"content":"The exception that is the cause of the current exception. If the <code>innerException</code> parameter is not `null`, the current exception is raised in a `catch` block that handles the inner exception.","nodes":[{"content":"The exception that is the cause of the current exception.","pos":[0,57]},{"content":"If the <bpt id=\"p1\">&lt;code&gt;</bpt><ph id=\"ph1\">innerException</ph><ept id=\"p1\">&lt;/code&gt;</ept> parameter is not <ph id=\"ph2\">`null`</ph>, the current exception is raised in a <ph id=\"ph3\">`catch`</ph> block that handles the inner exception.","pos":[58,202],"source":" If the <code>innerException</code> parameter is not `null`, the current exception is raised in a `catch` block that handles the inner exception."}]}],"pos":[16374,16577],"yaml":true},{"content":"Initializes a new instance of the <xref href=\"System.OperationCanceledException\"></xref> class with a specified error message and a cancellation token.","nodes":[{"pos":[0,151],"content":"Initializes a new instance of the <ph id=\"ph1\">&lt;xref href=\"System.OperationCanceledException\"&gt;&lt;/xref&gt;</ph> class with a specified error message and a cancellation token.","source":"Initializes a new instance of the <xref href=\"System.OperationCanceledException\"></xref> class with a specified error message and a cancellation token."}],"pos":[18384,18536],"yaml":true},{"content":"The content of `message` is intended to be understood by humans. The caller of this constructor is required to ensure that this string has been localized for the current system culture.  \n  \n The following table shows the initial property values for an instance of <xref:System.OperationCanceledException>.  \n  \n|Property|Value|  \n|--------------|-----------|  \n|<xref:System.Exception.InnerException%2A>|A null reference (`Nothing` in Visual Basic).|  \n|<xref:System.Exception.Message%2A>|`message`.|  \n|<xref:System.OperationCanceledException.CancellationToken%2A>|`token`.|","nodes":[{"pos":[0,185],"content":"The content of `message` is intended to be understood by humans. The caller of this constructor is required to ensure that this string has been localized for the current system culture.","nodes":[{"content":"The content of <ph id=\"ph1\">`message`</ph> is intended to be understood by humans.","pos":[0,64],"source":"The content of `message` is intended to be understood by humans."},{"content":"The caller of this constructor is required to ensure that this string has been localized for the current system culture.","pos":[65,185]}]},{"pos":[192,306],"content":"The following table shows the initial property values for an instance of <xref:System.OperationCanceledException>.","nodes":[{"content":"The following table shows the initial property values for an instance of <ph id=\"ph1\">&lt;xref:System.OperationCanceledException&gt;</ph>.","pos":[0,114],"source":"The following table shows the initial property values for an instance of <xref:System.OperationCanceledException>."}]},{"pos":[313,321],"content":"Property","nodes":[{"content":"Property","pos":[0,8]}]},{"pos":[322,327],"content":"Value","nodes":[{"content":"Value","pos":[0,5]}]},{"pos":[363,404],"content":"<xref:System.Exception.InnerException%2A>","nodes":[]},{"pos":[405,450],"content":"A null reference (<ph id=\"ph1\">`Nothing`</ph> in Visual Basic).","source":"A null reference (`Nothing` in Visual Basic)."},{"pos":[455,489],"content":"<xref:System.Exception.Message%2A>","nodes":[]},{"pos":[490,500],"content":"<ph id=\"ph1\">`message`</ph>.","source":"`message`."},{"pos":[505,566],"content":"<xref:System.OperationCanceledException.CancellationToken%2A>","nodes":[]},{"pos":[567,575],"content":"<ph id=\"ph1\">`token`</ph>.","source":"`token`."}],"pos":[18547,19134],"yaml":true,"extradata":"MT"},{"content":"The error message that explains the reason for the exception.","nodes":[{"pos":[0,61],"content":"The error message that explains the reason for the exception.","nodes":[{"content":"The error message that explains the reason for the exception.","pos":[0,61]}]}],"pos":[19330,19392],"yaml":true},{"content":"A cancellation token associated with the operation that was canceled.","nodes":[{"pos":[0,69],"content":"A cancellation token associated with the operation that was canceled.","nodes":[{"content":"A cancellation token associated with the operation that was canceled.","pos":[0,69]}]}],"pos":[19474,19544],"yaml":true},{"content":"Initializes a new instance of the <xref href=\"System.OperationCanceledException\"></xref> class with a specified error message, a reference to the inner exception that is the cause of this exception, and a cancellation token.","nodes":[{"pos":[0,224],"content":"Initializes a new instance of the <ph id=\"ph1\">&lt;xref href=\"System.OperationCanceledException\"&gt;&lt;/xref&gt;</ph> class with a specified error message, a reference to the inner exception that is the cause of this exception, and a cancellation token.","source":"Initializes a new instance of the <xref href=\"System.OperationCanceledException\"></xref> class with a specified error message, a reference to the inner exception that is the cause of this exception, and a cancellation token."}],"pos":[21435,21660],"yaml":true},{"content":"The content of `message` is intended to be understood by humans. The caller of this constructor is required to ensure that this string has been localized for the current system culture.  \n  \n An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property. The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or `null` if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor.  \n  \n The following table shows the initial property values for an instance of <xref:System.OperationCanceledException>.  \n  \n|Property Type|Condition|  \n|-------------------|---------------|  \n|<xref:System.Exception.InnerException%2A>|`innerException`.|  \n|<xref:System.Exception.Message%2A>|`message`.|  \n|<xref:System.OperationCanceledException.CancellationToken%2A>|`token`.|","nodes":[{"pos":[0,185],"content":"The content of `message` is intended to be understood by humans. The caller of this constructor is required to ensure that this string has been localized for the current system culture.","nodes":[{"content":"The content of <ph id=\"ph1\">`message`</ph> is intended to be understood by humans.","pos":[0,64],"source":"The content of `message` is intended to be understood by humans."},{"content":"The caller of this constructor is required to ensure that this string has been localized for the current system culture.","pos":[65,185]}]},{"pos":[192,619],"content":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property. The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or `null` if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor.","nodes":[{"content":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <ph id=\"ph1\">&lt;xref:System.Exception.InnerException%2A&gt;</ph> property.","pos":[0,182],"source":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property."},{"content":"The <ph id=\"ph1\">&lt;xref:System.Exception.InnerException%2A&gt;</ph> property returns the same value that is passed into the constructor, or <ph id=\"ph2\">`null`</ph> if the <ph id=\"ph3\">&lt;xref:System.Exception.InnerException%2A&gt;</ph> property does not supply the inner exception value to the constructor.","pos":[183,427],"source":" The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or `null` if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor."}]},{"pos":[626,740],"content":"The following table shows the initial property values for an instance of <xref:System.OperationCanceledException>.","nodes":[{"content":"The following table shows the initial property values for an instance of <ph id=\"ph1\">&lt;xref:System.OperationCanceledException&gt;</ph>.","pos":[0,114],"source":"The following table shows the initial property values for an instance of <xref:System.OperationCanceledException>."}]},{"pos":[747,760],"content":"Property Type","nodes":[{"content":"Property Type","pos":[0,13]}]},{"pos":[761,770],"content":"Condition","nodes":[{"content":"Condition","pos":[0,9]}]},{"pos":[815,856],"content":"<xref:System.Exception.InnerException%2A>","nodes":[]},{"pos":[857,874],"content":"<ph id=\"ph1\">`innerException`</ph>.","source":"`innerException`."},{"pos":[879,913],"content":"<xref:System.Exception.Message%2A>","nodes":[]},{"pos":[914,924],"content":"<ph id=\"ph1\">`message`</ph>.","source":"`message`."},{"pos":[929,990],"content":"<xref:System.OperationCanceledException.CancellationToken%2A>","nodes":[]},{"pos":[991,999],"content":"<ph id=\"ph1\">`token`</ph>.","source":"`token`."}],"pos":[21671,22684],"yaml":true,"extradata":"MT"},{"content":"The error message that explains the reason for the exception.","nodes":[{"pos":[0,61],"content":"The error message that explains the reason for the exception.","nodes":[{"content":"The error message that explains the reason for the exception.","pos":[0,61]}]}],"pos":[22906,22968],"yaml":true},{"content":"The exception that is the cause of the current exception. If the <code>innerException</code> parameter is not `null`, the current exception is raised in a `catch` block that handles the inner exception.","nodes":[{"pos":[0,202],"content":"The exception that is the cause of the current exception. If the <code>innerException</code> parameter is not `null`, the current exception is raised in a `catch` block that handles the inner exception.","nodes":[{"content":"The exception that is the cause of the current exception.","pos":[0,57]},{"content":"If the <bpt id=\"p1\">&lt;code&gt;</bpt><ph id=\"ph1\">innerException</ph><ept id=\"p1\">&lt;/code&gt;</ept> parameter is not <ph id=\"ph2\">`null`</ph>, the current exception is raised in a <ph id=\"ph3\">`catch`</ph> block that handles the inner exception.","pos":[58,202],"source":" If the <code>innerException</code> parameter is not `null`, the current exception is raised in a `catch` block that handles the inner exception."}]}],"pos":[23041,23244],"yaml":true},{"content":"A cancellation token associated with the operation that was canceled.","nodes":[{"pos":[0,69],"content":"A cancellation token associated with the operation that was canceled.","nodes":[{"content":"A cancellation token associated with the operation that was canceled.","pos":[0,69]}]}],"pos":[23326,23396],"yaml":true},{"content":"Gets a token associated with the operation that was canceled.","nodes":[{"pos":[0,61],"content":"Gets a token associated with the operation that was canceled.","nodes":[{"content":"Gets a token associated with the operation that was canceled.","pos":[0,61]}]}],"pos":[24976,25038],"yaml":true},{"content":"If the token is associated with a canceled operation, the <xref:System.Threading.CancellationToken.IsCancellationRequested%2A?displayProperty=fullName> property of the token returns `true`.","nodes":[{"pos":[0,189],"content":"If the token is associated with a canceled operation, the <ph id=\"ph1\">&lt;xref:System.Threading.CancellationToken.IsCancellationRequested%2A?displayProperty=fullName&gt;</ph> property of the token returns <ph id=\"ph2\">`true`</ph>.","source":"If the token is associated with a canceled operation, the <xref:System.Threading.CancellationToken.IsCancellationRequested%2A?displayProperty=fullName> property of the token returns `true`."}],"pos":[25049,25239],"yaml":true,"extradata":"MT"},{"content":"A token associated with the operation that was canceled, or a default token.","nodes":[{"pos":[0,76],"content":"A token associated with the operation that was canceled, or a default token.","nodes":[{"content":"A token associated with the operation that was canceled, or a default token.","pos":[0,76]}]}],"pos":[25409,25486],"yaml":true}],"content":"### YamlMime:ManagedReference\nitems:\n- uid: System.OperationCanceledException\n  commentId: T:System.OperationCanceledException\n  id: OperationCanceledException\n  children:\n  - System.OperationCanceledException.#ctor\n  - System.OperationCanceledException.#ctor(System.String)\n  - System.OperationCanceledException.#ctor(System.Threading.CancellationToken)\n  - System.OperationCanceledException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  - System.OperationCanceledException.#ctor(System.String,System.Exception)\n  - System.OperationCanceledException.#ctor(System.String,System.Threading.CancellationToken)\n  - System.OperationCanceledException.#ctor(System.String,System.Exception,System.Threading.CancellationToken)\n  - System.OperationCanceledException.CancellationToken\n  langs:\n  - csharp\n  name: OperationCanceledException\n  nameWithType: OperationCanceledException\n  fullName: System.OperationCanceledException\n  type: Class\n  assemblies:\n  - System.Threading.Tasks\n  - mscorlib\n  - netstandard\n  namespace: System\n  summary: The exception that is thrown in a thread upon cancellation of an operation that the thread was executing.\n  remarks: If the task that was canceled had an associated cancellation token, it is returned by the <xref:System.OperationCanceledException.CancellationToken%2A> property, and the <xref:System.Threading.CancellationToken.IsCancellationRequested%2A?displayProperty=fullName> property of the token is set to `true`.\n  syntax:\n    content: >-\n      [System.Runtime.InteropServices.ComVisible(true)]\n\n      public class OperationCanceledException : SystemException\n  inheritance:\n  - System.Object\n  - System.Exception\n  derivedClasses:\n  - System.Threading.Tasks.TaskCanceledException\n  implements: []\n  inheritedMembers:\n  - System.Exception.Data\n  - System.Exception.GetBaseException\n  - System.Exception.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  - System.Exception.GetType\n  - System.Exception.HelpLink\n  - System.Exception.HResult\n  - System.Exception.InnerException\n  - System.Exception.Message\n  - System.Exception.SerializeObjectState\n  - System.Exception.Source\n  - System.Exception.StackTrace\n  - System.Exception.TargetSite\n  - System.Exception.ToString\n  - System.Object.Equals(System.Object)\n  - System.Object.Equals(System.Object,System.Object)\n  - System.Object.GetHashCode\n  - System.Object.MemberwiseClone\n  - System.Object.ReferenceEquals(System.Object,System.Object)\n  attributes:\n  - type: System.Runtime.InteropServices.ComVisibleAttribute\n  version:\n  - netcore-1.0\n  - netcore-1.1\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-1.0\n  - netstandard-1.1\n  - netstandard-1.2\n  - netstandard-1.3\n  - netstandard-1.4\n  - netstandard-1.6\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  monikers:\n  - netcore-1.0\n  - netcore-1.1\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-1.0\n  - netstandard-1.1\n  - netstandard-1.2\n  - netstandard-1.3\n  - netstandard-1.4\n  - netstandard-1.6\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System/OperationCanceledException.xml\n  ms.technology:\n  - dotnet-standard\n  author: rpetrusha\n  ms.author: ronpet\n  manager: wpickett\n- uid: System.OperationCanceledException.#ctor\n  commentId: M:System.OperationCanceledException.#ctor\n  id: '#ctor'\n  parent: System.OperationCanceledException\n  langs:\n  - csharp\n  name: OperationCanceledException()\n  nameWithType: OperationCanceledException.OperationCanceledException()\n  fullName: OperationCanceledException.OperationCanceledException()\n  type: Constructor\n  assemblies:\n  - System.Threading.Tasks\n  - mscorlib\n  - netstandard\n  namespace: System\n  summary: Initializes a new instance of the <xref href=\"System.OperationCanceledException\"></xref> class with a system-supplied error message.\n  remarks: \"This constructor initializes the <xref:System.Exception.Message%2A> property of the new instance to a system-supplied message that describes the error, such as \\\"The operation was canceled.\\\" This message takes into account the current system culture.  \\n  \\n The following table shows the initial property values for an instance of <xref:System.OperationCanceledException>.  \\n  \\n|Property|Value|  \\n|--------------|-----------|  \\n|<xref:System.Exception.InnerException%2A>|A nullreference (`Nothing` in Visual Basic).|  \\n|<xref:System.Exception.Message%2A>|The localized error message string.|  \\n|<xref:System.OperationCanceledException.CancellationToken%2A>|A cancellation token created in the non-canceled state.|\"\n  syntax:\n    content: public OperationCanceledException ();\n    parameters: []\n  overload: System.OperationCanceledException.#ctor*\n  exceptions: []\n  version:\n  - netcore-1.0\n  - netcore-1.1\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-1.0\n  - netstandard-1.1\n  - netstandard-1.2\n  - netstandard-1.3\n  - netstandard-1.4\n  - netstandard-1.6\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  monikers:\n  - netcore-1.0\n  - netcore-1.1\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-1.0\n  - netstandard-1.1\n  - netstandard-1.2\n  - netstandard-1.3\n  - netstandard-1.4\n  - netstandard-1.6\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System/OperationCanceledException.xml\n  ms.technology:\n  - dotnet-standard\n  author: rpetrusha\n  ms.author: ronpet\n  manager: wpickett\n- uid: System.OperationCanceledException.#ctor(System.String)\n  commentId: M:System.OperationCanceledException.#ctor(System.String)\n  id: '#ctor(System.String)'\n  parent: System.OperationCanceledException\n  langs:\n  - csharp\n  name: OperationCanceledException(String)\n  nameWithType: OperationCanceledException.OperationCanceledException(String)\n  fullName: OperationCanceledException.OperationCanceledException(String)\n  type: Constructor\n  assemblies:\n  - System.Threading.Tasks\n  - mscorlib\n  - netstandard\n  namespace: System\n  summary: Initializes a new instance of the <xref href=\"System.OperationCanceledException\"></xref> class with a specified error message.\n  remarks: \"The content of `message` is intended to be understood by humans. The caller of this constructor is required to ensure that this string has been localized for the current system culture.  \\n  \\n The following table shows the initial property values for an instance of <xref:System.OperationCanceledException>.  \\n  \\n|Property|Value|  \\n|--------------|-----------|  \\n|<xref:System.Exception.InnerException%2A>|A null reference (`Nothing` in Visual Basic).|  \\n|<xref:System.Exception.Message%2A>|The error message string.|  \\n|<xref:System.OperationCanceledException.CancellationToken%2A>|A cancellation token created in the non-canceled state.|\"\n  syntax:\n    content: public OperationCanceledException (string message);\n    parameters:\n    - id: message\n      type: System.String\n      description: A <xref href=\"System.String\"></xref> that describes the error.\n  overload: System.OperationCanceledException.#ctor*\n  exceptions: []\n  version:\n  - netcore-1.0\n  - netcore-1.1\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-1.0\n  - netstandard-1.1\n  - netstandard-1.2\n  - netstandard-1.3\n  - netstandard-1.4\n  - netstandard-1.6\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  monikers:\n  - netcore-1.0\n  - netcore-1.1\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-1.0\n  - netstandard-1.1\n  - netstandard-1.2\n  - netstandard-1.3\n  - netstandard-1.4\n  - netstandard-1.6\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System/OperationCanceledException.xml\n  ms.technology:\n  - dotnet-standard\n  author: rpetrusha\n  ms.author: ronpet\n  manager: wpickett\n- uid: System.OperationCanceledException.#ctor(System.Threading.CancellationToken)\n  commentId: M:System.OperationCanceledException.#ctor(System.Threading.CancellationToken)\n  id: '#ctor(System.Threading.CancellationToken)'\n  parent: System.OperationCanceledException\n  langs:\n  - csharp\n  name: OperationCanceledException(CancellationToken)\n  nameWithType: OperationCanceledException.OperationCanceledException(CancellationToken)\n  fullName: OperationCanceledException.OperationCanceledException(CancellationToken)\n  type: Constructor\n  assemblies:\n  - System.Threading.Tasks\n  - mscorlib\n  - netstandard\n  namespace: System\n  summary: Initializes a new instance of the <xref href=\"System.OperationCanceledException\"></xref> class with a cancellation token.\n  remarks: \"This constructor initializes the <xref:System.Exception.Message%2A> property of the new instance to a system-supplied message that describes the error, such as \\\"The operation was canceled.\\\" This message takes into account the current system culture.  \\n  \\n The following table shows the initial property values for an instance of <xref:System.OperationCanceledException>.  \\n  \\n|Property|Value|  \\n|--------------|-----------|  \\n|<xref:System.Exception.InnerException%2A>|A nullreference (`Nothing` in Visual Basic).|  \\n|<xref:System.Exception.Message%2A>|The localized error message string.|  \\n|<xref:System.OperationCanceledException.CancellationToken%2A>|`token`.|\"\n  syntax:\n    content: public OperationCanceledException (System.Threading.CancellationToken token);\n    parameters:\n    - id: token\n      type: System.Threading.CancellationToken\n      description: A cancellation token associated with the operation that was canceled.\n  overload: System.OperationCanceledException.#ctor*\n  exceptions: []\n  version:\n  - netcore-1.0\n  - netcore-1.1\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-1.0\n  - netstandard-1.1\n  - netstandard-1.2\n  - netstandard-1.3\n  - netstandard-1.4\n  - netstandard-1.6\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  monikers:\n  - netcore-1.0\n  - netcore-1.1\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-1.0\n  - netstandard-1.1\n  - netstandard-1.2\n  - netstandard-1.3\n  - netstandard-1.4\n  - netstandard-1.6\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System/OperationCanceledException.xml\n  ms.technology:\n  - dotnet-standard\n  author: rpetrusha\n  ms.author: ronpet\n  manager: wpickett\n- uid: System.OperationCanceledException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  commentId: M:System.OperationCanceledException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'\n  parent: System.OperationCanceledException\n  langs:\n  - csharp\n  name: OperationCanceledException(SerializationInfo, StreamingContext)\n  nameWithType: OperationCanceledException.OperationCanceledException(SerializationInfo, StreamingContext)\n  fullName: OperationCanceledException.OperationCanceledException(SerializationInfo, StreamingContext)\n  type: Constructor\n  assemblies:\n  - mscorlib\n  - netstandard\n  - System.Threading.Tasks\n  namespace: System\n  summary: Initializes a new instance of the <xref href=\"System.OperationCanceledException\"></xref> class with serialized data.\n  remarks: This constructor is called during deserialization to reconstitute the exception object transmitted over a stream. For more information, see [XML and SOAP Serialization](~/docs/framework/serialization/xml-and-soap-serialization.md)\n  syntax:\n    content: protected OperationCanceledException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);\n    parameters:\n    - id: info\n      type: System.Runtime.Serialization.SerializationInfo\n      description: The object that holds the serialized object data.\n    - id: context\n      type: System.Runtime.Serialization.StreamingContext\n      description: The contextual information about the source or destination.\n  overload: System.OperationCanceledException.#ctor*\n  exceptions: []\n  version:\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  monikers:\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System/OperationCanceledException.xml\n  ms.technology:\n  - dotnet-standard\n  author: rpetrusha\n  ms.author: ronpet\n  manager: wpickett\n- uid: System.OperationCanceledException.#ctor(System.String,System.Exception)\n  commentId: M:System.OperationCanceledException.#ctor(System.String,System.Exception)\n  id: '#ctor(System.String,System.Exception)'\n  parent: System.OperationCanceledException\n  langs:\n  - csharp\n  name: OperationCanceledException(String, Exception)\n  nameWithType: OperationCanceledException.OperationCanceledException(String, Exception)\n  fullName: OperationCanceledException.OperationCanceledException(String, Exception)\n  type: Constructor\n  assemblies:\n  - System.Threading.Tasks\n  - mscorlib\n  - netstandard\n  namespace: System\n  summary: Initializes a new instance of the <xref href=\"System.OperationCanceledException\"></xref> class with a specified error message and a reference to the inner exception that is the cause of this exception.\n  remarks: \"The content of `message` is intended to be understood by humans. The caller of this constructor is required to ensure that this string has been localized for the current system culture.  \\n  \\n An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property. The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or `null` if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor.  \\n  \\n The following table shows the initial property values for an instance of <xref:System.OperationCanceledException>.  \\n  \\n|Property Type|Condition|  \\n|-------------------|---------------|  \\n|<xref:System.Exception.InnerException%2A>|`innerException`.|  \\n|<xref:System.Exception.Message%2A>|`message`.|  \\n|<xref:System.OperationCanceledException.CancellationToken%2A>|A cancellation token created in the non-canceled state.|\"\n  syntax:\n    content: public OperationCanceledException (string message, Exception innerException);\n    parameters:\n    - id: message\n      type: System.String\n      description: The error message that explains the reason for the exception.\n    - id: innerException\n      type: System.Exception\n      description: The exception that is the cause of the current exception. If the <code>innerException</code> parameter is not `null`, the current exception is raised in a `catch` block that handles the inner exception.\n  overload: System.OperationCanceledException.#ctor*\n  exceptions: []\n  version:\n  - netcore-1.0\n  - netcore-1.1\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-1.0\n  - netstandard-1.1\n  - netstandard-1.2\n  - netstandard-1.3\n  - netstandard-1.4\n  - netstandard-1.6\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  monikers:\n  - netcore-1.0\n  - netcore-1.1\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-1.0\n  - netstandard-1.1\n  - netstandard-1.2\n  - netstandard-1.3\n  - netstandard-1.4\n  - netstandard-1.6\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System/OperationCanceledException.xml\n  ms.technology:\n  - dotnet-standard\n  author: rpetrusha\n  ms.author: ronpet\n  manager: wpickett\n- uid: System.OperationCanceledException.#ctor(System.String,System.Threading.CancellationToken)\n  commentId: M:System.OperationCanceledException.#ctor(System.String,System.Threading.CancellationToken)\n  id: '#ctor(System.String,System.Threading.CancellationToken)'\n  parent: System.OperationCanceledException\n  langs:\n  - csharp\n  name: OperationCanceledException(String, CancellationToken)\n  nameWithType: OperationCanceledException.OperationCanceledException(String, CancellationToken)\n  fullName: OperationCanceledException.OperationCanceledException(String, CancellationToken)\n  type: Constructor\n  assemblies:\n  - System.Threading.Tasks\n  - mscorlib\n  - netstandard\n  namespace: System\n  summary: Initializes a new instance of the <xref href=\"System.OperationCanceledException\"></xref> class with a specified error message and a cancellation token.\n  remarks: \"The content of `message` is intended to be understood by humans. The caller of this constructor is required to ensure that this string has been localized for the current system culture.  \\n  \\n The following table shows the initial property values for an instance of <xref:System.OperationCanceledException>.  \\n  \\n|Property|Value|  \\n|--------------|-----------|  \\n|<xref:System.Exception.InnerException%2A>|A null reference (`Nothing` in Visual Basic).|  \\n|<xref:System.Exception.Message%2A>|`message`.|  \\n|<xref:System.OperationCanceledException.CancellationToken%2A>|`token`.|\"\n  syntax:\n    content: public OperationCanceledException (string message, System.Threading.CancellationToken token);\n    parameters:\n    - id: message\n      type: System.String\n      description: The error message that explains the reason for the exception.\n    - id: token\n      type: System.Threading.CancellationToken\n      description: A cancellation token associated with the operation that was canceled.\n  overload: System.OperationCanceledException.#ctor*\n  exceptions: []\n  version:\n  - netcore-1.0\n  - netcore-1.1\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-1.0\n  - netstandard-1.1\n  - netstandard-1.2\n  - netstandard-1.3\n  - netstandard-1.4\n  - netstandard-1.6\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  monikers:\n  - netcore-1.0\n  - netcore-1.1\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-1.0\n  - netstandard-1.1\n  - netstandard-1.2\n  - netstandard-1.3\n  - netstandard-1.4\n  - netstandard-1.6\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System/OperationCanceledException.xml\n  ms.technology:\n  - dotnet-standard\n  author: rpetrusha\n  ms.author: ronpet\n  manager: wpickett\n- uid: System.OperationCanceledException.#ctor(System.String,System.Exception,System.Threading.CancellationToken)\n  commentId: M:System.OperationCanceledException.#ctor(System.String,System.Exception,System.Threading.CancellationToken)\n  id: '#ctor(System.String,System.Exception,System.Threading.CancellationToken)'\n  parent: System.OperationCanceledException\n  langs:\n  - csharp\n  name: OperationCanceledException(String, Exception, CancellationToken)\n  nameWithType: OperationCanceledException.OperationCanceledException(String, Exception, CancellationToken)\n  fullName: OperationCanceledException.OperationCanceledException(String, Exception, CancellationToken)\n  type: Constructor\n  assemblies:\n  - System.Threading.Tasks\n  - mscorlib\n  - netstandard\n  namespace: System\n  summary: Initializes a new instance of the <xref href=\"System.OperationCanceledException\"></xref> class with a specified error message, a reference to the inner exception that is the cause of this exception, and a cancellation token.\n  remarks: \"The content of `message` is intended to be understood by humans. The caller of this constructor is required to ensure that this string has been localized for the current system culture.  \\n  \\n An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property. The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or `null` if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor.  \\n  \\n The following table shows the initial property values for an instance of <xref:System.OperationCanceledException>.  \\n  \\n|Property Type|Condition|  \\n|-------------------|---------------|  \\n|<xref:System.Exception.InnerException%2A>|`innerException`.|  \\n|<xref:System.Exception.Message%2A>|`message`.|  \\n|<xref:System.OperationCanceledException.CancellationToken%2A>|`token`.|\"\n  syntax:\n    content: public OperationCanceledException (string message, Exception innerException, System.Threading.CancellationToken token);\n    parameters:\n    - id: message\n      type: System.String\n      description: The error message that explains the reason for the exception.\n    - id: innerException\n      type: System.Exception\n      description: The exception that is the cause of the current exception. If the <code>innerException</code> parameter is not `null`, the current exception is raised in a `catch` block that handles the inner exception.\n    - id: token\n      type: System.Threading.CancellationToken\n      description: A cancellation token associated with the operation that was canceled.\n  overload: System.OperationCanceledException.#ctor*\n  exceptions: []\n  version:\n  - netcore-1.0\n  - netcore-1.1\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-1.0\n  - netstandard-1.1\n  - netstandard-1.2\n  - netstandard-1.3\n  - netstandard-1.4\n  - netstandard-1.6\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  monikers:\n  - netcore-1.0\n  - netcore-1.1\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-1.0\n  - netstandard-1.1\n  - netstandard-1.2\n  - netstandard-1.3\n  - netstandard-1.4\n  - netstandard-1.6\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System/OperationCanceledException.xml\n  ms.technology:\n  - dotnet-standard\n  author: rpetrusha\n  ms.author: ronpet\n  manager: wpickett\n- uid: System.OperationCanceledException.CancellationToken\n  commentId: P:System.OperationCanceledException.CancellationToken\n  id: CancellationToken\n  parent: System.OperationCanceledException\n  langs:\n  - csharp\n  name: CancellationToken\n  nameWithType: OperationCanceledException.CancellationToken\n  fullName: OperationCanceledException.CancellationToken\n  type: Property\n  assemblies:\n  - System.Threading.Tasks\n  - mscorlib\n  - netstandard\n  namespace: System\n  summary: Gets a token associated with the operation that was canceled.\n  remarks: If the token is associated with a canceled operation, the <xref:System.Threading.CancellationToken.IsCancellationRequested%2A?displayProperty=fullName> property of the token returns `true`.\n  syntax:\n    content: public System.Threading.CancellationToken CancellationToken { get; }\n    return:\n      type: System.Threading.CancellationToken\n      description: A token associated with the operation that was canceled, or a default token.\n  overload: System.OperationCanceledException.CancellationToken*\n  exceptions: []\n  version:\n  - netcore-1.0\n  - netcore-1.1\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-1.0\n  - netstandard-1.1\n  - netstandard-1.2\n  - netstandard-1.3\n  - netstandard-1.4\n  - netstandard-1.6\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  monikers:\n  - netcore-1.0\n  - netcore-1.1\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-1.0\n  - netstandard-1.1\n  - netstandard-1.2\n  - netstandard-1.3\n  - netstandard-1.4\n  - netstandard-1.6\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System/OperationCanceledException.xml\n  ms.technology:\n  - dotnet-standard\n  author: rpetrusha\n  ms.author: ronpet\n  manager: wpickett\nreferences:\n- uid: System.Exception\n  parent: System\n  isExternal: false\n  name: Exception\n  nameWithType: Exception\n  fullName: System.Exception\n- uid: System.OperationCanceledException.#ctor\n  parent: System.OperationCanceledException\n  isExternal: false\n  name: OperationCanceledException()\n  nameWithType: OperationCanceledException.OperationCanceledException()\n  fullName: OperationCanceledException.OperationCanceledException()\n- uid: System.OperationCanceledException.#ctor(System.String)\n  parent: System.OperationCanceledException\n  isExternal: false\n  name: OperationCanceledException(String)\n  nameWithType: OperationCanceledException.OperationCanceledException(String)\n  fullName: OperationCanceledException.OperationCanceledException(String)\n- uid: System.String\n  parent: System\n  isExternal: false\n  name: String\n  nameWithType: String\n  fullName: System.String\n- uid: System.OperationCanceledException.#ctor(System.Threading.CancellationToken)\n  parent: System.OperationCanceledException\n  isExternal: false\n  name: OperationCanceledException(CancellationToken)\n  nameWithType: OperationCanceledException.OperationCanceledException(CancellationToken)\n  fullName: OperationCanceledException.OperationCanceledException(CancellationToken)\n- uid: System.Threading.CancellationToken\n  parent: System.Threading\n  isExternal: false\n  name: CancellationToken\n  nameWithType: CancellationToken\n  fullName: System.Threading.CancellationToken\n- uid: System.OperationCanceledException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  parent: System.OperationCanceledException\n  isExternal: false\n  name: OperationCanceledException(SerializationInfo, StreamingContext)\n  nameWithType: OperationCanceledException.OperationCanceledException(SerializationInfo, StreamingContext)\n  fullName: OperationCanceledException.OperationCanceledException(SerializationInfo, StreamingContext)\n- uid: System.Runtime.Serialization.SerializationInfo\n  parent: System.Runtime.Serialization\n  isExternal: false\n  name: SerializationInfo\n  nameWithType: SerializationInfo\n  fullName: System.Runtime.Serialization.SerializationInfo\n- uid: System.Runtime.Serialization.StreamingContext\n  parent: System.Runtime.Serialization\n  isExternal: false\n  name: StreamingContext\n  nameWithType: StreamingContext\n  fullName: System.Runtime.Serialization.StreamingContext\n- uid: System.OperationCanceledException.#ctor(System.String,System.Exception)\n  parent: System.OperationCanceledException\n  isExternal: false\n  name: OperationCanceledException(String, Exception)\n  nameWithType: OperationCanceledException.OperationCanceledException(String, Exception)\n  fullName: OperationCanceledException.OperationCanceledException(String, Exception)\n- uid: System.OperationCanceledException.#ctor(System.String,System.Threading.CancellationToken)\n  parent: System.OperationCanceledException\n  isExternal: false\n  name: OperationCanceledException(String, CancellationToken)\n  nameWithType: OperationCanceledException.OperationCanceledException(String, CancellationToken)\n  fullName: OperationCanceledException.OperationCanceledException(String, CancellationToken)\n- uid: System.OperationCanceledException.#ctor(System.String,System.Exception,System.Threading.CancellationToken)\n  parent: System.OperationCanceledException\n  isExternal: false\n  name: OperationCanceledException(String, Exception, CancellationToken)\n  nameWithType: OperationCanceledException.OperationCanceledException(String, Exception, CancellationToken)\n  fullName: OperationCanceledException.OperationCanceledException(String, Exception, CancellationToken)\n- uid: System.OperationCanceledException.CancellationToken\n  parent: System.OperationCanceledException\n  isExternal: false\n  name: CancellationToken\n  nameWithType: OperationCanceledException.CancellationToken\n  fullName: OperationCanceledException.CancellationToken\n- uid: System.OperationCanceledException.#ctor*\n  parent: System.OperationCanceledException\n  isExternal: false\n  name: OperationCanceledException\n  nameWithType: OperationCanceledException.OperationCanceledException\n  fullName: OperationCanceledException.OperationCanceledException\n  monikers:\n  - netcore-1.0\n  - netcore-1.1\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-1.0\n  - netstandard-1.1\n  - netstandard-1.2\n  - netstandard-1.3\n  - netstandard-1.4\n  - netstandard-1.6\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System/OperationCanceledException.xml\n- uid: System.OperationCanceledException.CancellationToken*\n  parent: System.OperationCanceledException\n  isExternal: false\n  name: CancellationToken\n  nameWithType: OperationCanceledException.CancellationToken\n  fullName: OperationCanceledException.CancellationToken\n  monikers:\n  - netcore-1.0\n  - netcore-1.1\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-1.0\n  - netstandard-1.1\n  - netstandard-1.2\n  - netstandard-1.3\n  - netstandard-1.4\n  - netstandard-1.6\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System/OperationCanceledException.xml\n- uid: System.Object.Equals(System.Object)\n  parent: System.Object\n  isExternal: false\n  name: Equals(Object)\n  nameWithType: Object.Equals(Object)\n  fullName: Object.Equals(Object)\n- uid: System.Object.Equals(System.Object,System.Object)\n  parent: System.Object\n  isExternal: false\n  name: Equals(Object, Object)\n  nameWithType: Object.Equals(Object, Object)\n  fullName: Object.Equals(Object, Object)\n- uid: System.Object.GetHashCode\n  parent: System.Object\n  isExternal: false\n  name: GetHashCode()\n  nameWithType: Object.GetHashCode()\n  fullName: Object.GetHashCode()\n- uid: System.Exception.GetType\n  parent: System.Exception\n  isExternal: false\n  name: GetType()\n  nameWithType: Exception.GetType()\n  fullName: Exception.GetType()\n- uid: System.Object.MemberwiseClone\n  parent: System.Object\n  isExternal: false\n  name: MemberwiseClone()\n  nameWithType: Object.MemberwiseClone()\n  fullName: Object.MemberwiseClone()\n- uid: System.Object.ReferenceEquals(System.Object,System.Object)\n  parent: System.Object\n  isExternal: false\n  name: ReferenceEquals(Object, Object)\n  nameWithType: Object.ReferenceEquals(Object, Object)\n  fullName: Object.ReferenceEquals(Object, Object)\n- uid: System.Exception.ToString\n  parent: System.Exception\n  isExternal: false\n  name: ToString()\n  nameWithType: Exception.ToString()\n  fullName: Exception.ToString()\n- uid: System.Exception.Data\n  parent: System.Exception\n  isExternal: false\n  name: Data\n  nameWithType: Exception.Data\n  fullName: Exception.Data\n- uid: System.Exception.GetBaseException\n  parent: System.Exception\n  isExternal: false\n  name: GetBaseException()\n  nameWithType: Exception.GetBaseException()\n  fullName: Exception.GetBaseException()\n- uid: System.Exception.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  parent: System.Exception\n  isExternal: false\n  name: GetObjectData(SerializationInfo, StreamingContext)\n  nameWithType: Exception.GetObjectData(SerializationInfo, StreamingContext)\n  fullName: Exception.GetObjectData(SerializationInfo, StreamingContext)\n- uid: System.Exception.HelpLink\n  parent: System.Exception\n  isExternal: false\n  name: HelpLink\n  nameWithType: Exception.HelpLink\n  fullName: Exception.HelpLink\n- uid: System.Exception.HResult\n  parent: System.Exception\n  isExternal: false\n  name: HResult\n  nameWithType: Exception.HResult\n  fullName: Exception.HResult\n- uid: System.Exception.InnerException\n  parent: System.Exception\n  isExternal: false\n  name: InnerException\n  nameWithType: Exception.InnerException\n  fullName: Exception.InnerException\n- uid: System.Exception.Message\n  parent: System.Exception\n  isExternal: false\n  name: Message\n  nameWithType: Exception.Message\n  fullName: Exception.Message\n- uid: System.Exception.SerializeObjectState\n  parent: System.Exception\n  isExternal: false\n  name: SerializeObjectState\n  nameWithType: Exception.SerializeObjectState\n  fullName: Exception.SerializeObjectState\n- uid: System.Exception.Source\n  parent: System.Exception\n  isExternal: false\n  name: Source\n  nameWithType: Exception.Source\n  fullName: Exception.Source\n- uid: System.Exception.StackTrace\n  parent: System.Exception\n  isExternal: false\n  name: StackTrace\n  nameWithType: Exception.StackTrace\n  fullName: Exception.StackTrace\n- uid: System.Exception.TargetSite\n  parent: System.Exception\n  isExternal: false\n  name: TargetSite\n  nameWithType: Exception.TargetSite\n  fullName: Exception.TargetSite\n"}