{"nodes":[{"content":"The exception that is thrown when there is an invalid attempt to access a private or protected field inside a class.","nodes":[{"pos":[0,116],"content":"The exception that is thrown when there is an invalid attempt to access a private or protected field inside a class.","nodes":[{"content":"The exception that is thrown when there is an invalid attempt to access a private or protected field inside a class.","pos":[0,116]}]}],"pos":[679,796],"yaml":true},{"content":"This exception is typically thrown when the access level of a field in a class library is changed, and one or more assemblies referencing the library have not been recompiled.  \n  \n <xref:System.FieldAccessException> uses the HRESULT COR_E_FIELDACCESS, which has the value 0x80131507.  \n  \n For a list of initial property values for an instance of <xref:System.FieldAccessException>, see the <xref:System.FieldAccessException.%23ctor%2A> constructors.  \n  \n> [!NOTE]\n>  This exception is not included in the [.NET for Windows Store apps](http://go.microsoft.com/fwlink/?LinkID=247912) or the , but it is thrown by some members that are. To catch the exception in that case, write a `catch` statement for <xref:System.MemberAccessException> instead.","nodes":[{"pos":[0,175],"content":"This exception is typically thrown when the access level of a field in a class library is changed, and one or more assemblies referencing the library have not been recompiled.","nodes":[{"content":"This exception is typically thrown when the access level of a field in a class library is changed, and one or more assemblies referencing the library have not been recompiled.","pos":[0,175]}]},{"pos":[182,284],"content":"<xref:System.FieldAccessException> uses the HRESULT COR_E_FIELDACCESS, which has the value 0x80131507.","nodes":[{"content":"<ph id=\"ph1\">&lt;xref:System.FieldAccessException&gt;</ph> uses the HRESULT COR_E_FIELDACCESS, which has the value 0x80131507.","pos":[0,102],"source":"<xref:System.FieldAccessException> uses the HRESULT COR_E_FIELDACCESS, which has the value 0x80131507."}]},{"pos":[291,451],"content":"For a list of initial property values for an instance of <xref:System.FieldAccessException>, see the <xref:System.FieldAccessException.%23ctor%2A> constructors.","nodes":[{"content":"For a list of initial property values for an instance of <ph id=\"ph1\">&lt;xref:System.FieldAccessException&gt;</ph>, see the <ph id=\"ph2\">&lt;xref:System.FieldAccessException.%23ctor%2A&gt;</ph> constructors.","pos":[0,160],"source":"For a list of initial property values for an instance of <xref:System.FieldAccessException>, see the <xref:System.FieldAccessException.%23ctor%2A> constructors."}]},{"pos":[459,748],"content":"[!NOTE]\n This exception is not included in the [.NET for Windows Store apps](http://go.microsoft.com/fwlink/?LinkID=247912) or the , but it is thrown by some members that are. To catch the exception in that case, write a `catch` statement for <xref:System.MemberAccessException> instead.","leadings":["","> "],"nodes":[{"content":" This exception is not included in the [.NET for Windows Store apps](http://go.microsoft.com/fwlink/?LinkID=247912) or the , but it is thrown by some members that are. To catch the exception in that case, write a `catch` statement for <xref:System.MemberAccessException> instead.","pos":[8,287],"nodes":[{"content":"This exception is not included in the <bpt id=\"p1\">[</bpt>.NET for Windows Store apps<ept id=\"p1\">](http://go.microsoft.com/fwlink/?LinkID=247912)</ept> or the , but it is thrown by some members that are.","pos":[1,167],"source":" This exception is not included in the [.NET for Windows Store apps](http://go.microsoft.com/fwlink/?LinkID=247912) or the , but it is thrown by some members that are."},{"content":"To catch the exception in that case, write a <ph id=\"ph1\">`catch`</ph> statement for <ph id=\"ph2\">&lt;xref:System.MemberAccessException&gt;</ph> instead.","pos":[168,279],"source":" To catch the exception in that case, write a `catch` statement for <xref:System.MemberAccessException> instead."}]}]}],"pos":[807,1565],"yaml":true,"extradata":"MT"},{"content":"Initializes a new instance of the <xref href=\"System.FieldAccessException\"></xref> class.","nodes":[{"pos":[0,89],"content":"Initializes a new instance of the <ph id=\"ph1\">&lt;xref href=\"System.FieldAccessException\"&gt;&lt;/xref&gt;</ph> class.","source":"Initializes a new instance of the <xref href=\"System.FieldAccessException\"></xref> class."}],"pos":[4012,4102],"yaml":true},{"content":"This constructor initializes the <xref:System.Exception.Message%2A> property of the new instance to a system-supplied message that describes the error, such as \"Attempted to access a field that is not accessible by the caller.\" This message takes the current system culture into account.  \n  \n The following table shows the initial property values for an instance of <xref:System.FieldAccessException>.  \n  \n|Property|Value|  \n|--------------|-----------|  \n|<xref:System.Exception.InnerException%2A>|A null reference (`Nothing` in Visual Basic).|  \n|<xref:System.Exception.Message%2A>|The localized error message string.|","nodes":[{"pos":[0,287],"content":"This constructor initializes the <xref:System.Exception.Message%2A> property of the new instance to a system-supplied message that describes the error, such as \"Attempted to access a field that is not accessible by the caller.\" This message takes the current system culture into account.","nodes":[{"content":"This constructor initializes the <xref:System.Exception.Message%2A> property of the new instance to a system-supplied message that describes the error, such as \"Attempted to access a field that is not accessible by the caller.\" This message takes the current system culture into account.","pos":[0,287],"nodes":[{"content":"This constructor initializes the <ph id=\"ph1\">&lt;xref:System.Exception.Message%2A&gt;</ph> property of the new instance to a system-supplied message that describes the error, such as \"Attempted to access a field that is not accessible by the caller.\"","pos":[0,227],"source":"This constructor initializes the <xref:System.Exception.Message%2A> property of the new instance to a system-supplied message that describes the error, such as \"Attempted to access a field that is not accessible by the caller.\""},{"content":"This message takes the current system culture into account.","pos":[228,287]}]}]},{"pos":[294,402],"content":"The following table shows the initial property values for an instance of <xref:System.FieldAccessException>.","nodes":[{"content":"The following table shows the initial property values for an instance of <ph id=\"ph1\">&lt;xref:System.FieldAccessException&gt;</ph>.","pos":[0,108],"source":"The following table shows the initial property values for an instance of <xref:System.FieldAccessException>."}]},{"pos":[409,417],"content":"Property","nodes":[{"content":"Property","pos":[0,8]}]},{"pos":[418,423],"content":"Value","nodes":[{"content":"Value","pos":[0,5]}]},{"pos":[459,500],"content":"<xref:System.Exception.InnerException%2A>","nodes":[]},{"pos":[501,546],"content":"A null reference (<ph id=\"ph1\">`Nothing`</ph> in Visual Basic).","source":"A null reference (`Nothing` in Visual Basic)."},{"pos":[551,585],"content":"<xref:System.Exception.Message%2A>","nodes":[]},{"pos":[586,621],"content":"The localized error message string.","nodes":[{"content":"The localized error message string.","pos":[0,35]}]}],"pos":[4113,4747],"yaml":true,"extradata":"MT"},{"content":"Initializes a new instance of the <xref href=\"System.FieldAccessException\"></xref> class with a specified error message.","nodes":[{"pos":[0,120],"content":"Initializes a new instance of the <ph id=\"ph1\">&lt;xref href=\"System.FieldAccessException\"&gt;&lt;/xref&gt;</ph> class with a specified error message.","source":"Initializes a new instance of the <xref href=\"System.FieldAccessException\"></xref> class with a specified error message."}],"pos":[6318,6439],"yaml":true},{"content":"This constructor initializes the <xref:System.Exception.Message%2A> property of the new instance by using the `message` parameter. The content of `message` is intended to be understood by humans. The caller of this constructor must ensure that this string has been localized for the current system culture.  \n  \n The following table shows the initial property values for an instance of <xref:System.FieldAccessException>.  \n  \n|Property|Value|  \n|--------------|-----------|  \n|<xref:System.Exception.InnerException%2A>|A null reference (`Nothing` in Visual Basic).|  \n|<xref:System.Exception.Message%2A>|The localized error message string.|","nodes":[{"pos":[0,306],"content":"This constructor initializes the <xref:System.Exception.Message%2A> property of the new instance by using the `message` parameter. The content of `message` is intended to be understood by humans. The caller of this constructor must ensure that this string has been localized for the current system culture.","nodes":[{"content":"This constructor initializes the <ph id=\"ph1\">&lt;xref:System.Exception.Message%2A&gt;</ph> property of the new instance by using the <ph id=\"ph2\">`message`</ph> parameter.","pos":[0,130],"source":"This constructor initializes the <xref:System.Exception.Message%2A> property of the new instance by using the `message` parameter."},{"content":"The content of <ph id=\"ph1\">`message`</ph> is intended to be understood by humans.","pos":[131,195],"source":" The content of `message` is intended to be understood by humans."},{"content":"The caller of this constructor must ensure that this string has been localized for the current system culture.","pos":[196,306]}]},{"pos":[313,421],"content":"The following table shows the initial property values for an instance of <xref:System.FieldAccessException>.","nodes":[{"content":"The following table shows the initial property values for an instance of <ph id=\"ph1\">&lt;xref:System.FieldAccessException&gt;</ph>.","pos":[0,108],"source":"The following table shows the initial property values for an instance of <xref:System.FieldAccessException>."}]},{"pos":[428,436],"content":"Property","nodes":[{"content":"Property","pos":[0,8]}]},{"pos":[437,442],"content":"Value","nodes":[{"content":"Value","pos":[0,5]}]},{"pos":[478,519],"content":"<xref:System.Exception.InnerException%2A>","nodes":[]},{"pos":[520,565],"content":"A null reference (<ph id=\"ph1\">`Nothing`</ph> in Visual Basic).","source":"A null reference (`Nothing` in Visual Basic)."},{"pos":[570,604],"content":"<xref:System.Exception.Message%2A>","nodes":[]},{"pos":[605,640],"content":"The localized error message string.","nodes":[{"content":"The localized error message string.","pos":[0,35]}]}],"pos":[6450,7101],"yaml":true,"extradata":"MT"},{"content":"The error message that explains the reason for the exception.","nodes":[{"pos":[0,61],"content":"The error message that explains the reason for the exception.","nodes":[{"content":"The error message that explains the reason for the exception.","pos":[0,61]}]}],"pos":[7249,7311],"yaml":true},{"content":"Initializes a new instance of the <xref href=\"System.FieldAccessException\"></xref> class with serialized data.","nodes":[{"pos":[0,110],"content":"Initializes a new instance of the <ph id=\"ph1\">&lt;xref href=\"System.FieldAccessException\"&gt;&lt;/xref&gt;</ph> class with serialized data.","source":"Initializes a new instance of the <xref href=\"System.FieldAccessException\"></xref> class with serialized data."}],"pos":[9132,9243],"yaml":true},{"content":"This constructor is called during deserialization to reconstitute the exception object that was transmitted over a stream.","nodes":[{"pos":[0,122],"content":"This constructor is called during deserialization to reconstitute the exception object that was transmitted over a stream.","nodes":[{"content":"This constructor is called during deserialization to reconstitute the exception object that was transmitted over a stream.","pos":[0,122]}]}],"pos":[9254,9377],"yaml":true,"extradata":"MT"},{"content":"The object that holds the serialized object data.","nodes":[{"pos":[0,49],"content":"The object that holds the serialized object data.","nodes":[{"content":"The object that holds the serialized object data.","pos":[0,49]}]}],"pos":[9650,9700],"yaml":true},{"content":"The contextual information about the source or destination.","nodes":[{"pos":[0,59],"content":"The contextual information about the source or destination.","nodes":[{"content":"The contextual information about the source or destination.","pos":[0,59]}]}],"pos":[9795,9855],"yaml":true},{"content":"Initializes a new instance of the <xref href=\"System.FieldAccessException\"></xref> class with a specified error message and a reference to the inner exception that is the cause of this exception.","nodes":[{"pos":[0,195],"content":"Initializes a new instance of the <ph id=\"ph1\">&lt;xref href=\"System.FieldAccessException\"&gt;&lt;/xref&gt;</ph> class with a specified error message and a reference to the inner exception that is the cause of this exception.","source":"Initializes a new instance of the <xref href=\"System.FieldAccessException\"></xref> class with a specified error message and a reference to the inner exception that is the cause of this exception."}],"pos":[11212,11408],"yaml":true},{"content":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property. The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or returns `null` if it does not supply the inner exception value to the constructor. The caller of this constructor must ensure that this string has been localized for the current system culture.  \n  \n The following table shows the initial property values for an instance of <xref:System.FieldAccessException>.  \n  \n|Property|Value|  \n|--------------|-----------|  \n|<xref:System.Exception.InnerException%2A>|The inner exception reference.|  \n|<xref:System.Exception.Message%2A>|The localized error message string.|","nodes":[{"pos":[0,494],"content":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property. The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or returns `null` if it does not supply the inner exception value to the constructor. The caller of this constructor must ensure that this string has been localized for the current system culture.","nodes":[{"content":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <ph id=\"ph1\">&lt;xref:System.Exception.InnerException%2A&gt;</ph> property.","pos":[0,182],"source":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property."},{"content":"The <ph id=\"ph1\">&lt;xref:System.Exception.InnerException%2A&gt;</ph> property returns the same value that is passed into the constructor, or returns <ph id=\"ph2\">`null`</ph> if it does not supply the inner exception value to the constructor.","pos":[183,383],"source":" The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or returns `null` if it does not supply the inner exception value to the constructor."},{"content":"The caller of this constructor must ensure that this string has been localized for the current system culture.","pos":[384,494]}]},{"pos":[501,609],"content":"The following table shows the initial property values for an instance of <xref:System.FieldAccessException>.","nodes":[{"content":"The following table shows the initial property values for an instance of <ph id=\"ph1\">&lt;xref:System.FieldAccessException&gt;</ph>.","pos":[0,108],"source":"The following table shows the initial property values for an instance of <xref:System.FieldAccessException>."}]},{"pos":[616,624],"content":"Property","nodes":[{"content":"Property","pos":[0,8]}]},{"pos":[625,630],"content":"Value","nodes":[{"content":"Value","pos":[0,5]}]},{"pos":[666,707],"content":"<xref:System.Exception.InnerException%2A>","nodes":[]},{"pos":[708,738],"content":"The inner exception reference.","nodes":[{"content":"The inner exception reference.","pos":[0,30]}]},{"pos":[743,777],"content":"<xref:System.Exception.Message%2A>","nodes":[]},{"pos":[778,813],"content":"The localized error message string.","nodes":[{"content":"The localized error message string.","pos":[0,35]}]}],"pos":[11419,12243],"yaml":true,"extradata":"MT"},{"content":"The error message that explains the reason for the exception.","nodes":[{"pos":[0,61],"content":"The error message that explains the reason for the exception.","nodes":[{"content":"The error message that explains the reason for the exception.","pos":[0,61]}]}],"pos":[12408,12470],"yaml":true},{"content":"The exception that is the cause of the current exception. If the <code>inner</code> parameter is not `null`, the current exception is raised in a `catch` block that handles the inner exception.","nodes":[{"pos":[0,193],"content":"The exception that is the cause of the current exception. If the <code>inner</code> parameter is not `null`, the current exception is raised in a `catch` block that handles the inner exception.","nodes":[{"content":"The exception that is the cause of the current exception.","pos":[0,57]},{"content":"If the <bpt id=\"p1\">&lt;code&gt;</bpt><ph id=\"ph1\">inner</ph><ept id=\"p1\">&lt;/code&gt;</ept> parameter is not <ph id=\"ph2\">`null`</ph>, the current exception is raised in a <ph id=\"ph3\">`catch`</ph> block that handles the inner exception.","pos":[58,193],"source":" If the <code>inner</code> parameter is not `null`, the current exception is raised in a `catch` block that handles the inner exception."}]}],"pos":[12534,12728],"yaml":true}],"content":"### YamlMime:ManagedReference\nitems:\n- uid: System.FieldAccessException\n  commentId: T:System.FieldAccessException\n  id: FieldAccessException\n  children:\n  - System.FieldAccessException.#ctor\n  - System.FieldAccessException.#ctor(System.String)\n  - System.FieldAccessException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  - System.FieldAccessException.#ctor(System.String,System.Exception)\n  langs:\n  - csharp\n  name: FieldAccessException\n  nameWithType: FieldAccessException\n  fullName: System.FieldAccessException\n  type: Class\n  assemblies:\n  - System.Runtime\n  - mscorlib\n  - netstandard\n  namespace: System\n  summary: The exception that is thrown when there is an invalid attempt to access a private or protected field inside a class.\n  remarks: \"This exception is typically thrown when the access level of a field in a class library is changed, and one or more assemblies referencing the library have not been recompiled.  \\n  \\n <xref:System.FieldAccessException> uses the HRESULT COR_E_FIELDACCESS, which has the value 0x80131507.  \\n  \\n For a list of initial property values for an instance of <xref:System.FieldAccessException>, see the <xref:System.FieldAccessException.%23ctor%2A> constructors.  \\n  \\n> [!NOTE]\\n>  This exception is not included in the [.NET for Windows Store apps](http://go.microsoft.com/fwlink/?LinkID=247912) or the , but it is thrown by some members that are. To catch the exception in that case, write a `catch` statement for <xref:System.MemberAccessException> instead.\"\n  syntax:\n    content: >-\n      [System.Runtime.InteropServices.ComVisible(true)]\n\n      public class FieldAccessException : MemberAccessException\n  inheritance:\n  - System.Object\n  - System.Exception\n  - System.MemberAccessException\n  implements: []\n  inheritedMembers:\n  - System.Exception.Data\n  - System.Exception.GetBaseException\n  - System.Exception.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  - System.Exception.GetType\n  - System.Exception.HelpLink\n  - System.Exception.HResult\n  - System.Exception.InnerException\n  - System.Exception.Message\n  - System.Exception.SerializeObjectState\n  - System.Exception.Source\n  - System.Exception.StackTrace\n  - System.Exception.TargetSite\n  - System.Exception.ToString\n  - System.Object.Equals(System.Object)\n  - System.Object.Equals(System.Object,System.Object)\n  - System.Object.GetHashCode\n  - System.Object.MemberwiseClone\n  - System.Object.ReferenceEquals(System.Object,System.Object)\n  attributes:\n  - type: System.Runtime.InteropServices.ComVisibleAttribute\n  version:\n  - netcore-1.0\n  - netcore-1.1\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-1.3\n  - netstandard-1.4\n  - netstandard-1.5\n  - netstandard-1.6\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  monikers:\n  - netcore-1.0\n  - netcore-1.1\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-1.3\n  - netstandard-1.4\n  - netstandard-1.5\n  - netstandard-1.6\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System/FieldAccessException.xml\n  ms.technology:\n  - dotnet-standard\n  author: rpetrusha\n  ms.author: ronpet\n  manager: wpickett\n- uid: System.FieldAccessException.#ctor\n  commentId: M:System.FieldAccessException.#ctor\n  id: '#ctor'\n  parent: System.FieldAccessException\n  langs:\n  - csharp\n  name: FieldAccessException()\n  nameWithType: FieldAccessException.FieldAccessException()\n  fullName: FieldAccessException.FieldAccessException()\n  type: Constructor\n  assemblies:\n  - System.Runtime\n  - mscorlib\n  - netstandard\n  namespace: System\n  summary: Initializes a new instance of the <xref href=\"System.FieldAccessException\"></xref> class.\n  remarks: \"This constructor initializes the <xref:System.Exception.Message%2A> property of the new instance to a system-supplied message that describes the error, such as \\\"Attempted to access a field that is not accessible by the caller.\\\" This message takes the current system culture into account.  \\n  \\n The following table shows the initial property values for an instance of <xref:System.FieldAccessException>.  \\n  \\n|Property|Value|  \\n|--------------|-----------|  \\n|<xref:System.Exception.InnerException%2A>|A null reference (`Nothing` in Visual Basic).|  \\n|<xref:System.Exception.Message%2A>|The localized error message string.|\"\n  syntax:\n    content: public FieldAccessException ();\n    parameters: []\n  overload: System.FieldAccessException.#ctor*\n  exceptions: []\n  version:\n  - netcore-1.0\n  - netcore-1.1\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-1.3\n  - netstandard-1.4\n  - netstandard-1.5\n  - netstandard-1.6\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  monikers:\n  - netcore-1.0\n  - netcore-1.1\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-1.3\n  - netstandard-1.4\n  - netstandard-1.5\n  - netstandard-1.6\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System/FieldAccessException.xml\n  ms.technology:\n  - dotnet-standard\n  author: rpetrusha\n  ms.author: ronpet\n  manager: wpickett\n- uid: System.FieldAccessException.#ctor(System.String)\n  commentId: M:System.FieldAccessException.#ctor(System.String)\n  id: '#ctor(System.String)'\n  parent: System.FieldAccessException\n  langs:\n  - csharp\n  name: FieldAccessException(String)\n  nameWithType: FieldAccessException.FieldAccessException(String)\n  fullName: FieldAccessException.FieldAccessException(String)\n  type: Constructor\n  assemblies:\n  - System.Runtime\n  - mscorlib\n  - netstandard\n  namespace: System\n  summary: Initializes a new instance of the <xref href=\"System.FieldAccessException\"></xref> class with a specified error message.\n  remarks: \"This constructor initializes the <xref:System.Exception.Message%2A> property of the new instance by using the `message` parameter. The content of `message` is intended to be understood by humans. The caller of this constructor must ensure that this string has been localized for the current system culture.  \\n  \\n The following table shows the initial property values for an instance of <xref:System.FieldAccessException>.  \\n  \\n|Property|Value|  \\n|--------------|-----------|  \\n|<xref:System.Exception.InnerException%2A>|A null reference (`Nothing` in Visual Basic).|  \\n|<xref:System.Exception.Message%2A>|The localized error message string.|\"\n  syntax:\n    content: public FieldAccessException (string message);\n    parameters:\n    - id: message\n      type: System.String\n      description: The error message that explains the reason for the exception.\n  overload: System.FieldAccessException.#ctor*\n  exceptions: []\n  version:\n  - netcore-1.0\n  - netcore-1.1\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-1.3\n  - netstandard-1.4\n  - netstandard-1.5\n  - netstandard-1.6\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  monikers:\n  - netcore-1.0\n  - netcore-1.1\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-1.3\n  - netstandard-1.4\n  - netstandard-1.5\n  - netstandard-1.6\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System/FieldAccessException.xml\n  ms.technology:\n  - dotnet-standard\n  author: rpetrusha\n  ms.author: ronpet\n  manager: wpickett\n- uid: System.FieldAccessException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  commentId: M:System.FieldAccessException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'\n  parent: System.FieldAccessException\n  langs:\n  - csharp\n  name: FieldAccessException(SerializationInfo, StreamingContext)\n  nameWithType: FieldAccessException.FieldAccessException(SerializationInfo, StreamingContext)\n  fullName: FieldAccessException.FieldAccessException(SerializationInfo, StreamingContext)\n  type: Constructor\n  assemblies:\n  - mscorlib\n  - netstandard\n  - System.Runtime\n  namespace: System\n  summary: Initializes a new instance of the <xref href=\"System.FieldAccessException\"></xref> class with serialized data.\n  remarks: This constructor is called during deserialization to reconstitute the exception object that was transmitted over a stream.\n  syntax:\n    content: protected FieldAccessException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);\n    parameters:\n    - id: info\n      type: System.Runtime.Serialization.SerializationInfo\n      description: The object that holds the serialized object data.\n    - id: context\n      type: System.Runtime.Serialization.StreamingContext\n      description: The contextual information about the source or destination.\n  overload: System.FieldAccessException.#ctor*\n  exceptions: []\n  version:\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  monikers:\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System/FieldAccessException.xml\n  ms.technology:\n  - dotnet-standard\n  author: rpetrusha\n  ms.author: ronpet\n  manager: wpickett\n- uid: System.FieldAccessException.#ctor(System.String,System.Exception)\n  commentId: M:System.FieldAccessException.#ctor(System.String,System.Exception)\n  id: '#ctor(System.String,System.Exception)'\n  parent: System.FieldAccessException\n  langs:\n  - csharp\n  name: FieldAccessException(String, Exception)\n  nameWithType: FieldAccessException.FieldAccessException(String, Exception)\n  fullName: FieldAccessException.FieldAccessException(String, Exception)\n  type: Constructor\n  assemblies:\n  - System.Runtime\n  - mscorlib\n  - netstandard\n  namespace: System\n  summary: Initializes a new instance of the <xref href=\"System.FieldAccessException\"></xref> class with a specified error message and a reference to the inner exception that is the cause of this exception.\n  remarks: \"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property. The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or returns `null` if it does not supply the inner exception value to the constructor. The caller of this constructor must ensure that this string has been localized for the current system culture.  \\n  \\n The following table shows the initial property values for an instance of <xref:System.FieldAccessException>.  \\n  \\n|Property|Value|  \\n|--------------|-----------|  \\n|<xref:System.Exception.InnerException%2A>|The inner exception reference.|  \\n|<xref:System.Exception.Message%2A>|The localized error message string.|\"\n  syntax:\n    content: public FieldAccessException (string message, Exception inner);\n    parameters:\n    - id: message\n      type: System.String\n      description: The error message that explains the reason for the exception.\n    - id: inner\n      type: System.Exception\n      description: The exception that is the cause of the current exception. If the <code>inner</code> parameter is not `null`, the current exception is raised in a `catch` block that handles the inner exception.\n  overload: System.FieldAccessException.#ctor*\n  exceptions: []\n  version:\n  - netcore-1.0\n  - netcore-1.1\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-1.3\n  - netstandard-1.4\n  - netstandard-1.5\n  - netstandard-1.6\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  monikers:\n  - netcore-1.0\n  - netcore-1.1\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-1.3\n  - netstandard-1.4\n  - netstandard-1.5\n  - netstandard-1.6\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System/FieldAccessException.xml\n  ms.technology:\n  - dotnet-standard\n  author: rpetrusha\n  ms.author: ronpet\n  manager: wpickett\nreferences:\n- uid: System.MemberAccessException\n  parent: System\n  isExternal: false\n  name: MemberAccessException\n  nameWithType: MemberAccessException\n  fullName: System.MemberAccessException\n- uid: System.FieldAccessException.#ctor\n  parent: System.FieldAccessException\n  isExternal: false\n  name: FieldAccessException()\n  nameWithType: FieldAccessException.FieldAccessException()\n  fullName: FieldAccessException.FieldAccessException()\n- uid: System.FieldAccessException.#ctor(System.String)\n  parent: System.FieldAccessException\n  isExternal: false\n  name: FieldAccessException(String)\n  nameWithType: FieldAccessException.FieldAccessException(String)\n  fullName: FieldAccessException.FieldAccessException(String)\n- uid: System.String\n  parent: System\n  isExternal: false\n  name: String\n  nameWithType: String\n  fullName: System.String\n- uid: System.FieldAccessException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  parent: System.FieldAccessException\n  isExternal: false\n  name: FieldAccessException(SerializationInfo, StreamingContext)\n  nameWithType: FieldAccessException.FieldAccessException(SerializationInfo, StreamingContext)\n  fullName: FieldAccessException.FieldAccessException(SerializationInfo, StreamingContext)\n- uid: System.Runtime.Serialization.SerializationInfo\n  parent: System.Runtime.Serialization\n  isExternal: false\n  name: SerializationInfo\n  nameWithType: SerializationInfo\n  fullName: System.Runtime.Serialization.SerializationInfo\n- uid: System.Runtime.Serialization.StreamingContext\n  parent: System.Runtime.Serialization\n  isExternal: false\n  name: StreamingContext\n  nameWithType: StreamingContext\n  fullName: System.Runtime.Serialization.StreamingContext\n- uid: System.FieldAccessException.#ctor(System.String,System.Exception)\n  parent: System.FieldAccessException\n  isExternal: false\n  name: FieldAccessException(String, Exception)\n  nameWithType: FieldAccessException.FieldAccessException(String, Exception)\n  fullName: FieldAccessException.FieldAccessException(String, Exception)\n- uid: System.Exception\n  parent: System\n  isExternal: false\n  name: Exception\n  nameWithType: Exception\n  fullName: System.Exception\n- uid: System.FieldAccessException.#ctor*\n  parent: System.FieldAccessException\n  isExternal: false\n  name: FieldAccessException\n  nameWithType: FieldAccessException.FieldAccessException\n  fullName: FieldAccessException.FieldAccessException\n  monikers:\n  - netcore-1.0\n  - netcore-1.1\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-1.3\n  - netstandard-1.4\n  - netstandard-1.5\n  - netstandard-1.6\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System/FieldAccessException.xml\n- uid: System.Object.Equals(System.Object)\n  parent: System.Object\n  isExternal: false\n  name: Equals(Object)\n  nameWithType: Object.Equals(Object)\n  fullName: Object.Equals(Object)\n- uid: System.Object.Equals(System.Object,System.Object)\n  parent: System.Object\n  isExternal: false\n  name: Equals(Object, Object)\n  nameWithType: Object.Equals(Object, Object)\n  fullName: Object.Equals(Object, Object)\n- uid: System.Object.GetHashCode\n  parent: System.Object\n  isExternal: false\n  name: GetHashCode()\n  nameWithType: Object.GetHashCode()\n  fullName: Object.GetHashCode()\n- uid: System.Exception.GetType\n  parent: System.Exception\n  isExternal: false\n  name: GetType()\n  nameWithType: Exception.GetType()\n  fullName: Exception.GetType()\n- uid: System.Object.MemberwiseClone\n  parent: System.Object\n  isExternal: false\n  name: MemberwiseClone()\n  nameWithType: Object.MemberwiseClone()\n  fullName: Object.MemberwiseClone()\n- uid: System.Object.ReferenceEquals(System.Object,System.Object)\n  parent: System.Object\n  isExternal: false\n  name: ReferenceEquals(Object, Object)\n  nameWithType: Object.ReferenceEquals(Object, Object)\n  fullName: Object.ReferenceEquals(Object, Object)\n- uid: System.Exception.ToString\n  parent: System.Exception\n  isExternal: false\n  name: ToString()\n  nameWithType: Exception.ToString()\n  fullName: Exception.ToString()\n- uid: System.Exception.Data\n  parent: System.Exception\n  isExternal: false\n  name: Data\n  nameWithType: Exception.Data\n  fullName: Exception.Data\n- uid: System.Exception.GetBaseException\n  parent: System.Exception\n  isExternal: false\n  name: GetBaseException()\n  nameWithType: Exception.GetBaseException()\n  fullName: Exception.GetBaseException()\n- uid: System.Exception.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  parent: System.Exception\n  isExternal: false\n  name: GetObjectData(SerializationInfo, StreamingContext)\n  nameWithType: Exception.GetObjectData(SerializationInfo, StreamingContext)\n  fullName: Exception.GetObjectData(SerializationInfo, StreamingContext)\n- uid: System.Exception.HelpLink\n  parent: System.Exception\n  isExternal: false\n  name: HelpLink\n  nameWithType: Exception.HelpLink\n  fullName: Exception.HelpLink\n- uid: System.Exception.HResult\n  parent: System.Exception\n  isExternal: false\n  name: HResult\n  nameWithType: Exception.HResult\n  fullName: Exception.HResult\n- uid: System.Exception.InnerException\n  parent: System.Exception\n  isExternal: false\n  name: InnerException\n  nameWithType: Exception.InnerException\n  fullName: Exception.InnerException\n- uid: System.Exception.Message\n  parent: System.Exception\n  isExternal: false\n  name: Message\n  nameWithType: Exception.Message\n  fullName: Exception.Message\n- uid: System.Exception.SerializeObjectState\n  parent: System.Exception\n  isExternal: false\n  name: SerializeObjectState\n  nameWithType: Exception.SerializeObjectState\n  fullName: Exception.SerializeObjectState\n- uid: System.Exception.Source\n  parent: System.Exception\n  isExternal: false\n  name: Source\n  nameWithType: Exception.Source\n  fullName: Exception.Source\n- uid: System.Exception.StackTrace\n  parent: System.Exception\n  isExternal: false\n  name: StackTrace\n  nameWithType: Exception.StackTrace\n  fullName: Exception.StackTrace\n- uid: System.Exception.TargetSite\n  parent: System.Exception\n  isExternal: false\n  name: TargetSite\n  nameWithType: Exception.TargetSite\n  fullName: Exception.TargetSite\n"}