{"nodes":[{"content":"The exception thrown when the type of the incoming `SAFEARRAY` does not match the type specified in the managed signature.","nodes":[{"pos":[0,122],"content":"The exception thrown when the type of the incoming <ph id=\"ph1\">`SAFEARRAY`</ph> does not match the type specified in the managed signature.","source":"The exception thrown when the type of the incoming `SAFEARRAY` does not match the type specified in the managed signature."}],"pos":[987,1110],"yaml":true},{"content":"`SafeArrayTypeMismatchException` uses the HRESULT COR_E_SAFEARRAYTYPEMISMATCH which has the value 0x80131533.","nodes":[{"pos":[0,109],"content":"<ph id=\"ph1\">`SafeArrayTypeMismatchException`</ph> uses the HRESULT COR_E_SAFEARRAYTYPEMISMATCH which has the value 0x80131533.","source":"`SafeArrayTypeMismatchException` uses the HRESULT COR_E_SAFEARRAYTYPEMISMATCH which has the value 0x80131533."}],"pos":[1121,1233],"yaml":true,"extradata":"MT"},{"content":"Initializes a new instance of the `SafeArrayTypeMismatchException` class with default values.","nodes":[{"pos":[0,93],"content":"Initializes a new instance of the <ph id=\"ph1\">`SafeArrayTypeMismatchException`</ph> class with default values.","source":"Initializes a new instance of the `SafeArrayTypeMismatchException` class with default values."}],"pos":[3957,4051],"yaml":true},{"content":"`SafeArrayTypeMismatchException` inherits from <xref:System.SystemException>. This constructor sets the properties of the <xref:System.Exception> object as shown in the following table.  \n  \n|Property|Value|  \n|--------------|-----------|  \n|<xref:System.Exception.InnerException%2A>|`null`.|  \n|<xref:System.Exception.Message%2A>|A localized error message string.|","nodes":[{"pos":[0,185],"content":"`SafeArrayTypeMismatchException` inherits from <xref:System.SystemException>. This constructor sets the properties of the <xref:System.Exception> object as shown in the following table.","nodes":[{"content":"<ph id=\"ph1\">`SafeArrayTypeMismatchException`</ph> inherits from <ph id=\"ph2\">&lt;xref:System.SystemException&gt;</ph>.","pos":[0,77],"source":"`SafeArrayTypeMismatchException` inherits from <xref:System.SystemException>."},{"content":"This constructor sets the properties of the <ph id=\"ph1\">&lt;xref:System.Exception&gt;</ph> object as shown in the following table.","pos":[78,185],"source":" This constructor sets the properties of the <xref:System.Exception> object as shown in the following table."}]},{"pos":[192,200],"content":"Property","nodes":[{"content":"Property","pos":[0,8]}]},{"pos":[201,206],"content":"Value","nodes":[{"content":"Value","pos":[0,5]}]},{"pos":[242,283],"content":"<xref:System.Exception.InnerException%2A>","nodes":[]},{"pos":[284,291],"content":"<ph id=\"ph1\">`null`</ph>.","source":"`null`."},{"pos":[296,330],"content":"<xref:System.Exception.Message%2A>","nodes":[]},{"pos":[331,364],"content":"A localized error message string.","nodes":[{"content":"A localized error message string.","pos":[0,33]}]}],"pos":[4062,4435],"yaml":true,"extradata":"MT"},{"content":"Initializes a new instance of the `SafeArrayTypeMismatchException` class with the specified message.","nodes":[{"pos":[0,100],"content":"Initializes a new instance of the <ph id=\"ph1\">`SafeArrayTypeMismatchException`</ph> class with the specified message.","source":"Initializes a new instance of the `SafeArrayTypeMismatchException` class with the specified message."}],"pos":[6356,6457],"yaml":true},{"content":"`SafeArrayTypeMismatchException` inherits from <xref:System.SystemException>. This constructor sets the properties of the <xref:System.Exception> object as shown in the following table.  \n  \n|Property|Value|  \n|--------------|-----------|  \n|<xref:System.Exception.InnerException%2A>|`null`.|  \n|<xref:System.Exception.Message%2A>|`message`|","nodes":[{"pos":[0,185],"content":"`SafeArrayTypeMismatchException` inherits from <xref:System.SystemException>. This constructor sets the properties of the <xref:System.Exception> object as shown in the following table.","nodes":[{"content":"<ph id=\"ph1\">`SafeArrayTypeMismatchException`</ph> inherits from <ph id=\"ph2\">&lt;xref:System.SystemException&gt;</ph>.","pos":[0,77],"source":"`SafeArrayTypeMismatchException` inherits from <xref:System.SystemException>."},{"content":"This constructor sets the properties of the <ph id=\"ph1\">&lt;xref:System.Exception&gt;</ph> object as shown in the following table.","pos":[78,185],"source":" This constructor sets the properties of the <xref:System.Exception> object as shown in the following table."}]},{"pos":[192,200],"content":"Property","nodes":[{"content":"Property","pos":[0,8]}]},{"pos":[201,206],"content":"Value","nodes":[{"content":"Value","pos":[0,5]}]},{"pos":[242,283],"content":"<xref:System.Exception.InnerException%2A>","nodes":[]},{"pos":[284,291],"content":"<ph id=\"ph1\">`null`</ph>.","source":"`null`."},{"pos":[296,330],"content":"<xref:System.Exception.Message%2A>","nodes":[]}],"pos":[6468,6817],"yaml":true,"extradata":"MT"},{"content":"The message that indicates the reason for the exception.","nodes":[{"pos":[0,56],"content":"The message that indicates the reason for the exception.","nodes":[{"content":"The message that indicates the reason for the exception.","pos":[0,56]}]}],"pos":[6975,7032],"yaml":true},{"content":"Initializes a new instance of the `SafeArrayTypeMismatchException` class from serialization data.","nodes":[{"pos":[0,97],"content":"Initializes a new instance of the <ph id=\"ph1\">`SafeArrayTypeMismatchException`</ph> class from serialization data.","source":"Initializes a new instance of the `SafeArrayTypeMismatchException` class from serialization data."}],"pos":[9193,9291],"yaml":true},{"content":"This constructor is called during deserialization to reconstitute the exception object transmitted over a stream. For more information, see <xref:System.Runtime.Serialization>.  \n  \n `SafeArrayTypeMismatchException` inherits from <xref:System.SystemException>.","nodes":[{"pos":[0,176],"content":"This constructor is called during deserialization to reconstitute the exception object transmitted over a stream. For more information, see <xref:System.Runtime.Serialization>.","nodes":[{"content":"This constructor is called during deserialization to reconstitute the exception object transmitted over a stream. For more information, see <xref:System.Runtime.Serialization>.","pos":[0,176],"nodes":[{"content":"This constructor is called during deserialization to reconstitute the exception object transmitted over a stream.","pos":[0,113]},{"content":"For more information, see <ph id=\"ph1\">&lt;xref:System.Runtime.Serialization&gt;</ph>.","pos":[114,176],"source":" For more information, see <xref:System.Runtime.Serialization>."}]}]},{"pos":[183,260],"content":"<ph id=\"ph1\">`SafeArrayTypeMismatchException`</ph> inherits from <ph id=\"ph2\">&lt;xref:System.SystemException&gt;</ph>.","source":"`SafeArrayTypeMismatchException` inherits from <xref:System.SystemException>."}],"pos":[9302,9567],"yaml":true,"extradata":"MT"},{"content":"The object that holds the serialized object data.","nodes":[{"pos":[0,49],"content":"The object that holds the serialized object data.","nodes":[{"content":"The object that holds the serialized object data.","pos":[0,49]}]}],"pos":[9850,9900],"yaml":true},{"content":"The contextual information about the source or destination.","nodes":[{"pos":[0,59],"content":"The contextual information about the source or destination.","nodes":[{"content":"The contextual information about the source or destination.","pos":[0,59]}]}],"pos":[9995,10055],"yaml":true},{"content":"<code>info</code> is `null`.","nodes":[{"pos":[0,28],"content":"<ph id=\"ph1\">&lt;code&gt;info&lt;/code&gt;</ph> is <ph id=\"ph2\">`null`</ph>.","source":"<code>info</code> is `null`."}],"pos":[10252,10281],"yaml":true},{"content":"Initializes a new instance of the <xref href=\"System.Runtime.InteropServices.SafeArrayTypeMismatchException\"></xref> class with a specified error message and a reference to the inner exception that is the cause of this exception.","nodes":[{"pos":[0,229],"content":"Initializes a new instance of the <ph id=\"ph1\">&lt;xref href=\"System.Runtime.InteropServices.SafeArrayTypeMismatchException\"&gt;&lt;/xref&gt;</ph> class with a specified error message and a reference to the inner exception that is the cause of this exception.","source":"Initializes a new instance of the <xref href=\"System.Runtime.InteropServices.SafeArrayTypeMismatchException\"></xref> class with a specified error message and a reference to the inner exception that is the cause of this exception."}],"pos":[11800,12030],"yaml":true},{"content":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property. The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or `null` if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor.  \n  \n The following table shows the initial property values for an instance of <xref:System.Runtime.InteropServices.SafeArrayTypeMismatchException>.  \n  \n|Property|Value|  \n|--------------|-----------|  \n|<xref:System.Exception.InnerException%2A>|The inner exception reference.|  \n|<xref:System.Exception.Message%2A>|The error message string.|","nodes":[{"pos":[0,427],"content":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property. The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or `null` if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor.","nodes":[{"content":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <ph id=\"ph1\">&lt;xref:System.Exception.InnerException%2A&gt;</ph> property.","pos":[0,182],"source":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property."},{"content":"The <ph id=\"ph1\">&lt;xref:System.Exception.InnerException%2A&gt;</ph> property returns the same value that is passed into the constructor, or <ph id=\"ph2\">`null`</ph> if the <ph id=\"ph3\">&lt;xref:System.Exception.InnerException%2A&gt;</ph> property does not supply the inner exception value to the constructor.","pos":[183,427],"source":" The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or `null` if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor."}]},{"pos":[434,576],"content":"The following table shows the initial property values for an instance of <xref:System.Runtime.InteropServices.SafeArrayTypeMismatchException>.","nodes":[{"content":"The following table shows the initial property values for an instance of <ph id=\"ph1\">&lt;xref:System.Runtime.InteropServices.SafeArrayTypeMismatchException&gt;</ph>.","pos":[0,142],"source":"The following table shows the initial property values for an instance of <xref:System.Runtime.InteropServices.SafeArrayTypeMismatchException>."}]},{"pos":[583,591],"content":"Property","nodes":[{"content":"Property","pos":[0,8]}]},{"pos":[592,597],"content":"Value","nodes":[{"content":"Value","pos":[0,5]}]},{"pos":[633,674],"content":"<xref:System.Exception.InnerException%2A>","nodes":[]},{"pos":[675,705],"content":"The inner exception reference.","nodes":[{"content":"The inner exception reference.","pos":[0,30]}]},{"pos":[710,744],"content":"<xref:System.Exception.Message%2A>","nodes":[]},{"pos":[745,770],"content":"The error message string.","nodes":[{"content":"The error message string.","pos":[0,25]}]}],"pos":[12041,12822],"yaml":true,"extradata":"MT"},{"content":"The error message that explains the reason for the exception.","nodes":[{"pos":[0,61],"content":"The error message that explains the reason for the exception.","nodes":[{"content":"The error message that explains the reason for the exception.","pos":[0,61]}]}],"pos":[12997,13059],"yaml":true},{"content":"The exception that is the cause of the current exception. If the <code>inner</code> parameter is not `null`, the current exception is raised in a `catch` block that handles the inner exception.","nodes":[{"pos":[0,193],"content":"The exception that is the cause of the current exception. If the <code>inner</code> parameter is not `null`, the current exception is raised in a `catch` block that handles the inner exception.","nodes":[{"content":"The exception that is the cause of the current exception.","pos":[0,57]},{"content":"If the <bpt id=\"p1\">&lt;code&gt;</bpt><ph id=\"ph1\">inner</ph><ept id=\"p1\">&lt;/code&gt;</ept> parameter is not <ph id=\"ph2\">`null`</ph>, the current exception is raised in a <ph id=\"ph3\">`catch`</ph> block that handles the inner exception.","pos":[58,193],"source":" If the <code>inner</code> parameter is not `null`, the current exception is raised in a `catch` block that handles the inner exception."}]}],"pos":[13123,13317],"yaml":true}],"content":"### YamlMime:ManagedReference\nitems:\n- uid: System.Runtime.InteropServices.SafeArrayTypeMismatchException\n  commentId: T:System.Runtime.InteropServices.SafeArrayTypeMismatchException\n  id: SafeArrayTypeMismatchException\n  children:\n  - System.Runtime.InteropServices.SafeArrayTypeMismatchException.#ctor\n  - System.Runtime.InteropServices.SafeArrayTypeMismatchException.#ctor(System.String)\n  - System.Runtime.InteropServices.SafeArrayTypeMismatchException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  - System.Runtime.InteropServices.SafeArrayTypeMismatchException.#ctor(System.String,System.Exception)\n  langs:\n  - csharp\n  name: SafeArrayTypeMismatchException\n  nameWithType: SafeArrayTypeMismatchException\n  fullName: System.Runtime.InteropServices.SafeArrayTypeMismatchException\n  type: Class\n  assemblies:\n  - System.Runtime.InteropServices\n  - mscorlib\n  - netstandard\n  namespace: System.Runtime.InteropServices\n  summary: The exception thrown when the type of the incoming `SAFEARRAY` does not match the type specified in the managed signature.\n  remarks: '`SafeArrayTypeMismatchException` uses the HRESULT COR_E_SAFEARRAYTYPEMISMATCH which has the value 0x80131533.'\n  syntax:\n    content: >-\n      [System.Runtime.InteropServices.ComVisible(true)]\n\n      public class SafeArrayTypeMismatchException : SystemException\n  inheritance:\n  - System.Object\n  - System.Exception\n  implements: []\n  inheritedMembers:\n  - System.Exception.Data\n  - System.Exception.GetBaseException\n  - System.Exception.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  - System.Exception.GetType\n  - System.Exception.HelpLink\n  - System.Exception.HResult\n  - System.Exception.InnerException\n  - System.Exception.Message\n  - System.Exception.SerializeObjectState\n  - System.Exception.Source\n  - System.Exception.StackTrace\n  - System.Exception.TargetSite\n  - System.Exception.ToString\n  - System.Object.Equals(System.Object)\n  - System.Object.Equals(System.Object,System.Object)\n  - System.Object.GetHashCode\n  - System.Object.MemberwiseClone\n  - System.Object.ReferenceEquals(System.Object,System.Object)\n  attributes:\n  - type: System.Runtime.InteropServices.ComVisibleAttribute\n  version:\n  - netcore-1.0\n  - netcore-1.1\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-1.1\n  - netstandard-1.2\n  - netstandard-1.3\n  - netstandard-1.4\n  - netstandard-1.5\n  - netstandard-1.6\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  monikers:\n  - netcore-1.0\n  - netcore-1.1\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-1.1\n  - netstandard-1.2\n  - netstandard-1.3\n  - netstandard-1.4\n  - netstandard-1.5\n  - netstandard-1.6\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Runtime.InteropServices/SafeArrayTypeMismatchException.xml\n  ms.technology:\n  - dotnet-standard\n  author: rpetrusha\n  ms.author: ronpet\n  manager: wpickett\n- uid: System.Runtime.InteropServices.SafeArrayTypeMismatchException.#ctor\n  commentId: M:System.Runtime.InteropServices.SafeArrayTypeMismatchException.#ctor\n  id: '#ctor'\n  parent: System.Runtime.InteropServices.SafeArrayTypeMismatchException\n  langs:\n  - csharp\n  name: SafeArrayTypeMismatchException()\n  nameWithType: SafeArrayTypeMismatchException.SafeArrayTypeMismatchException()\n  fullName: SafeArrayTypeMismatchException.SafeArrayTypeMismatchException()\n  type: Constructor\n  assemblies:\n  - System.Runtime.InteropServices\n  - mscorlib\n  - netstandard\n  namespace: System.Runtime.InteropServices\n  summary: Initializes a new instance of the `SafeArrayTypeMismatchException` class with default values.\n  remarks: \"`SafeArrayTypeMismatchException` inherits from <xref:System.SystemException>. This constructor sets the properties of the <xref:System.Exception> object as shown in the following table.  \\n  \\n|Property|Value|  \\n|--------------|-----------|  \\n|<xref:System.Exception.InnerException%2A>|`null`.|  \\n|<xref:System.Exception.Message%2A>|A localized error message string.|\"\n  syntax:\n    content: public SafeArrayTypeMismatchException ();\n    parameters: []\n  overload: System.Runtime.InteropServices.SafeArrayTypeMismatchException.#ctor*\n  exceptions: []\n  version:\n  - netcore-1.0\n  - netcore-1.1\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-1.1\n  - netstandard-1.2\n  - netstandard-1.3\n  - netstandard-1.4\n  - netstandard-1.5\n  - netstandard-1.6\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  monikers:\n  - netcore-1.0\n  - netcore-1.1\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-1.1\n  - netstandard-1.2\n  - netstandard-1.3\n  - netstandard-1.4\n  - netstandard-1.5\n  - netstandard-1.6\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Runtime.InteropServices/SafeArrayTypeMismatchException.xml\n  ms.technology:\n  - dotnet-standard\n  author: rpetrusha\n  ms.author: ronpet\n  manager: wpickett\n- uid: System.Runtime.InteropServices.SafeArrayTypeMismatchException.#ctor(System.String)\n  commentId: M:System.Runtime.InteropServices.SafeArrayTypeMismatchException.#ctor(System.String)\n  id: '#ctor(System.String)'\n  parent: System.Runtime.InteropServices.SafeArrayTypeMismatchException\n  langs:\n  - csharp\n  name: SafeArrayTypeMismatchException(String)\n  nameWithType: SafeArrayTypeMismatchException.SafeArrayTypeMismatchException(String)\n  fullName: SafeArrayTypeMismatchException.SafeArrayTypeMismatchException(String)\n  type: Constructor\n  assemblies:\n  - System.Runtime.InteropServices\n  - mscorlib\n  - netstandard\n  namespace: System.Runtime.InteropServices\n  summary: Initializes a new instance of the `SafeArrayTypeMismatchException` class with the specified message.\n  remarks: \"`SafeArrayTypeMismatchException` inherits from <xref:System.SystemException>. This constructor sets the properties of the <xref:System.Exception> object as shown in the following table.  \\n  \\n|Property|Value|  \\n|--------------|-----------|  \\n|<xref:System.Exception.InnerException%2A>|`null`.|  \\n|<xref:System.Exception.Message%2A>|`message`|\"\n  syntax:\n    content: public SafeArrayTypeMismatchException (string message);\n    parameters:\n    - id: message\n      type: System.String\n      description: The message that indicates the reason for the exception.\n  overload: System.Runtime.InteropServices.SafeArrayTypeMismatchException.#ctor*\n  exceptions: []\n  version:\n  - netcore-1.0\n  - netcore-1.1\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-1.1\n  - netstandard-1.2\n  - netstandard-1.3\n  - netstandard-1.4\n  - netstandard-1.5\n  - netstandard-1.6\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  monikers:\n  - netcore-1.0\n  - netcore-1.1\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-1.1\n  - netstandard-1.2\n  - netstandard-1.3\n  - netstandard-1.4\n  - netstandard-1.5\n  - netstandard-1.6\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Runtime.InteropServices/SafeArrayTypeMismatchException.xml\n  ms.technology:\n  - dotnet-standard\n  author: rpetrusha\n  ms.author: ronpet\n  manager: wpickett\n- uid: System.Runtime.InteropServices.SafeArrayTypeMismatchException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  commentId: M:System.Runtime.InteropServices.SafeArrayTypeMismatchException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'\n  parent: System.Runtime.InteropServices.SafeArrayTypeMismatchException\n  langs:\n  - csharp\n  name: SafeArrayTypeMismatchException(SerializationInfo, StreamingContext)\n  nameWithType: SafeArrayTypeMismatchException.SafeArrayTypeMismatchException(SerializationInfo, StreamingContext)\n  fullName: SafeArrayTypeMismatchException.SafeArrayTypeMismatchException(SerializationInfo, StreamingContext)\n  type: Constructor\n  assemblies:\n  - mscorlib\n  - netstandard\n  - System.Runtime.InteropServices\n  namespace: System.Runtime.InteropServices\n  summary: Initializes a new instance of the `SafeArrayTypeMismatchException` class from serialization data.\n  remarks: \"This constructor is called during deserialization to reconstitute the exception object transmitted over a stream. For more information, see <xref:System.Runtime.Serialization>.  \\n  \\n `SafeArrayTypeMismatchException` inherits from <xref:System.SystemException>.\"\n  syntax:\n    content: protected SafeArrayTypeMismatchException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);\n    parameters:\n    - id: info\n      type: System.Runtime.Serialization.SerializationInfo\n      description: The object that holds the serialized object data.\n    - id: context\n      type: System.Runtime.Serialization.StreamingContext\n      description: The contextual information about the source or destination.\n  overload: System.Runtime.InteropServices.SafeArrayTypeMismatchException.#ctor*\n  exceptions:\n  - type: System.ArgumentNullException\n    commentId: T:System.ArgumentNullException\n    description: <code>info</code> is `null`.\n  version:\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  monikers:\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Runtime.InteropServices/SafeArrayTypeMismatchException.xml\n  ms.technology:\n  - dotnet-standard\n  author: rpetrusha\n  ms.author: ronpet\n  manager: wpickett\n- uid: System.Runtime.InteropServices.SafeArrayTypeMismatchException.#ctor(System.String,System.Exception)\n  commentId: M:System.Runtime.InteropServices.SafeArrayTypeMismatchException.#ctor(System.String,System.Exception)\n  id: '#ctor(System.String,System.Exception)'\n  parent: System.Runtime.InteropServices.SafeArrayTypeMismatchException\n  langs:\n  - csharp\n  name: SafeArrayTypeMismatchException(String, Exception)\n  nameWithType: SafeArrayTypeMismatchException.SafeArrayTypeMismatchException(String, Exception)\n  fullName: SafeArrayTypeMismatchException.SafeArrayTypeMismatchException(String, Exception)\n  type: Constructor\n  assemblies:\n  - System.Runtime.InteropServices\n  - mscorlib\n  - netstandard\n  namespace: System.Runtime.InteropServices\n  summary: Initializes a new instance of the <xref href=\"System.Runtime.InteropServices.SafeArrayTypeMismatchException\"></xref> class with a specified error message and a reference to the inner exception that is the cause of this exception.\n  remarks: \"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property. The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or `null` if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor.  \\n  \\n The following table shows the initial property values for an instance of <xref:System.Runtime.InteropServices.SafeArrayTypeMismatchException>.  \\n  \\n|Property|Value|  \\n|--------------|-----------|  \\n|<xref:System.Exception.InnerException%2A>|The inner exception reference.|  \\n|<xref:System.Exception.Message%2A>|The error message string.|\"\n  syntax:\n    content: public SafeArrayTypeMismatchException (string message, Exception inner);\n    parameters:\n    - id: message\n      type: System.String\n      description: The error message that explains the reason for the exception.\n    - id: inner\n      type: System.Exception\n      description: The exception that is the cause of the current exception. If the <code>inner</code> parameter is not `null`, the current exception is raised in a `catch` block that handles the inner exception.\n  overload: System.Runtime.InteropServices.SafeArrayTypeMismatchException.#ctor*\n  exceptions: []\n  version:\n  - netcore-1.0\n  - netcore-1.1\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-1.1\n  - netstandard-1.2\n  - netstandard-1.3\n  - netstandard-1.4\n  - netstandard-1.5\n  - netstandard-1.6\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  monikers:\n  - netcore-1.0\n  - netcore-1.1\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-1.1\n  - netstandard-1.2\n  - netstandard-1.3\n  - netstandard-1.4\n  - netstandard-1.5\n  - netstandard-1.6\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Runtime.InteropServices/SafeArrayTypeMismatchException.xml\n  ms.technology:\n  - dotnet-standard\n  author: rpetrusha\n  ms.author: ronpet\n  manager: wpickett\nreferences:\n- uid: System.Exception\n  parent: System\n  isExternal: false\n  name: Exception\n  nameWithType: Exception\n  fullName: System.Exception\n- uid: System.ArgumentNullException\n  parent: System\n  isExternal: false\n  name: ArgumentNullException\n  nameWithType: ArgumentNullException\n  fullName: System.ArgumentNullException\n- uid: System.Runtime.InteropServices.SafeArrayTypeMismatchException.#ctor\n  parent: System.Runtime.InteropServices.SafeArrayTypeMismatchException\n  isExternal: false\n  name: SafeArrayTypeMismatchException()\n  nameWithType: SafeArrayTypeMismatchException.SafeArrayTypeMismatchException()\n  fullName: SafeArrayTypeMismatchException.SafeArrayTypeMismatchException()\n- uid: System.Runtime.InteropServices.SafeArrayTypeMismatchException.#ctor(System.String)\n  parent: System.Runtime.InteropServices.SafeArrayTypeMismatchException\n  isExternal: false\n  name: SafeArrayTypeMismatchException(String)\n  nameWithType: SafeArrayTypeMismatchException.SafeArrayTypeMismatchException(String)\n  fullName: SafeArrayTypeMismatchException.SafeArrayTypeMismatchException(String)\n- uid: System.String\n  parent: System\n  isExternal: false\n  name: String\n  nameWithType: String\n  fullName: System.String\n- uid: System.Runtime.InteropServices.SafeArrayTypeMismatchException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  parent: System.Runtime.InteropServices.SafeArrayTypeMismatchException\n  isExternal: false\n  name: SafeArrayTypeMismatchException(SerializationInfo, StreamingContext)\n  nameWithType: SafeArrayTypeMismatchException.SafeArrayTypeMismatchException(SerializationInfo, StreamingContext)\n  fullName: SafeArrayTypeMismatchException.SafeArrayTypeMismatchException(SerializationInfo, StreamingContext)\n- uid: System.Runtime.Serialization.SerializationInfo\n  parent: System.Runtime.Serialization\n  isExternal: false\n  name: SerializationInfo\n  nameWithType: SerializationInfo\n  fullName: System.Runtime.Serialization.SerializationInfo\n- uid: System.Runtime.Serialization.StreamingContext\n  parent: System.Runtime.Serialization\n  isExternal: false\n  name: StreamingContext\n  nameWithType: StreamingContext\n  fullName: System.Runtime.Serialization.StreamingContext\n- uid: System.Runtime.InteropServices.SafeArrayTypeMismatchException.#ctor(System.String,System.Exception)\n  parent: System.Runtime.InteropServices.SafeArrayTypeMismatchException\n  isExternal: false\n  name: SafeArrayTypeMismatchException(String, Exception)\n  nameWithType: SafeArrayTypeMismatchException.SafeArrayTypeMismatchException(String, Exception)\n  fullName: SafeArrayTypeMismatchException.SafeArrayTypeMismatchException(String, Exception)\n- uid: System.Runtime.InteropServices.SafeArrayTypeMismatchException.#ctor*\n  parent: System.Runtime.InteropServices.SafeArrayTypeMismatchException\n  isExternal: false\n  name: SafeArrayTypeMismatchException\n  nameWithType: SafeArrayTypeMismatchException.SafeArrayTypeMismatchException\n  fullName: SafeArrayTypeMismatchException.SafeArrayTypeMismatchException\n  monikers:\n  - netcore-1.0\n  - netcore-1.1\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-1.1\n  - netstandard-1.2\n  - netstandard-1.3\n  - netstandard-1.4\n  - netstandard-1.5\n  - netstandard-1.6\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Runtime.InteropServices/SafeArrayTypeMismatchException.xml\n- uid: System.Object.Equals(System.Object)\n  parent: System.Object\n  isExternal: false\n  name: Equals(Object)\n  nameWithType: Object.Equals(Object)\n  fullName: Object.Equals(Object)\n- uid: System.Object.Equals(System.Object,System.Object)\n  parent: System.Object\n  isExternal: false\n  name: Equals(Object, Object)\n  nameWithType: Object.Equals(Object, Object)\n  fullName: Object.Equals(Object, Object)\n- uid: System.Object.GetHashCode\n  parent: System.Object\n  isExternal: false\n  name: GetHashCode()\n  nameWithType: Object.GetHashCode()\n  fullName: Object.GetHashCode()\n- uid: System.Exception.GetType\n  parent: System.Exception\n  isExternal: false\n  name: GetType()\n  nameWithType: Exception.GetType()\n  fullName: Exception.GetType()\n- uid: System.Object.MemberwiseClone\n  parent: System.Object\n  isExternal: false\n  name: MemberwiseClone()\n  nameWithType: Object.MemberwiseClone()\n  fullName: Object.MemberwiseClone()\n- uid: System.Object.ReferenceEquals(System.Object,System.Object)\n  parent: System.Object\n  isExternal: false\n  name: ReferenceEquals(Object, Object)\n  nameWithType: Object.ReferenceEquals(Object, Object)\n  fullName: Object.ReferenceEquals(Object, Object)\n- uid: System.Exception.ToString\n  parent: System.Exception\n  isExternal: false\n  name: ToString()\n  nameWithType: Exception.ToString()\n  fullName: Exception.ToString()\n- uid: System.Exception.Data\n  parent: System.Exception\n  isExternal: false\n  name: Data\n  nameWithType: Exception.Data\n  fullName: Exception.Data\n- uid: System.Exception.GetBaseException\n  parent: System.Exception\n  isExternal: false\n  name: GetBaseException()\n  nameWithType: Exception.GetBaseException()\n  fullName: Exception.GetBaseException()\n- uid: System.Exception.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  parent: System.Exception\n  isExternal: false\n  name: GetObjectData(SerializationInfo, StreamingContext)\n  nameWithType: Exception.GetObjectData(SerializationInfo, StreamingContext)\n  fullName: Exception.GetObjectData(SerializationInfo, StreamingContext)\n- uid: System.Exception.HelpLink\n  parent: System.Exception\n  isExternal: false\n  name: HelpLink\n  nameWithType: Exception.HelpLink\n  fullName: Exception.HelpLink\n- uid: System.Exception.HResult\n  parent: System.Exception\n  isExternal: false\n  name: HResult\n  nameWithType: Exception.HResult\n  fullName: Exception.HResult\n- uid: System.Exception.InnerException\n  parent: System.Exception\n  isExternal: false\n  name: InnerException\n  nameWithType: Exception.InnerException\n  fullName: Exception.InnerException\n- uid: System.Exception.Message\n  parent: System.Exception\n  isExternal: false\n  name: Message\n  nameWithType: Exception.Message\n  fullName: Exception.Message\n- uid: System.Exception.SerializeObjectState\n  parent: System.Exception\n  isExternal: false\n  name: SerializeObjectState\n  nameWithType: Exception.SerializeObjectState\n  fullName: Exception.SerializeObjectState\n- uid: System.Exception.Source\n  parent: System.Exception\n  isExternal: false\n  name: Source\n  nameWithType: Exception.Source\n  fullName: Exception.Source\n- uid: System.Exception.StackTrace\n  parent: System.Exception\n  isExternal: false\n  name: StackTrace\n  nameWithType: Exception.StackTrace\n  fullName: Exception.StackTrace\n- uid: System.Exception.TargetSite\n  parent: System.Exception\n  isExternal: false\n  name: TargetSite\n  nameWithType: Exception.TargetSite\n  fullName: Exception.TargetSite\n"}