{"nodes":[{"content":"The exception that is thrown when there is an attempt to dereference a null object reference.","nodes":[{"pos":[0,93],"content":"The exception that is thrown when there is an attempt to dereference a null object reference.","nodes":[{"content":"The exception that is thrown when there is an attempt to dereference a null object reference.","pos":[0,93]}]}],"pos":[699,793],"yaml":true},{"content":"A <xref:System.NullReferenceException> exception is thrown when you try to access a member on a type whose value is `null`. A <xref:System.NullReferenceException> exception typically reflects developer error and is thrown in the following scenarios:  \n  \n-   You've forgotten to instantiate a reference type. In the following example, `names` is declared but never instantiated:  \n  \n     [!code-csharp[System.NullReferenceException.Class#1](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.nullreferenceexception.class/cs/example1.cs#1)]\n     [!code-vb[System.NullReferenceException.Class#1](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.nullreferenceexception.class/vb/example1.vb#1)]  \n  \n     Some compilers issue a warning when they compile this code. Others issue an error, and the compilation fails. To address this problem, instantiate the object so that its value is no longer `null`. The following example does this by calling a type's class constructor.  \n  \n     [!code-csharp[System.NullReferenceException.Class#2](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.nullreferenceexception.class/cs/example1a.cs#2)]\n     [!code-vb[System.NullReferenceException.Class#2](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.nullreferenceexception.class/vb/example1a.vb#2)]  \n  \n-   You've forgotten to dimension an array before initializing it. In the following example, `values` is declared to be an integer array, but the number of elements that it contains is never specified. The attempt to initialize its values therefore thrown a  <xref:System.NullReferenceException> exception.  \n  \n     [!code-csharp[System.NullReferenceException.Class#10](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.nullreferenceexception.class/cs/Array3.cs#10)]\n     [!code-vb[System.NullReferenceException.Class#10](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.nullreferenceexception.class/vb/Array3.vb#10)]  \n  \n     You can eliminate the exception by declaring the number of elements in the array before initializing it, as the following example does.  \n  \n     [!code-csharp[System.NullReferenceException.Class#11](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.nullreferenceexception.class/cs/Array4.cs#11)]\n     [!code-vb[System.NullReferenceException.Class#11](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.nullreferenceexception.class/vb/Array4.vb#11)]  \n  \n     For more information on declaring and initializing arrays, see [Arrays](http://msdn.microsoft.com/library/bb79bdde-e570-4c30-adb0-1dd5759ae041) and [Arrays](http://msdn.microsoft.com/library/dbf29737-b589-4443-bee6-a27588d9c67e).  \n  \n-   You get a **null** return value from a method, and then call a method on the returned type. This sometimes is the result of a documentation error; the documentation fails to note that a method call can return `null`. In other cases, your code erroneously assumes that the method will always return a non-**null** value.  \n  \n     The code in the following example assumes that the <xref:System.Array.Find%2A?displayProperty=fullName> method always returns `Person` object whose `FirstName` field matches a search string. Because there is no match, the runtime throws a <xref:System.NullReferenceException> exception.  \n  \n     [!code-csharp[System.NullReferenceException.Class#4](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.nullreferenceexception.class/cs/nullreturn2.cs#4)]\n     [!code-vb[System.NullReferenceException.Class#4](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.nullreferenceexception.class/vb/nullreturn2.vb#4)]  \n  \n     To address this problem, test the method's return value to ensure that it is not `null` before calling any of its members, as the following example does.  \n  \n     [!code-csharp[System.NullReferenceException.Class#5](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.nullreferenceexception.class/cs/nullreturn2a.cs#5)]\n     [!code-vb[System.NullReferenceException.Class#5](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.nullreferenceexception.class/vb/nullreturn2a.vb#5)]  \n  \n-   You're using an expression (for example, you're chaining a list of methods or properties together) to retrieve a value and, although you're checking whether the value is `null`, the runtime still throws a <xref:System.NullReferenceException> exception. This occurs because one of the intermediate values in the expression returns `null`. As a result, your rest for `null` is never evaluated.  \n  \n     The following example defines a `Pages` object that  caches information about web pages, which are presented by `Page` objects. The `Example.Main` method checks whether the current web page has a non-null title and, if it does, displays the title. Despite this check, however, the method throws a <xref:System.NullReferenceException> exception.  \n  \n     [!code-csharp[System.NullReferenceException.Class#6](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.nullreferenceexception.class/cs/Chain1.cs#6)]\n     [!code-vb[System.NullReferenceException.Class#6](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.nullreferenceexception.class/vb/Chain1.vb#6)]  \n  \n     The exception is thrown because `pages.CurrentPage` returns `null` if no page information is  stored in the cache. This exception can be corrected by testing the value of the `CurrentPage` property before retrieving the current `Page` object's `Title` property, as the following example does:  \n  \n     [!code-csharp[System.NullReferenceException.Class#7](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.nullreferenceexception.class/cs/Chain2.cs#7)]\n     [!code-vb[System.NullReferenceException.Class#7](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.nullreferenceexception.class/vb/Chain2.vb#7)]  \n  \n-   You're enumerating the elements of an array that contains reference types, and your attempt to process one of the elements throws a <xref:System.NullReferenceException> exception.  \n  \n     The following example defines a string array. A `for` statement enumerates the elements in the array and calls each string's <xref:System.String.Trim%2A> method before displaying the string.  \n  \n     [!code-csharp[System.NullReferenceException.Class#8](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.nullreferenceexception.class/cs/Array1.cs#8)]\n     [!code-vb[System.NullReferenceException.Class#8](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.nullreferenceexception.class/vb/Array1.vb#8)]  \n  \n     This exception occurs if you assume that each element of the array must contain a non-null value, and the value of the array element is in fact `null`. The exception can be eliminated by testing whether the element is `null` before performing any operation on that element, as the following example shows.  \n  \n     [!code-csharp[System.NullReferenceException.Class#9](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.nullreferenceexception.class/cs/Array2.cs#9)]\n     [!code-vb[System.NullReferenceException.Class#9](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.nullreferenceexception.class/vb/Array2.vb#9)]  \n  \n-   A <xref:System.NullReferenceException> exception is thrown by a method that is passed `null`. Some methods validate the arguments that are passed to them. If they do and one of the arguments is `null`, the method throws an <xref:System.ArgumentNullException?displayProperty=fullName> exception. Otherwise, it throws a <xref:System.NullReferenceException> exception. The following example illustrates this scenario.  \n  \n     [!code-csharp[System.NullReferenceException.Class#3](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.nullreferenceexception.class/cs/example2.cs#3)]\n     [!code-vb[System.NullReferenceException.Class#3](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.nullreferenceexception.class/vb/example2.vb#3)]  \n  \n     To address this issue, make sure that the argument passed to the method is not `null`, or handle the thrown exception in a `try…catch…finally` block. For more information, see [Exceptions](http://msdn.microsoft.com/library/f99a1d29-a2a8-47af-9707-9909f9010735).  \n  \n The following Microsoft intermediate language (MSIL) instructions throw <xref:System.NullReferenceException>: `callvirt`, `cpblk`, `cpobj`, `initblk`, `ldelem.<type>`, `ldelema`, `ldfld`, `ldflda`, `ldind.<type>`, `ldlen`, `stelem.<type>`, `stfld`, `stind.<type>`, `throw`, and `unbox`.  \n  \n <xref:System.NullReferenceException> uses the HRESULT COR_E_NULLREFERENCE, which has the value 0x80004003.  \n  \n For a list of initial property values for an instance of <xref:System.NullReferenceException>, see the <xref:System.NullReferenceException.%23ctor%2A> constructors.  \n  \n **Handling NullReferenceException in release code**  \n  \n It's usually better to avoid a NullReferenceException than to handle it after it occurs. Handling an exception can make your code harder to maintain and understand, and can sometimes introduce other bugs. A NullReferenceException is often a non-recoverable error. In these cases, letting the exception stop the app might be the best alternative.  \n  \n However, there are many situations where handling the error can be useful:  \n  \n-   Your app can ignore objects that are null. For example, if your app retrieves and processes records in a database, you might be able to ignore some number of bad records that result in null objects. Recording the bad data in a log file or in the application UI might be all you have to do.  \n  \n-   You can recover from the exception. For example, a call to a web service that returns a reference type might return null if the connection is lost or the connection times out. You can attempt to reestablish the connection and try the call again.  \n  \n-   You can restore the state of your app to a valid state. For example, you might be performing a multi-step task that requires you to save information to a data store before you call a method that throws a NullReferenceException. If the uninitialized object would corrupt the data record, you can remove the previous data before you close the app.  \n  \n-   You want to report the exception. For example, if the error was caused by a mistake from the user of your app, you can generate a message to help him supply the correct information. You can also log information about the error to help you fix the problem. Some frameworks, like ASP.NET, have a high-level exception handler that captures all errors to that the app never crashes; in that case, logging the exception might be the only way you can know that it occurs.","nodes":[{"pos":[0,249],"content":"A <xref:System.NullReferenceException> exception is thrown when you try to access a member on a type whose value is `null`. A <xref:System.NullReferenceException> exception typically reflects developer error and is thrown in the following scenarios:","nodes":[{"content":"A <ph id=\"ph1\">&lt;xref:System.NullReferenceException&gt;</ph> exception is thrown when you try to access a member on a type whose value is <ph id=\"ph2\">`null`</ph>.","pos":[0,123],"source":"A <xref:System.NullReferenceException> exception is thrown when you try to access a member on a type whose value is `null`."},{"content":"A <ph id=\"ph1\">&lt;xref:System.NullReferenceException&gt;</ph> exception typically reflects developer error and is thrown in the following scenarios:","pos":[124,249],"source":" A <xref:System.NullReferenceException> exception typically reflects developer error and is thrown in the following scenarios:"}]},{"pos":[259,378],"content":"You've forgotten to instantiate a reference type. In the following example, `names` is declared but never instantiated:","nodes":[{"content":"You've forgotten to instantiate a reference type.","pos":[0,49]},{"content":"In the following example, <ph id=\"ph1\">`names`</ph> is declared but never instantiated:","pos":[50,119],"source":" In the following example, `names` is declared but never instantiated:"}]},{"pos":[389,708],"content":"<bpt id=\"p1\">[!code-csharp</bpt><bpt id=\"p2\">[</bpt>System.NullReferenceException.Class#1<ept id=\"p2\">](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.nullreferenceexception.class/cs/example1.cs#1)</ept><ept id=\"p1\">]</ept>  <bpt id=\"p3\">[!code-vb</bpt><bpt id=\"p4\">[</bpt>System.NullReferenceException.Class#1<ept id=\"p4\">](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.nullreferenceexception.class/vb/example1.vb#1)</ept><ept id=\"p3\">]</ept>","leadings":["","    "],"source":"[!code-csharp[System.NullReferenceException.Class#1](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.nullreferenceexception.class/cs/example1.cs#1)]\n [!code-vb[System.NullReferenceException.Class#1](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.nullreferenceexception.class/vb/example1.vb#1)]"},{"pos":[719,986],"content":"Some compilers issue a warning when they compile this code. Others issue an error, and the compilation fails. To address this problem, instantiate the object so that its value is no longer `null`. The following example does this by calling a type's class constructor.","nodes":[{"content":"Some compilers issue a warning when they compile this code.","pos":[0,59]},{"content":"Others issue an error, and the compilation fails.","pos":[60,109]},{"content":"To address this problem, instantiate the object so that its value is no longer <ph id=\"ph1\">`null`</ph>.","pos":[110,196],"source":" To address this problem, instantiate the object so that its value is no longer `null`."},{"content":"The following example does this by calling a type's class constructor.","pos":[197,267]}]},{"pos":[997,1318],"content":"<bpt id=\"p1\">[!code-csharp</bpt><bpt id=\"p2\">[</bpt>System.NullReferenceException.Class#2<ept id=\"p2\">](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.nullreferenceexception.class/cs/example1a.cs#2)</ept><ept id=\"p1\">]</ept>  <bpt id=\"p3\">[!code-vb</bpt><bpt id=\"p4\">[</bpt>System.NullReferenceException.Class#2<ept id=\"p4\">](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.nullreferenceexception.class/vb/example1a.vb#2)</ept><ept id=\"p3\">]</ept>","leadings":["","    "],"source":"[!code-csharp[System.NullReferenceException.Class#2](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.nullreferenceexception.class/cs/example1a.cs#2)]\n [!code-vb[System.NullReferenceException.Class#2](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.nullreferenceexception.class/vb/example1a.vb#2)]"},{"pos":[1328,1630],"content":"You've forgotten to dimension an array before initializing it. In the following example, `values` is declared to be an integer array, but the number of elements that it contains is never specified. The attempt to initialize its values therefore thrown a  <xref:System.NullReferenceException> exception.","nodes":[{"content":"You've forgotten to dimension an array before initializing it.","pos":[0,62]},{"content":"In the following example, <ph id=\"ph1\">`values`</ph> is declared to be an integer array, but the number of elements that it contains is never specified.","pos":[63,197],"source":" In the following example, `values` is declared to be an integer array, but the number of elements that it contains is never specified."},{"content":"The attempt to initialize its values therefore thrown a  <ph id=\"ph1\">&lt;xref:System.NullReferenceException&gt;</ph> exception.","pos":[198,302],"source":" The attempt to initialize its values therefore thrown a  <xref:System.NullReferenceException> exception."}]},{"pos":[1641,1960],"content":"<bpt id=\"p1\">[!code-csharp</bpt><bpt id=\"p2\">[</bpt>System.NullReferenceException.Class#10<ept id=\"p2\">](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.nullreferenceexception.class/cs/Array3.cs#10)</ept><ept id=\"p1\">]</ept>  <bpt id=\"p3\">[!code-vb</bpt><bpt id=\"p4\">[</bpt>System.NullReferenceException.Class#10<ept id=\"p4\">](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.nullreferenceexception.class/vb/Array3.vb#10)</ept><ept id=\"p3\">]</ept>","leadings":["","    "],"source":"[!code-csharp[System.NullReferenceException.Class#10](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.nullreferenceexception.class/cs/Array3.cs#10)]\n [!code-vb[System.NullReferenceException.Class#10](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.nullreferenceexception.class/vb/Array3.vb#10)]"},{"pos":[1971,2106],"content":"You can eliminate the exception by declaring the number of elements in the array before initializing it, as the following example does.","nodes":[{"content":"You can eliminate the exception by declaring the number of elements in the array before initializing it, as the following example does.","pos":[0,135]}]},{"pos":[2117,2436],"content":"<bpt id=\"p1\">[!code-csharp</bpt><bpt id=\"p2\">[</bpt>System.NullReferenceException.Class#11<ept id=\"p2\">](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.nullreferenceexception.class/cs/Array4.cs#11)</ept><ept id=\"p1\">]</ept>  <bpt id=\"p3\">[!code-vb</bpt><bpt id=\"p4\">[</bpt>System.NullReferenceException.Class#11<ept id=\"p4\">](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.nullreferenceexception.class/vb/Array4.vb#11)</ept><ept id=\"p3\">]</ept>","leadings":["","    "],"source":"[!code-csharp[System.NullReferenceException.Class#11](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.nullreferenceexception.class/cs/Array4.cs#11)]\n [!code-vb[System.NullReferenceException.Class#11](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.nullreferenceexception.class/vb/Array4.vb#11)]"},{"pos":[2447,2676],"content":"For more information on declaring and initializing arrays, see <bpt id=\"p1\">[</bpt>Arrays<ept id=\"p1\">](http://msdn.microsoft.com/library/bb79bdde-e570-4c30-adb0-1dd5759ae041)</ept> and <bpt id=\"p2\">[</bpt>Arrays<ept id=\"p2\">](http://msdn.microsoft.com/library/dbf29737-b589-4443-bee6-a27588d9c67e)</ept>.","source":"For more information on declaring and initializing arrays, see [Arrays](http://msdn.microsoft.com/library/bb79bdde-e570-4c30-adb0-1dd5759ae041) and [Arrays](http://msdn.microsoft.com/library/dbf29737-b589-4443-bee6-a27588d9c67e)."},{"pos":[2686,3005],"content":"You get a **null** return value from a method, and then call a method on the returned type. This sometimes is the result of a documentation error; the documentation fails to note that a method call can return `null`. In other cases, your code erroneously assumes that the method will always return a non-**null** value.","nodes":[{"content":"You get a <bpt id=\"p1\">**</bpt>null<ept id=\"p1\">**</ept> return value from a method, and then call a method on the returned type.","pos":[0,91],"source":"You get a **null** return value from a method, and then call a method on the returned type."},{"content":"This sometimes is the result of a documentation error; the documentation fails to note that a method call can return <ph id=\"ph1\">`null`</ph>.","pos":[92,216],"source":" This sometimes is the result of a documentation error; the documentation fails to note that a method call can return `null`."},{"content":"In other cases, your code erroneously assumes that the method will always return a non-<bpt id=\"p1\">**</bpt>null<ept id=\"p1\">**</ept> value.","pos":[217,319],"source":" In other cases, your code erroneously assumes that the method will always return a non-**null** value."}]},{"pos":[3016,3302],"content":"The code in the following example assumes that the <xref:System.Array.Find%2A?displayProperty=fullName> method always returns `Person` object whose `FirstName` field matches a search string. Because there is no match, the runtime throws a <xref:System.NullReferenceException> exception.","nodes":[{"content":"The code in the following example assumes that the <ph id=\"ph1\">&lt;xref:System.Array.Find%2A?displayProperty=fullName&gt;</ph> method always returns <ph id=\"ph2\">`Person`</ph> object whose <ph id=\"ph3\">`FirstName`</ph> field matches a search string.","pos":[0,190],"source":"The code in the following example assumes that the <xref:System.Array.Find%2A?displayProperty=fullName> method always returns `Person` object whose `FirstName` field matches a search string."},{"content":"Because there is no match, the runtime throws a <ph id=\"ph1\">&lt;xref:System.NullReferenceException&gt;</ph> exception.","pos":[191,286],"source":" Because there is no match, the runtime throws a <xref:System.NullReferenceException> exception."}]},{"pos":[3313,3638],"content":"<bpt id=\"p1\">[!code-csharp</bpt><bpt id=\"p2\">[</bpt>System.NullReferenceException.Class#4<ept id=\"p2\">](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.nullreferenceexception.class/cs/nullreturn2.cs#4)</ept><ept id=\"p1\">]</ept>  <bpt id=\"p3\">[!code-vb</bpt><bpt id=\"p4\">[</bpt>System.NullReferenceException.Class#4<ept id=\"p4\">](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.nullreferenceexception.class/vb/nullreturn2.vb#4)</ept><ept id=\"p3\">]</ept>","leadings":["","    "],"source":"[!code-csharp[System.NullReferenceException.Class#4](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.nullreferenceexception.class/cs/nullreturn2.cs#4)]\n [!code-vb[System.NullReferenceException.Class#4](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.nullreferenceexception.class/vb/nullreturn2.vb#4)]"},{"pos":[3649,3802],"content":"To address this problem, test the method's return value to ensure that it is not <ph id=\"ph1\">`null`</ph> before calling any of its members, as the following example does.","source":"To address this problem, test the method's return value to ensure that it is not `null` before calling any of its members, as the following example does."},{"pos":[3813,4140],"content":"<bpt id=\"p1\">[!code-csharp</bpt><bpt id=\"p2\">[</bpt>System.NullReferenceException.Class#5<ept id=\"p2\">](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.nullreferenceexception.class/cs/nullreturn2a.cs#5)</ept><ept id=\"p1\">]</ept>  <bpt id=\"p3\">[!code-vb</bpt><bpt id=\"p4\">[</bpt>System.NullReferenceException.Class#5<ept id=\"p4\">](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.nullreferenceexception.class/vb/nullreturn2a.vb#5)</ept><ept id=\"p3\">]</ept>","leadings":["","    "],"source":"[!code-csharp[System.NullReferenceException.Class#5](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.nullreferenceexception.class/cs/nullreturn2a.cs#5)]\n [!code-vb[System.NullReferenceException.Class#5](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.nullreferenceexception.class/vb/nullreturn2a.vb#5)]"},{"pos":[4150,4541],"content":"You're using an expression (for example, you're chaining a list of methods or properties together) to retrieve a value and, although you're checking whether the value is `null`, the runtime still throws a <xref:System.NullReferenceException> exception. This occurs because one of the intermediate values in the expression returns `null`. As a result, your rest for `null` is never evaluated.","nodes":[{"content":"You're using an expression (for example, you're chaining a list of methods or properties together) to retrieve a value and, although you're checking whether the value is <ph id=\"ph1\">`null`</ph>, the runtime still throws a <ph id=\"ph2\">&lt;xref:System.NullReferenceException&gt;</ph> exception.","pos":[0,252],"source":"You're using an expression (for example, you're chaining a list of methods or properties together) to retrieve a value and, although you're checking whether the value is `null`, the runtime still throws a <xref:System.NullReferenceException> exception."},{"content":"This occurs because one of the intermediate values in the expression returns <ph id=\"ph1\">`null`</ph>.","pos":[253,337],"source":" This occurs because one of the intermediate values in the expression returns `null`."},{"content":"As a result, your rest for <ph id=\"ph1\">`null`</ph> is never evaluated.","pos":[338,391],"source":" As a result, your rest for `null` is never evaluated."}]},{"pos":[4552,4896],"content":"The following example defines a `Pages` object that  caches information about web pages, which are presented by `Page` objects. The `Example.Main` method checks whether the current web page has a non-null title and, if it does, displays the title. Despite this check, however, the method throws a <xref:System.NullReferenceException> exception.","nodes":[{"content":"The following example defines a <ph id=\"ph1\">`Pages`</ph> object that  caches information about web pages, which are presented by <ph id=\"ph2\">`Page`</ph> objects.","pos":[0,127],"source":"The following example defines a `Pages` object that  caches information about web pages, which are presented by `Page` objects."},{"content":"The <ph id=\"ph1\">`Example.Main`</ph> method checks whether the current web page has a non-null title and, if it does, displays the title.","pos":[128,247],"source":" The `Example.Main` method checks whether the current web page has a non-null title and, if it does, displays the title."},{"content":"Despite this check, however, the method throws a <ph id=\"ph1\">&lt;xref:System.NullReferenceException&gt;</ph> exception.","pos":[248,344],"source":" Despite this check, however, the method throws a <xref:System.NullReferenceException> exception."}]},{"pos":[4907,5222],"content":"<bpt id=\"p1\">[!code-csharp</bpt><bpt id=\"p2\">[</bpt>System.NullReferenceException.Class#6<ept id=\"p2\">](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.nullreferenceexception.class/cs/Chain1.cs#6)</ept><ept id=\"p1\">]</ept>  <bpt id=\"p3\">[!code-vb</bpt><bpt id=\"p4\">[</bpt>System.NullReferenceException.Class#6<ept id=\"p4\">](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.nullreferenceexception.class/vb/Chain1.vb#6)</ept><ept id=\"p3\">]</ept>","leadings":["","    "],"source":"[!code-csharp[System.NullReferenceException.Class#6](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.nullreferenceexception.class/cs/Chain1.cs#6)]\n [!code-vb[System.NullReferenceException.Class#6](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.nullreferenceexception.class/vb/Chain1.vb#6)]"},{"pos":[5233,5525],"content":"The exception is thrown because `pages.CurrentPage` returns `null` if no page information is  stored in the cache. This exception can be corrected by testing the value of the `CurrentPage` property before retrieving the current `Page` object's `Title` property, as the following example does:","nodes":[{"content":"The exception is thrown because <ph id=\"ph1\">`pages.CurrentPage`</ph> returns <ph id=\"ph2\">`null`</ph> if no page information is  stored in the cache.","pos":[0,114],"source":"The exception is thrown because `pages.CurrentPage` returns `null` if no page information is  stored in the cache."},{"content":"This exception can be corrected by testing the value of the <ph id=\"ph1\">`CurrentPage`</ph> property before retrieving the current <ph id=\"ph2\">`Page`</ph> object's <ph id=\"ph3\">`Title`</ph> property, as the following example does:","pos":[115,292],"source":" This exception can be corrected by testing the value of the `CurrentPage` property before retrieving the current `Page` object's `Title` property, as the following example does:"}]},{"pos":[5536,5851],"content":"<bpt id=\"p1\">[!code-csharp</bpt><bpt id=\"p2\">[</bpt>System.NullReferenceException.Class#7<ept id=\"p2\">](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.nullreferenceexception.class/cs/Chain2.cs#7)</ept><ept id=\"p1\">]</ept>  <bpt id=\"p3\">[!code-vb</bpt><bpt id=\"p4\">[</bpt>System.NullReferenceException.Class#7<ept id=\"p4\">](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.nullreferenceexception.class/vb/Chain2.vb#7)</ept><ept id=\"p3\">]</ept>","leadings":["","    "],"source":"[!code-csharp[System.NullReferenceException.Class#7](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.nullreferenceexception.class/cs/Chain2.cs#7)]\n [!code-vb[System.NullReferenceException.Class#7](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.nullreferenceexception.class/vb/Chain2.vb#7)]"},{"pos":[5861,6040],"content":"You're enumerating the elements of an array that contains reference types, and your attempt to process one of the elements throws a <xref:System.NullReferenceException> exception.","nodes":[{"content":"You're enumerating the elements of an array that contains reference types, and your attempt to process one of the elements throws a <ph id=\"ph1\">&lt;xref:System.NullReferenceException&gt;</ph> exception.","pos":[0,179],"source":"You're enumerating the elements of an array that contains reference types, and your attempt to process one of the elements throws a <xref:System.NullReferenceException> exception."}]},{"pos":[6051,6241],"content":"The following example defines a string array. A `for` statement enumerates the elements in the array and calls each string's <xref:System.String.Trim%2A> method before displaying the string.","nodes":[{"content":"The following example defines a string array.","pos":[0,45]},{"content":"A <ph id=\"ph1\">`for`</ph> statement enumerates the elements in the array and calls each string's <ph id=\"ph2\">&lt;xref:System.String.Trim%2A&gt;</ph> method before displaying the string.","pos":[46,190],"source":" A `for` statement enumerates the elements in the array and calls each string's <xref:System.String.Trim%2A> method before displaying the string."}]},{"pos":[6252,6567],"content":"<bpt id=\"p1\">[!code-csharp</bpt><bpt id=\"p2\">[</bpt>System.NullReferenceException.Class#8<ept id=\"p2\">](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.nullreferenceexception.class/cs/Array1.cs#8)</ept><ept id=\"p1\">]</ept>  <bpt id=\"p3\">[!code-vb</bpt><bpt id=\"p4\">[</bpt>System.NullReferenceException.Class#8<ept id=\"p4\">](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.nullreferenceexception.class/vb/Array1.vb#8)</ept><ept id=\"p3\">]</ept>","leadings":["","    "],"source":"[!code-csharp[System.NullReferenceException.Class#8](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.nullreferenceexception.class/cs/Array1.cs#8)]\n [!code-vb[System.NullReferenceException.Class#8](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.nullreferenceexception.class/vb/Array1.vb#8)]"},{"pos":[6578,6883],"content":"This exception occurs if you assume that each element of the array must contain a non-null value, and the value of the array element is in fact `null`. The exception can be eliminated by testing whether the element is `null` before performing any operation on that element, as the following example shows.","nodes":[{"content":"This exception occurs if you assume that each element of the array must contain a non-null value, and the value of the array element is in fact <ph id=\"ph1\">`null`</ph>.","pos":[0,151],"source":"This exception occurs if you assume that each element of the array must contain a non-null value, and the value of the array element is in fact `null`."},{"content":"The exception can be eliminated by testing whether the element is <ph id=\"ph1\">`null`</ph> before performing any operation on that element, as the following example shows.","pos":[152,305],"source":" The exception can be eliminated by testing whether the element is `null` before performing any operation on that element, as the following example shows."}]},{"pos":[6894,7209],"content":"<bpt id=\"p1\">[!code-csharp</bpt><bpt id=\"p2\">[</bpt>System.NullReferenceException.Class#9<ept id=\"p2\">](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.nullreferenceexception.class/cs/Array2.cs#9)</ept><ept id=\"p1\">]</ept>  <bpt id=\"p3\">[!code-vb</bpt><bpt id=\"p4\">[</bpt>System.NullReferenceException.Class#9<ept id=\"p4\">](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.nullreferenceexception.class/vb/Array2.vb#9)</ept><ept id=\"p3\">]</ept>","leadings":["","    "],"source":"[!code-csharp[System.NullReferenceException.Class#9](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.nullreferenceexception.class/cs/Array2.cs#9)]\n [!code-vb[System.NullReferenceException.Class#9](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.nullreferenceexception.class/vb/Array2.vb#9)]"},{"pos":[7219,7633],"content":"A <xref:System.NullReferenceException> exception is thrown by a method that is passed `null`. Some methods validate the arguments that are passed to them. If they do and one of the arguments is `null`, the method throws an <xref:System.ArgumentNullException?displayProperty=fullName> exception. Otherwise, it throws a <xref:System.NullReferenceException> exception. The following example illustrates this scenario.","nodes":[{"content":"A <ph id=\"ph1\">&lt;xref:System.NullReferenceException&gt;</ph> exception is thrown by a method that is passed <ph id=\"ph2\">`null`</ph>.","pos":[0,93],"source":"A <xref:System.NullReferenceException> exception is thrown by a method that is passed `null`."},{"content":"Some methods validate the arguments that are passed to them.","pos":[94,154]},{"content":"If they do and one of the arguments is <ph id=\"ph1\">`null`</ph>, the method throws an <ph id=\"ph2\">&lt;xref:System.ArgumentNullException?displayProperty=fullName&gt;</ph> exception.","pos":[155,294],"source":" If they do and one of the arguments is `null`, the method throws an <xref:System.ArgumentNullException?displayProperty=fullName> exception."},{"content":"Otherwise, it throws a <ph id=\"ph1\">&lt;xref:System.NullReferenceException&gt;</ph> exception.","pos":[295,365],"source":" Otherwise, it throws a <xref:System.NullReferenceException> exception."},{"content":"The following example illustrates this scenario.","pos":[366,414]}]},{"pos":[7644,7963],"content":"<bpt id=\"p1\">[!code-csharp</bpt><bpt id=\"p2\">[</bpt>System.NullReferenceException.Class#3<ept id=\"p2\">](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.nullreferenceexception.class/cs/example2.cs#3)</ept><ept id=\"p1\">]</ept>  <bpt id=\"p3\">[!code-vb</bpt><bpt id=\"p4\">[</bpt>System.NullReferenceException.Class#3<ept id=\"p4\">](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.nullreferenceexception.class/vb/example2.vb#3)</ept><ept id=\"p3\">]</ept>","leadings":["","    "],"source":"[!code-csharp[System.NullReferenceException.Class#3](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.nullreferenceexception.class/cs/example2.cs#3)]\n [!code-vb[System.NullReferenceException.Class#3](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.nullreferenceexception.class/vb/example2.vb#3)]"},{"pos":[7974,8235],"content":"To address this issue, make sure that the argument passed to the method is not `null`, or handle the thrown exception in a `try…catch…finally` block. For more information, see [Exceptions](http://msdn.microsoft.com/library/f99a1d29-a2a8-47af-9707-9909f9010735).","nodes":[{"content":"To address this issue, make sure that the argument passed to the method is not <ph id=\"ph1\">`null`</ph>, or handle the thrown exception in a <ph id=\"ph2\">`try…catch…finally`</ph> block.","pos":[0,149],"source":"To address this issue, make sure that the argument passed to the method is not `null`, or handle the thrown exception in a `try…catch…finally` block."},{"content":"For more information, see <bpt id=\"p1\">[</bpt>Exceptions<ept id=\"p1\">](http://msdn.microsoft.com/library/f99a1d29-a2a8-47af-9707-9909f9010735)</ept>.","pos":[150,261],"source":" For more information, see [Exceptions](http://msdn.microsoft.com/library/f99a1d29-a2a8-47af-9707-9909f9010735)."}]},{"pos":[8242,8528],"content":"The following Microsoft intermediate language (MSIL) instructions throw <ph id=\"ph1\">&lt;xref:System.NullReferenceException&gt;</ph>: <ph id=\"ph2\">`callvirt`</ph>, <ph id=\"ph3\">`cpblk`</ph>, <ph id=\"ph4\">`cpobj`</ph>, <ph id=\"ph5\">`initblk`</ph>, <ph id=\"ph6\">`ldelem.&lt;type&gt;`</ph>, <ph id=\"ph7\">`ldelema`</ph>, <ph id=\"ph8\">`ldfld`</ph>, <ph id=\"ph9\">`ldflda`</ph>, <ph id=\"ph10\">`ldind.&lt;type&gt;`</ph>, <ph id=\"ph11\">`ldlen`</ph>, <ph id=\"ph12\">`stelem.&lt;type&gt;`</ph>, <ph id=\"ph13\">`stfld`</ph>, <ph id=\"ph14\">`stind.&lt;type&gt;`</ph>, <ph id=\"ph15\">`throw`</ph>, and <ph id=\"ph16\">`unbox`</ph>.","source":"The following Microsoft intermediate language (MSIL) instructions throw <xref:System.NullReferenceException>: `callvirt`, `cpblk`, `cpobj`, `initblk`, `ldelem.<type>`, `ldelema`, `ldfld`, `ldflda`, `ldind.<type>`, `ldlen`, `stelem.<type>`, `stfld`, `stind.<type>`, `throw`, and `unbox`."},{"pos":[8535,8641],"content":"<xref:System.NullReferenceException> uses the HRESULT COR_E_NULLREFERENCE, which has the value 0x80004003.","nodes":[{"content":"<ph id=\"ph1\">&lt;xref:System.NullReferenceException&gt;</ph> uses the HRESULT COR_E_NULLREFERENCE, which has the value 0x80004003.","pos":[0,106],"source":"<xref:System.NullReferenceException> uses the HRESULT COR_E_NULLREFERENCE, which has the value 0x80004003."}]},{"pos":[8648,8812],"content":"For a list of initial property values for an instance of <xref:System.NullReferenceException>, see the <xref:System.NullReferenceException.%23ctor%2A> constructors.","nodes":[{"content":"For a list of initial property values for an instance of <ph id=\"ph1\">&lt;xref:System.NullReferenceException&gt;</ph>, see the <ph id=\"ph2\">&lt;xref:System.NullReferenceException.%23ctor%2A&gt;</ph> constructors.","pos":[0,164],"source":"For a list of initial property values for an instance of <xref:System.NullReferenceException>, see the <xref:System.NullReferenceException.%23ctor%2A> constructors."}]},{"pos":[8819,8870],"content":"<bpt id=\"p1\">**</bpt>Handling NullReferenceException in release code<ept id=\"p1\">**</ept>","source":"**Handling NullReferenceException in release code**"},{"pos":[8877,9222],"content":"It's usually better to avoid a NullReferenceException than to handle it after it occurs. Handling an exception can make your code harder to maintain and understand, and can sometimes introduce other bugs. A NullReferenceException is often a non-recoverable error. In these cases, letting the exception stop the app might be the best alternative.","nodes":[{"content":"It's usually better to avoid a NullReferenceException than to handle it after it occurs. Handling an exception can make your code harder to maintain and understand, and can sometimes introduce other bugs. A NullReferenceException is often a non-recoverable error. In these cases, letting the exception stop the app might be the best alternative.","pos":[0,345],"nodes":[{"content":"It's usually better to avoid a NullReferenceException than to handle it after it occurs.","pos":[0,88]},{"content":"Handling an exception can make your code harder to maintain and understand, and can sometimes introduce other bugs.","pos":[89,204]},{"content":"A NullReferenceException is often a non-recoverable error.","pos":[205,263]},{"content":"In these cases, letting the exception stop the app might be the best alternative.","pos":[264,345]}]}]},{"pos":[9229,9303],"content":"However, there are many situations where handling the error can be useful:","nodes":[{"content":"However, there are many situations where handling the error can be useful:","pos":[0,74]}]},{"pos":[9313,9602],"content":"Your app can ignore objects that are null. For example, if your app retrieves and processes records in a database, you might be able to ignore some number of bad records that result in null objects. Recording the bad data in a log file or in the application UI might be all you have to do.","nodes":[{"content":"Your app can ignore objects that are null. For example, if your app retrieves and processes records in a database, you might be able to ignore some number of bad records that result in null objects. Recording the bad data in a log file or in the application UI might be all you have to do.","pos":[0,289],"nodes":[{"content":"Your app can ignore objects that are null.","pos":[0,42]},{"content":"For example, if your app retrieves and processes records in a database, you might be able to ignore some number of bad records that result in null objects.","pos":[43,198]},{"content":"Recording the bad data in a log file or in the application UI might be all you have to do.","pos":[199,289]}]}]},{"pos":[9612,9857],"content":"You can recover from the exception. For example, a call to a web service that returns a reference type might return null if the connection is lost or the connection times out. You can attempt to reestablish the connection and try the call again.","nodes":[{"content":"You can recover from the exception. For example, a call to a web service that returns a reference type might return null if the connection is lost or the connection times out. You can attempt to reestablish the connection and try the call again.","pos":[0,245],"nodes":[{"content":"You can recover from the exception.","pos":[0,35]},{"content":"For example, a call to a web service that returns a reference type might return null if the connection is lost or the connection times out.","pos":[36,175]},{"content":"You can attempt to reestablish the connection and try the call again.","pos":[176,245]}]}]},{"pos":[9867,10212],"content":"You can restore the state of your app to a valid state. For example, you might be performing a multi-step task that requires you to save information to a data store before you call a method that throws a NullReferenceException. If the uninitialized object would corrupt the data record, you can remove the previous data before you close the app.","nodes":[{"content":"You can restore the state of your app to a valid state. For example, you might be performing a multi-step task that requires you to save information to a data store before you call a method that throws a NullReferenceException. If the uninitialized object would corrupt the data record, you can remove the previous data before you close the app.","pos":[0,345],"nodes":[{"content":"You can restore the state of your app to a valid state.","pos":[0,55]},{"content":"For example, you might be performing a multi-step task that requires you to save information to a data store before you call a method that throws a NullReferenceException.","pos":[56,227]},{"content":"If the uninitialized object would corrupt the data record, you can remove the previous data before you close the app.","pos":[228,345]}]}]},{"pos":[10222,10687],"content":"You want to report the exception. For example, if the error was caused by a mistake from the user of your app, you can generate a message to help him supply the correct information. You can also log information about the error to help you fix the problem. Some frameworks, like ASP.NET, have a high-level exception handler that captures all errors to that the app never crashes; in that case, logging the exception might be the only way you can know that it occurs.","nodes":[{"content":"You want to report the exception. For example, if the error was caused by a mistake from the user of your app, you can generate a message to help him supply the correct information. You can also log information about the error to help you fix the problem. Some frameworks, like ASP.NET, have a high-level exception handler that captures all errors to that the app never crashes; in that case, logging the exception might be the only way you can know that it occurs.","pos":[0,465],"nodes":[{"content":"You want to report the exception.","pos":[0,33]},{"content":"For example, if the error was caused by a mistake from the user of your app, you can generate a message to help him supply the correct information.","pos":[34,181]},{"content":"You can also log information about the error to help you fix the problem.","pos":[182,255]},{"content":"Some frameworks, like ASP.NET, have a high-level exception handler that captures all errors to that the app never crashes; in that case, logging the exception might be the only way you can know that it occurs.","pos":[256,465]}]}]}],"pos":[804,11579],"yaml":true,"extradata":"MT"},{"content":"Initializes a new instance of the <xref href=\"System.NullReferenceException\"></xref> class, setting the <xref href=\"System.Exception.Message\"></xref> property of the new instance to a system-supplied message that describes the error, such as \"The value 'null' was found where an instance of an object was required.\" This message takes into account the current system culture.","nodes":[{"pos":[0,375],"content":"Initializes a new instance of the <xref href=\"System.NullReferenceException\"></xref> class, setting the <xref href=\"System.Exception.Message\"></xref> property of the new instance to a system-supplied message that describes the error, such as \"The value 'null' was found where an instance of an object was required.\" This message takes into account the current system culture.","nodes":[{"content":"Initializes a new instance of the <ph id=\"ph1\">&lt;xref href=\"System.NullReferenceException\"&gt;&lt;/xref&gt;</ph> class, setting the <ph id=\"ph2\">&lt;xref href=\"System.Exception.Message\"&gt;&lt;/xref&gt;</ph> property of the new instance to a system-supplied message that describes the error, such as \"The value 'null' was found where an instance of an object was required.\"","pos":[0,315],"source":"Initializes a new instance of the <xref href=\"System.NullReferenceException\"></xref> class, setting the <xref href=\"System.Exception.Message\"></xref> property of the new instance to a system-supplied message that describes the error, such as \"The value 'null' was found where an instance of an object was required.\""},{"content":"This message takes into account the current system culture.","pos":[316,375]}]}],"pos":[14127,14503],"yaml":true},{"content":"The following table shows the initial property values for an instance of <xref:System.NullReferenceException>.  \n  \n|Property|Value|  \n|--------------|-----------|  \n|<xref:System.Exception.InnerException%2A>|`null`.|  \n|<xref:System.Exception.Message%2A>|The localized error message string.|","nodes":[{"pos":[0,110],"content":"The following table shows the initial property values for an instance of <xref:System.NullReferenceException>.","nodes":[{"content":"The following table shows the initial property values for an instance of <ph id=\"ph1\">&lt;xref:System.NullReferenceException&gt;</ph>.","pos":[0,110],"source":"The following table shows the initial property values for an instance of <xref:System.NullReferenceException>."}]},{"pos":[117,125],"content":"Property","nodes":[{"content":"Property","pos":[0,8]}]},{"pos":[126,131],"content":"Value","nodes":[{"content":"Value","pos":[0,5]}]},{"pos":[167,208],"content":"<xref:System.Exception.InnerException%2A>","nodes":[]},{"pos":[209,216],"content":"<ph id=\"ph1\">`null`</ph>.","source":"`null`."},{"pos":[221,255],"content":"<xref:System.Exception.Message%2A>","nodes":[]},{"pos":[256,291],"content":"The localized error message string.","nodes":[{"content":"The localized error message string.","pos":[0,35]}]}],"pos":[14514,14814],"yaml":true,"extradata":"MT"},{"content":"Initializes a new instance of the <xref href=\"System.NullReferenceException\"></xref> class with a specified error message.","nodes":[{"pos":[0,122],"content":"Initializes a new instance of the <ph id=\"ph1\">&lt;xref href=\"System.NullReferenceException\"&gt;&lt;/xref&gt;</ph> class with a specified error message.","source":"Initializes a new instance of the <xref href=\"System.NullReferenceException\"></xref> class with a specified error message."}],"pos":[16527,16650],"yaml":true},{"content":"The following table shows the initial property values for an instance of <xref:System.NullReferenceException>.  \n  \n|Property|Value|  \n|--------------|-----------|  \n|<xref:System.Exception.InnerException%2A>|`null`.|  \n|<xref:System.Exception.Message%2A>|The error message string.|","nodes":[{"pos":[0,110],"content":"The following table shows the initial property values for an instance of <xref:System.NullReferenceException>.","nodes":[{"content":"The following table shows the initial property values for an instance of <ph id=\"ph1\">&lt;xref:System.NullReferenceException&gt;</ph>.","pos":[0,110],"source":"The following table shows the initial property values for an instance of <xref:System.NullReferenceException>."}]},{"pos":[117,125],"content":"Property","nodes":[{"content":"Property","pos":[0,8]}]},{"pos":[126,131],"content":"Value","nodes":[{"content":"Value","pos":[0,5]}]},{"pos":[167,208],"content":"<xref:System.Exception.InnerException%2A>","nodes":[]},{"pos":[209,216],"content":"<ph id=\"ph1\">`null`</ph>.","source":"`null`."},{"pos":[221,255],"content":"<xref:System.Exception.Message%2A>","nodes":[]},{"pos":[256,281],"content":"The error message string.","nodes":[{"content":"The error message string.","pos":[0,25]}]}],"pos":[16661,16951],"yaml":true,"extradata":"MT"},{"content":"A <xref href=\"System.String\"></xref> that describes the error. The content of <code>message</code> is intended to be understood by humans. The caller of this constructor is required to ensure that this string has been localized for the current system culture.","nodes":[{"pos":[0,259],"content":"A <xref href=\"System.String\"></xref> that describes the error. The content of <code>message</code> is intended to be understood by humans. The caller of this constructor is required to ensure that this string has been localized for the current system culture.","nodes":[{"content":"A <ph id=\"ph1\">&lt;xref href=\"System.String\"&gt;&lt;/xref&gt;</ph> that describes the error.","pos":[0,62],"source":"A <xref href=\"System.String\"></xref> that describes the error."},{"content":"The content of <bpt id=\"p1\">&lt;code&gt;</bpt><ph id=\"ph1\">message</ph><ept id=\"p1\">&lt;/code&gt;</ept> is intended to be understood by humans.","pos":[63,138],"source":" The content of <code>message</code> is intended to be understood by humans."},{"content":"The caller of this constructor is required to ensure that this string has been localized for the current system culture.","pos":[139,259]}]}],"pos":[17101,17361],"yaml":true},{"content":"Initializes a new instance of the <xref href=\"System.NullReferenceException\"></xref> class with serialized data.","nodes":[{"pos":[0,112],"content":"Initializes a new instance of the <ph id=\"ph1\">&lt;xref href=\"System.NullReferenceException\"&gt;&lt;/xref&gt;</ph> class with serialized data.","source":"Initializes a new instance of the <xref href=\"System.NullReferenceException\"></xref> class with serialized data."}],"pos":[19322,19435],"yaml":true},{"content":"This constructor is called during deserialization to reconstitute the exception object transmitted over a stream. For more information, see [XML and SOAP Serialization](~/docs/framework/serialization/xml-and-soap-serialization.md).","nodes":[{"pos":[0,231],"content":"This constructor is called during deserialization to reconstitute the exception object transmitted over a stream. For more information, see [XML and SOAP Serialization](~/docs/framework/serialization/xml-and-soap-serialization.md).","nodes":[{"content":"This constructor is called during deserialization to reconstitute the exception object transmitted over a stream.","pos":[0,113]},{"content":"For more information, see <bpt id=\"p1\">[</bpt>XML and SOAP Serialization<ept id=\"p1\">](~/docs/framework/serialization/xml-and-soap-serialization.md)</ept>.","pos":[114,231],"source":" For more information, see [XML and SOAP Serialization](~/docs/framework/serialization/xml-and-soap-serialization.md)."}]}],"pos":[19446,19678],"yaml":true,"extradata":"MT"},{"content":"The object that holds the serialized object data.","nodes":[{"pos":[0,49],"content":"The object that holds the serialized object data.","nodes":[{"content":"The object that holds the serialized object data.","pos":[0,49]}]}],"pos":[19953,20003],"yaml":true},{"content":"The contextual information about the source or destination.","nodes":[{"pos":[0,59],"content":"The contextual information about the source or destination.","nodes":[{"content":"The contextual information about the source or destination.","pos":[0,59]}]}],"pos":[20098,20158],"yaml":true},{"content":"Initializes a new instance of the <xref href=\"System.NullReferenceException\"></xref> class with a specified error message and a reference to the inner exception that is the cause of this exception.","nodes":[{"pos":[0,197],"content":"Initializes a new instance of the <ph id=\"ph1\">&lt;xref href=\"System.NullReferenceException\"&gt;&lt;/xref&gt;</ph> class with a specified error message and a reference to the inner exception that is the cause of this exception.","source":"Initializes a new instance of the <xref href=\"System.NullReferenceException\"></xref> class with a specified error message and a reference to the inner exception that is the cause of this exception."}],"pos":[21535,21733],"yaml":true},{"content":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property. The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or `null` if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor.  \n  \n The following table shows the initial property values for an instance of <xref:System.NullReferenceException>.  \n  \n|Property|Value|  \n|--------------|-----------|  \n|<xref:System.Exception.InnerException%2A>|The inner exception reference.|  \n|<xref:System.Exception.Message%2A>|The error message string.|","nodes":[{"pos":[0,427],"content":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property. The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or `null` if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor.","nodes":[{"content":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <ph id=\"ph1\">&lt;xref:System.Exception.InnerException%2A&gt;</ph> property.","pos":[0,182],"source":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property."},{"content":"The <ph id=\"ph1\">&lt;xref:System.Exception.InnerException%2A&gt;</ph> property returns the same value that is passed into the constructor, or <ph id=\"ph2\">`null`</ph> if the <ph id=\"ph3\">&lt;xref:System.Exception.InnerException%2A&gt;</ph> property does not supply the inner exception value to the constructor.","pos":[183,427],"source":" The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or `null` if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor."}]},{"pos":[434,544],"content":"The following table shows the initial property values for an instance of <xref:System.NullReferenceException>.","nodes":[{"content":"The following table shows the initial property values for an instance of <ph id=\"ph1\">&lt;xref:System.NullReferenceException&gt;</ph>.","pos":[0,110],"source":"The following table shows the initial property values for an instance of <xref:System.NullReferenceException>."}]},{"pos":[551,559],"content":"Property","nodes":[{"content":"Property","pos":[0,8]}]},{"pos":[560,565],"content":"Value","nodes":[{"content":"Value","pos":[0,5]}]},{"pos":[601,642],"content":"<xref:System.Exception.InnerException%2A>","nodes":[]},{"pos":[643,673],"content":"The inner exception reference.","nodes":[{"content":"The inner exception reference.","pos":[0,30]}]},{"pos":[678,712],"content":"<xref:System.Exception.Message%2A>","nodes":[]},{"pos":[713,738],"content":"The error message string.","nodes":[{"content":"The error message string.","pos":[0,25]}]}],"pos":[21744,22493],"yaml":true,"extradata":"MT"},{"content":"The error message that explains the reason for the exception.","nodes":[{"pos":[0,61],"content":"The error message that explains the reason for the exception.","nodes":[{"content":"The error message that explains the reason for the exception.","pos":[0,61]}]}],"pos":[22669,22731],"yaml":true},{"content":"The exception that is the cause of the current exception. If the <code>innerException</code> parameter is not `null`, the current exception is raised in a `catch` block that handles the inner exception.","nodes":[{"pos":[0,202],"content":"The exception that is the cause of the current exception. If the <code>innerException</code> parameter is not `null`, the current exception is raised in a `catch` block that handles the inner exception.","nodes":[{"content":"The exception that is the cause of the current exception.","pos":[0,57]},{"content":"If the <bpt id=\"p1\">&lt;code&gt;</bpt><ph id=\"ph1\">innerException</ph><ept id=\"p1\">&lt;/code&gt;</ept> parameter is not <ph id=\"ph2\">`null`</ph>, the current exception is raised in a <ph id=\"ph3\">`catch`</ph> block that handles the inner exception.","pos":[58,202],"source":" If the <code>innerException</code> parameter is not `null`, the current exception is raised in a `catch` block that handles the inner exception."}]}],"pos":[22804,23007],"yaml":true}],"content":"### YamlMime:ManagedReference\nitems:\n- uid: System.NullReferenceException\n  commentId: T:System.NullReferenceException\n  id: NullReferenceException\n  children:\n  - System.NullReferenceException.#ctor\n  - System.NullReferenceException.#ctor(System.String)\n  - System.NullReferenceException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  - System.NullReferenceException.#ctor(System.String,System.Exception)\n  langs:\n  - csharp\n  name: NullReferenceException\n  nameWithType: NullReferenceException\n  fullName: System.NullReferenceException\n  type: Class\n  assemblies:\n  - System.Runtime\n  - mscorlib\n  - netstandard\n  namespace: System\n  summary: The exception that is thrown when there is an attempt to dereference a null object reference.\n  remarks: \"A <xref:System.NullReferenceException> exception is thrown when you try to access a member on a type whose value is `null`. A <xref:System.NullReferenceException> exception typically reflects developer error and is thrown in the following scenarios:  \\n  \\n-   You've forgotten to instantiate a reference type. In the following example, `names` is declared but never instantiated:  \\n  \\n     [!code-csharp[System.NullReferenceException.Class#1](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.nullreferenceexception.class/cs/example1.cs#1)]\\n     [!code-vb[System.NullReferenceException.Class#1](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.nullreferenceexception.class/vb/example1.vb#1)]  \\n  \\n     Some compilers issue a warning when they compile this code. Others issue an error, and the compilation fails. To address this problem, instantiate the object so that its value is no longer `null`. The following example does this by calling a type's class constructor.  \\n  \\n     [!code-csharp[System.NullReferenceException.Class#2](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.nullreferenceexception.class/cs/example1a.cs#2)]\\n     [!code-vb[System.NullReferenceException.Class#2](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.nullreferenceexception.class/vb/example1a.vb#2)]  \\n  \\n-   You've forgotten to dimension an array before initializing it. In the following example, `values` is declared to be an integer array, but the number of elements that it contains is never specified. The attempt to initialize its values therefore thrown a  <xref:System.NullReferenceException> exception.  \\n  \\n     [!code-csharp[System.NullReferenceException.Class#10](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.nullreferenceexception.class/cs/Array3.cs#10)]\\n     [!code-vb[System.NullReferenceException.Class#10](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.nullreferenceexception.class/vb/Array3.vb#10)]  \\n  \\n     You can eliminate the exception by declaring the number of elements in the array before initializing it, as the following example does.  \\n  \\n     [!code-csharp[System.NullReferenceException.Class#11](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.nullreferenceexception.class/cs/Array4.cs#11)]\\n     [!code-vb[System.NullReferenceException.Class#11](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.nullreferenceexception.class/vb/Array4.vb#11)]  \\n  \\n     For more information on declaring and initializing arrays, see [Arrays](http://msdn.microsoft.com/library/bb79bdde-e570-4c30-adb0-1dd5759ae041) and [Arrays](http://msdn.microsoft.com/library/dbf29737-b589-4443-bee6-a27588d9c67e).  \\n  \\n-   You get a **null** return value from a method, and then call a method on the returned type. This sometimes is the result of a documentation error; the documentation fails to note that a method call can return `null`. In other cases, your code erroneously assumes that the method will always return a non-**null** value.  \\n  \\n     The code in the following example assumes that the <xref:System.Array.Find%2A?displayProperty=fullName> method always returns `Person` object whose `FirstName` field matches a search string. Because there is no match, the runtime throws a <xref:System.NullReferenceException> exception.  \\n  \\n     [!code-csharp[System.NullReferenceException.Class#4](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.nullreferenceexception.class/cs/nullreturn2.cs#4)]\\n     [!code-vb[System.NullReferenceException.Class#4](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.nullreferenceexception.class/vb/nullreturn2.vb#4)]  \\n  \\n     To address this problem, test the method's return value to ensure that it is not `null` before calling any of its members, as the following example does.  \\n  \\n     [!code-csharp[System.NullReferenceException.Class#5](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.nullreferenceexception.class/cs/nullreturn2a.cs#5)]\\n     [!code-vb[System.NullReferenceException.Class#5](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.nullreferenceexception.class/vb/nullreturn2a.vb#5)]  \\n  \\n-   You're using an expression (for example, you're chaining a list of methods or properties together) to retrieve a value and, although you're checking whether the value is `null`, the runtime still throws a <xref:System.NullReferenceException> exception. This occurs because one of the intermediate values in the expression returns `null`. As a result, your rest for `null` is never evaluated.  \\n  \\n     The following example defines a `Pages` object that  caches information about web pages, which are presented by `Page` objects. The `Example.Main` method checks whether the current web page has a non-null title and, if it does, displays the title. Despite this check, however, the method throws a <xref:System.NullReferenceException> exception.  \\n  \\n     [!code-csharp[System.NullReferenceException.Class#6](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.nullreferenceexception.class/cs/Chain1.cs#6)]\\n     [!code-vb[System.NullReferenceException.Class#6](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.nullreferenceexception.class/vb/Chain1.vb#6)]  \\n  \\n     The exception is thrown because `pages.CurrentPage` returns `null` if no page information is  stored in the cache. This exception can be corrected by testing the value of the `CurrentPage` property before retrieving the current `Page` object's `Title` property, as the following example does:  \\n  \\n     [!code-csharp[System.NullReferenceException.Class#7](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.nullreferenceexception.class/cs/Chain2.cs#7)]\\n     [!code-vb[System.NullReferenceException.Class#7](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.nullreferenceexception.class/vb/Chain2.vb#7)]  \\n  \\n-   You're enumerating the elements of an array that contains reference types, and your attempt to process one of the elements throws a <xref:System.NullReferenceException> exception.  \\n  \\n     The following example defines a string array. A `for` statement enumerates the elements in the array and calls each string's <xref:System.String.Trim%2A> method before displaying the string.  \\n  \\n     [!code-csharp[System.NullReferenceException.Class#8](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.nullreferenceexception.class/cs/Array1.cs#8)]\\n     [!code-vb[System.NullReferenceException.Class#8](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.nullreferenceexception.class/vb/Array1.vb#8)]  \\n  \\n     This exception occurs if you assume that each element of the array must contain a non-null value, and the value of the array element is in fact `null`. The exception can be eliminated by testing whether the element is `null` before performing any operation on that element, as the following example shows.  \\n  \\n     [!code-csharp[System.NullReferenceException.Class#9](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.nullreferenceexception.class/cs/Array2.cs#9)]\\n     [!code-vb[System.NullReferenceException.Class#9](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.nullreferenceexception.class/vb/Array2.vb#9)]  \\n  \\n-   A <xref:System.NullReferenceException> exception is thrown by a method that is passed `null`. Some methods validate the arguments that are passed to them. If they do and one of the arguments is `null`, the method throws an <xref:System.ArgumentNullException?displayProperty=fullName> exception. Otherwise, it throws a <xref:System.NullReferenceException> exception. The following example illustrates this scenario.  \\n  \\n     [!code-csharp[System.NullReferenceException.Class#3](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.nullreferenceexception.class/cs/example2.cs#3)]\\n     [!code-vb[System.NullReferenceException.Class#3](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.nullreferenceexception.class/vb/example2.vb#3)]  \\n  \\n     To address this issue, make sure that the argument passed to the method is not `null`, or handle the thrown exception in a `try…catch…finally` block. For more information, see [Exceptions](http://msdn.microsoft.com/library/f99a1d29-a2a8-47af-9707-9909f9010735).  \\n  \\n The following Microsoft intermediate language (MSIL) instructions throw <xref:System.NullReferenceException>: `callvirt`, `cpblk`, `cpobj`, `initblk`, `ldelem.<type>`, `ldelema`, `ldfld`, `ldflda`, `ldind.<type>`, `ldlen`, `stelem.<type>`, `stfld`, `stind.<type>`, `throw`, and `unbox`.  \\n  \\n <xref:System.NullReferenceException> uses the HRESULT COR_E_NULLREFERENCE, which has the value 0x80004003.  \\n  \\n For a list of initial property values for an instance of <xref:System.NullReferenceException>, see the <xref:System.NullReferenceException.%23ctor%2A> constructors.  \\n  \\n **Handling NullReferenceException in release code**  \\n  \\n It's usually better to avoid a NullReferenceException than to handle it after it occurs. Handling an exception can make your code harder to maintain and understand, and can sometimes introduce other bugs. A NullReferenceException is often a non-recoverable error. In these cases, letting the exception stop the app might be the best alternative.  \\n  \\n However, there are many situations where handling the error can be useful:  \\n  \\n-   Your app can ignore objects that are null. For example, if your app retrieves and processes records in a database, you might be able to ignore some number of bad records that result in null objects. Recording the bad data in a log file or in the application UI might be all you have to do.  \\n  \\n-   You can recover from the exception. For example, a call to a web service that returns a reference type might return null if the connection is lost or the connection times out. You can attempt to reestablish the connection and try the call again.  \\n  \\n-   You can restore the state of your app to a valid state. For example, you might be performing a multi-step task that requires you to save information to a data store before you call a method that throws a NullReferenceException. If the uninitialized object would corrupt the data record, you can remove the previous data before you close the app.  \\n  \\n-   You want to report the exception. For example, if the error was caused by a mistake from the user of your app, you can generate a message to help him supply the correct information. You can also log information about the error to help you fix the problem. Some frameworks, like ASP.NET, have a high-level exception handler that captures all errors to that the app never crashes; in that case, logging the exception might be the only way you can know that it occurs.\"\n  syntax:\n    content: >-\n      [System.Runtime.InteropServices.ComVisible(true)]\n\n      public class NullReferenceException : SystemException\n  inheritance:\n  - System.Object\n  - System.Exception\n  implements: []\n  inheritedMembers:\n  - System.Exception.Data\n  - System.Exception.GetBaseException\n  - System.Exception.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  - System.Exception.GetType\n  - System.Exception.HelpLink\n  - System.Exception.HResult\n  - System.Exception.InnerException\n  - System.Exception.Message\n  - System.Exception.SerializeObjectState\n  - System.Exception.Source\n  - System.Exception.StackTrace\n  - System.Exception.TargetSite\n  - System.Exception.ToString\n  - System.Object.Equals(System.Object)\n  - System.Object.Equals(System.Object,System.Object)\n  - System.Object.GetHashCode\n  - System.Object.MemberwiseClone\n  - System.Object.ReferenceEquals(System.Object,System.Object)\n  attributes:\n  - type: System.Runtime.InteropServices.ComVisibleAttribute\n  version:\n  - netcore-1.0\n  - netcore-1.1\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-1.0\n  - netstandard-1.1\n  - netstandard-1.2\n  - netstandard-1.3\n  - netstandard-1.4\n  - netstandard-1.5\n  - netstandard-1.6\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  monikers:\n  - netcore-1.0\n  - netcore-1.1\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-1.0\n  - netstandard-1.1\n  - netstandard-1.2\n  - netstandard-1.3\n  - netstandard-1.4\n  - netstandard-1.5\n  - netstandard-1.6\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System/NullReferenceException.xml\n  ms.technology:\n  - dotnet-standard\n  author: rpetrusha\n  ms.author: ronpet\n  manager: wpickett\n- uid: System.NullReferenceException.#ctor\n  commentId: M:System.NullReferenceException.#ctor\n  id: '#ctor'\n  parent: System.NullReferenceException\n  langs:\n  - csharp\n  name: NullReferenceException()\n  nameWithType: NullReferenceException.NullReferenceException()\n  fullName: NullReferenceException.NullReferenceException()\n  type: Constructor\n  assemblies:\n  - System.Runtime\n  - mscorlib\n  - netstandard\n  namespace: System\n  summary: Initializes a new instance of the <xref href=\"System.NullReferenceException\"></xref> class, setting the <xref href=\"System.Exception.Message\"></xref> property of the new instance to a system-supplied message that describes the error, such as \"The value 'null' was found where an instance of an object was required.\" This message takes into account the current system culture.\n  remarks: \"The following table shows the initial property values for an instance of <xref:System.NullReferenceException>.  \\n  \\n|Property|Value|  \\n|--------------|-----------|  \\n|<xref:System.Exception.InnerException%2A>|`null`.|  \\n|<xref:System.Exception.Message%2A>|The localized error message string.|\"\n  syntax:\n    content: public NullReferenceException ();\n    parameters: []\n  overload: System.NullReferenceException.#ctor*\n  exceptions: []\n  version:\n  - netcore-1.0\n  - netcore-1.1\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-1.0\n  - netstandard-1.1\n  - netstandard-1.2\n  - netstandard-1.3\n  - netstandard-1.4\n  - netstandard-1.5\n  - netstandard-1.6\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  monikers:\n  - netcore-1.0\n  - netcore-1.1\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-1.0\n  - netstandard-1.1\n  - netstandard-1.2\n  - netstandard-1.3\n  - netstandard-1.4\n  - netstandard-1.5\n  - netstandard-1.6\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System/NullReferenceException.xml\n  ms.technology:\n  - dotnet-standard\n  author: rpetrusha\n  ms.author: ronpet\n  manager: wpickett\n- uid: System.NullReferenceException.#ctor(System.String)\n  commentId: M:System.NullReferenceException.#ctor(System.String)\n  id: '#ctor(System.String)'\n  parent: System.NullReferenceException\n  langs:\n  - csharp\n  name: NullReferenceException(String)\n  nameWithType: NullReferenceException.NullReferenceException(String)\n  fullName: NullReferenceException.NullReferenceException(String)\n  type: Constructor\n  assemblies:\n  - System.Runtime\n  - mscorlib\n  - netstandard\n  namespace: System\n  summary: Initializes a new instance of the <xref href=\"System.NullReferenceException\"></xref> class with a specified error message.\n  remarks: \"The following table shows the initial property values for an instance of <xref:System.NullReferenceException>.  \\n  \\n|Property|Value|  \\n|--------------|-----------|  \\n|<xref:System.Exception.InnerException%2A>|`null`.|  \\n|<xref:System.Exception.Message%2A>|The error message string.|\"\n  syntax:\n    content: public NullReferenceException (string message);\n    parameters:\n    - id: message\n      type: System.String\n      description: A <xref href=\"System.String\"></xref> that describes the error. The content of <code>message</code> is intended to be understood by humans. The caller of this constructor is required to ensure that this string has been localized for the current system culture.\n  overload: System.NullReferenceException.#ctor*\n  exceptions: []\n  version:\n  - netcore-1.0\n  - netcore-1.1\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-1.0\n  - netstandard-1.1\n  - netstandard-1.2\n  - netstandard-1.3\n  - netstandard-1.4\n  - netstandard-1.5\n  - netstandard-1.6\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  monikers:\n  - netcore-1.0\n  - netcore-1.1\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-1.0\n  - netstandard-1.1\n  - netstandard-1.2\n  - netstandard-1.3\n  - netstandard-1.4\n  - netstandard-1.5\n  - netstandard-1.6\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System/NullReferenceException.xml\n  ms.technology:\n  - dotnet-standard\n  author: rpetrusha\n  ms.author: ronpet\n  manager: wpickett\n- uid: System.NullReferenceException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  commentId: M:System.NullReferenceException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'\n  parent: System.NullReferenceException\n  langs:\n  - csharp\n  name: NullReferenceException(SerializationInfo, StreamingContext)\n  nameWithType: NullReferenceException.NullReferenceException(SerializationInfo, StreamingContext)\n  fullName: NullReferenceException.NullReferenceException(SerializationInfo, StreamingContext)\n  type: Constructor\n  assemblies:\n  - mscorlib\n  - netstandard\n  - System.Runtime\n  namespace: System\n  summary: Initializes a new instance of the <xref href=\"System.NullReferenceException\"></xref> class with serialized data.\n  remarks: This constructor is called during deserialization to reconstitute the exception object transmitted over a stream. For more information, see [XML and SOAP Serialization](~/docs/framework/serialization/xml-and-soap-serialization.md).\n  syntax:\n    content: protected NullReferenceException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);\n    parameters:\n    - id: info\n      type: System.Runtime.Serialization.SerializationInfo\n      description: The object that holds the serialized object data.\n    - id: context\n      type: System.Runtime.Serialization.StreamingContext\n      description: The contextual information about the source or destination.\n  overload: System.NullReferenceException.#ctor*\n  exceptions: []\n  version:\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  monikers:\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System/NullReferenceException.xml\n  ms.technology:\n  - dotnet-standard\n  author: rpetrusha\n  ms.author: ronpet\n  manager: wpickett\n- uid: System.NullReferenceException.#ctor(System.String,System.Exception)\n  commentId: M:System.NullReferenceException.#ctor(System.String,System.Exception)\n  id: '#ctor(System.String,System.Exception)'\n  parent: System.NullReferenceException\n  langs:\n  - csharp\n  name: NullReferenceException(String, Exception)\n  nameWithType: NullReferenceException.NullReferenceException(String, Exception)\n  fullName: NullReferenceException.NullReferenceException(String, Exception)\n  type: Constructor\n  assemblies:\n  - System.Runtime\n  - mscorlib\n  - netstandard\n  namespace: System\n  summary: Initializes a new instance of the <xref href=\"System.NullReferenceException\"></xref> class with a specified error message and a reference to the inner exception that is the cause of this exception.\n  remarks: \"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property. The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or `null` if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor.  \\n  \\n The following table shows the initial property values for an instance of <xref:System.NullReferenceException>.  \\n  \\n|Property|Value|  \\n|--------------|-----------|  \\n|<xref:System.Exception.InnerException%2A>|The inner exception reference.|  \\n|<xref:System.Exception.Message%2A>|The error message string.|\"\n  syntax:\n    content: public NullReferenceException (string message, Exception innerException);\n    parameters:\n    - id: message\n      type: System.String\n      description: The error message that explains the reason for the exception.\n    - id: innerException\n      type: System.Exception\n      description: The exception that is the cause of the current exception. If the <code>innerException</code> parameter is not `null`, the current exception is raised in a `catch` block that handles the inner exception.\n  overload: System.NullReferenceException.#ctor*\n  exceptions: []\n  version:\n  - netcore-1.0\n  - netcore-1.1\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-1.0\n  - netstandard-1.1\n  - netstandard-1.2\n  - netstandard-1.3\n  - netstandard-1.4\n  - netstandard-1.5\n  - netstandard-1.6\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  monikers:\n  - netcore-1.0\n  - netcore-1.1\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-1.0\n  - netstandard-1.1\n  - netstandard-1.2\n  - netstandard-1.3\n  - netstandard-1.4\n  - netstandard-1.5\n  - netstandard-1.6\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System/NullReferenceException.xml\n  ms.technology:\n  - dotnet-standard\n  author: rpetrusha\n  ms.author: ronpet\n  manager: wpickett\nreferences:\n- uid: System.Exception\n  parent: System\n  isExternal: false\n  name: Exception\n  nameWithType: Exception\n  fullName: System.Exception\n- uid: System.NullReferenceException.#ctor\n  parent: System.NullReferenceException\n  isExternal: false\n  name: NullReferenceException()\n  nameWithType: NullReferenceException.NullReferenceException()\n  fullName: NullReferenceException.NullReferenceException()\n- uid: System.NullReferenceException.#ctor(System.String)\n  parent: System.NullReferenceException\n  isExternal: false\n  name: NullReferenceException(String)\n  nameWithType: NullReferenceException.NullReferenceException(String)\n  fullName: NullReferenceException.NullReferenceException(String)\n- uid: System.String\n  parent: System\n  isExternal: false\n  name: String\n  nameWithType: String\n  fullName: System.String\n- uid: System.NullReferenceException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  parent: System.NullReferenceException\n  isExternal: false\n  name: NullReferenceException(SerializationInfo, StreamingContext)\n  nameWithType: NullReferenceException.NullReferenceException(SerializationInfo, StreamingContext)\n  fullName: NullReferenceException.NullReferenceException(SerializationInfo, StreamingContext)\n- uid: System.Runtime.Serialization.SerializationInfo\n  parent: System.Runtime.Serialization\n  isExternal: false\n  name: SerializationInfo\n  nameWithType: SerializationInfo\n  fullName: System.Runtime.Serialization.SerializationInfo\n- uid: System.Runtime.Serialization.StreamingContext\n  parent: System.Runtime.Serialization\n  isExternal: false\n  name: StreamingContext\n  nameWithType: StreamingContext\n  fullName: System.Runtime.Serialization.StreamingContext\n- uid: System.NullReferenceException.#ctor(System.String,System.Exception)\n  parent: System.NullReferenceException\n  isExternal: false\n  name: NullReferenceException(String, Exception)\n  nameWithType: NullReferenceException.NullReferenceException(String, Exception)\n  fullName: NullReferenceException.NullReferenceException(String, Exception)\n- uid: System.NullReferenceException.#ctor*\n  parent: System.NullReferenceException\n  isExternal: false\n  name: NullReferenceException\n  nameWithType: NullReferenceException.NullReferenceException\n  fullName: NullReferenceException.NullReferenceException\n  monikers:\n  - netcore-1.0\n  - netcore-1.1\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-1.0\n  - netstandard-1.1\n  - netstandard-1.2\n  - netstandard-1.3\n  - netstandard-1.4\n  - netstandard-1.5\n  - netstandard-1.6\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System/NullReferenceException.xml\n- uid: System.Object.Equals(System.Object)\n  parent: System.Object\n  isExternal: false\n  name: Equals(Object)\n  nameWithType: Object.Equals(Object)\n  fullName: Object.Equals(Object)\n- uid: System.Object.Equals(System.Object,System.Object)\n  parent: System.Object\n  isExternal: false\n  name: Equals(Object, Object)\n  nameWithType: Object.Equals(Object, Object)\n  fullName: Object.Equals(Object, Object)\n- uid: System.Object.GetHashCode\n  parent: System.Object\n  isExternal: false\n  name: GetHashCode()\n  nameWithType: Object.GetHashCode()\n  fullName: Object.GetHashCode()\n- uid: System.Exception.GetType\n  parent: System.Exception\n  isExternal: false\n  name: GetType()\n  nameWithType: Exception.GetType()\n  fullName: Exception.GetType()\n- uid: System.Object.MemberwiseClone\n  parent: System.Object\n  isExternal: false\n  name: MemberwiseClone()\n  nameWithType: Object.MemberwiseClone()\n  fullName: Object.MemberwiseClone()\n- uid: System.Object.ReferenceEquals(System.Object,System.Object)\n  parent: System.Object\n  isExternal: false\n  name: ReferenceEquals(Object, Object)\n  nameWithType: Object.ReferenceEquals(Object, Object)\n  fullName: Object.ReferenceEquals(Object, Object)\n- uid: System.Exception.ToString\n  parent: System.Exception\n  isExternal: false\n  name: ToString()\n  nameWithType: Exception.ToString()\n  fullName: Exception.ToString()\n- uid: System.Exception.Data\n  parent: System.Exception\n  isExternal: false\n  name: Data\n  nameWithType: Exception.Data\n  fullName: Exception.Data\n- uid: System.Exception.GetBaseException\n  parent: System.Exception\n  isExternal: false\n  name: GetBaseException()\n  nameWithType: Exception.GetBaseException()\n  fullName: Exception.GetBaseException()\n- uid: System.Exception.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  parent: System.Exception\n  isExternal: false\n  name: GetObjectData(SerializationInfo, StreamingContext)\n  nameWithType: Exception.GetObjectData(SerializationInfo, StreamingContext)\n  fullName: Exception.GetObjectData(SerializationInfo, StreamingContext)\n- uid: System.Exception.HelpLink\n  parent: System.Exception\n  isExternal: false\n  name: HelpLink\n  nameWithType: Exception.HelpLink\n  fullName: Exception.HelpLink\n- uid: System.Exception.HResult\n  parent: System.Exception\n  isExternal: false\n  name: HResult\n  nameWithType: Exception.HResult\n  fullName: Exception.HResult\n- uid: System.Exception.InnerException\n  parent: System.Exception\n  isExternal: false\n  name: InnerException\n  nameWithType: Exception.InnerException\n  fullName: Exception.InnerException\n- uid: System.Exception.Message\n  parent: System.Exception\n  isExternal: false\n  name: Message\n  nameWithType: Exception.Message\n  fullName: Exception.Message\n- uid: System.Exception.SerializeObjectState\n  parent: System.Exception\n  isExternal: false\n  name: SerializeObjectState\n  nameWithType: Exception.SerializeObjectState\n  fullName: Exception.SerializeObjectState\n- uid: System.Exception.Source\n  parent: System.Exception\n  isExternal: false\n  name: Source\n  nameWithType: Exception.Source\n  fullName: Exception.Source\n- uid: System.Exception.StackTrace\n  parent: System.Exception\n  isExternal: false\n  name: StackTrace\n  nameWithType: Exception.StackTrace\n  fullName: Exception.StackTrace\n- uid: System.Exception.TargetSite\n  parent: System.Exception\n  isExternal: false\n  name: TargetSite\n  nameWithType: Exception.TargetSite\n  fullName: Exception.TargetSite\n"}