{"nodes":[{"content":"The exception that is thrown when the workflow runtime engine attempts to load a workflow instance that is currently loaded by another workflow runtime engine instance. Additionally, this exception is thrown when the workflow runtime engine attempts to save a workflow after the ownership timeout that was specified while loading the workflow has expired.","nodes":[{"pos":[0,355],"content":"The exception that is thrown when the workflow runtime engine attempts to load a workflow instance that is currently loaded by another workflow runtime engine instance. Additionally, this exception is thrown when the workflow runtime engine attempts to save a workflow after the ownership timeout that was specified while loading the workflow has expired.","nodes":[{"content":"The exception that is thrown when the workflow runtime engine attempts to load a workflow instance that is currently loaded by another workflow runtime engine instance. Additionally, this exception is thrown when the workflow runtime engine attempts to save a workflow after the ownership timeout that was specified while loading the workflow has expired.","pos":[0,355],"nodes":[{"content":"The exception that is thrown when the workflow runtime engine attempts to load a workflow instance that is currently loaded by another workflow runtime engine instance.","pos":[0,168]},{"content":"Additionally, this exception is thrown when the workflow runtime engine attempts to save a workflow after the ownership timeout that was specified while loading the workflow has expired.","pos":[169,355]}]}]}],"pos":[1351,1707],"yaml":true},{"content":"> [!NOTE]\n>  [!INCLUDE[DeprecatedContent](~/includes/deprecatedcontent-md.md)]  \n  \n The <xref:System.Workflow.Runtime.WorkflowOwnershipException> is used by persistence services which support the capability for multiple applications to access the same database. In such an environment, an instance of the workflow runtime may try to load a workflow that is already loaded by another instance of the workflow runtime engine. For example, the <xref:System.Workflow.Runtime.Hosting.SqlWorkflowPersistenceService> class throws the <xref:System.Workflow.Runtime.WorkflowOwnershipException> when this situation occurs.  \n  \n If you implement a persistence service that throws the <xref:System.Workflow.Runtime.WorkflowOwnershipException> you should provide the <xref:System.Guid> of the workflow instance for which the exception occurs by using an appropriate constructor for the class or setting the <xref:System.Workflow.Runtime.WorkflowOwnershipException.InstanceId%2A> property before you throw the exception.","nodes":[{"pos":[2,78],"content":"[!NOTE]\n [!INCLUDE[DeprecatedContent](~/includes/deprecatedcontent-md.md)]","leadings":["","> "],"nodes":[]},{"pos":[85,613],"content":"The <xref:System.Workflow.Runtime.WorkflowOwnershipException> is used by persistence services which support the capability for multiple applications to access the same database. In such an environment, an instance of the workflow runtime may try to load a workflow that is already loaded by another instance of the workflow runtime engine. For example, the <xref:System.Workflow.Runtime.Hosting.SqlWorkflowPersistenceService> class throws the <xref:System.Workflow.Runtime.WorkflowOwnershipException> when this situation occurs.","nodes":[{"content":"The <xref:System.Workflow.Runtime.WorkflowOwnershipException> is used by persistence services which support the capability for multiple applications to access the same database. In such an environment, an instance of the workflow runtime may try to load a workflow that is already loaded by another instance of the workflow runtime engine. For example, the <xref:System.Workflow.Runtime.Hosting.SqlWorkflowPersistenceService> class throws the <xref:System.Workflow.Runtime.WorkflowOwnershipException> when this situation occurs.","pos":[0,528],"nodes":[{"content":"The <ph id=\"ph1\">&lt;xref:System.Workflow.Runtime.WorkflowOwnershipException&gt;</ph> is used by persistence services which support the capability for multiple applications to access the same database.","pos":[0,177],"source":"The <xref:System.Workflow.Runtime.WorkflowOwnershipException> is used by persistence services which support the capability for multiple applications to access the same database."},{"content":"In such an environment, an instance of the workflow runtime may try to load a workflow that is already loaded by another instance of the workflow runtime engine.","pos":[178,339]},{"content":"For example, the <ph id=\"ph1\">&lt;xref:System.Workflow.Runtime.Hosting.SqlWorkflowPersistenceService&gt;</ph> class throws the <ph id=\"ph2\">&lt;xref:System.Workflow.Runtime.WorkflowOwnershipException&gt;</ph> when this situation occurs.","pos":[340,528],"source":" For example, the <xref:System.Workflow.Runtime.Hosting.SqlWorkflowPersistenceService> class throws the <xref:System.Workflow.Runtime.WorkflowOwnershipException> when this situation occurs."}]}]},{"pos":[620,1008],"content":"If you implement a persistence service that throws the <xref:System.Workflow.Runtime.WorkflowOwnershipException> you should provide the <xref:System.Guid> of the workflow instance for which the exception occurs by using an appropriate constructor for the class or setting the <xref:System.Workflow.Runtime.WorkflowOwnershipException.InstanceId%2A> property before you throw the exception.","nodes":[{"content":"If you implement a persistence service that throws the <ph id=\"ph1\">&lt;xref:System.Workflow.Runtime.WorkflowOwnershipException&gt;</ph> you should provide the <ph id=\"ph2\">&lt;xref:System.Guid&gt;</ph> of the workflow instance for which the exception occurs by using an appropriate constructor for the class or setting the <ph id=\"ph3\">&lt;xref:System.Workflow.Runtime.WorkflowOwnershipException.InstanceId%2A&gt;</ph> property before you throw the exception.","pos":[0,388],"source":"If you implement a persistence service that throws the <xref:System.Workflow.Runtime.WorkflowOwnershipException> you should provide the <xref:System.Guid> of the workflow instance for which the exception occurs by using an appropriate constructor for the class or setting the <xref:System.Workflow.Runtime.WorkflowOwnershipException.InstanceId%2A> property before you throw the exception."}]}],"pos":[1718,2734],"yaml":true,"extradata":"MT"},{"content":"Initializes a new instance of the <xref href=\"System.Workflow.Runtime.WorkflowOwnershipException\"></xref> class.","nodes":[{"pos":[0,112],"content":"Initializes a new instance of the <ph id=\"ph1\">&lt;xref href=\"System.Workflow.Runtime.WorkflowOwnershipException\"&gt;&lt;/xref&gt;</ph> class.","source":"Initializes a new instance of the <xref href=\"System.Workflow.Runtime.WorkflowOwnershipException\"></xref> class."}],"pos":[4719,4832],"yaml":true},{"content":"This constructor initializes the <xref:System.Exception.Message%2A> property of the new instance to a system-supplied message that describes the error and takes into account the current system culture.  \n  \n The following table shows the initial property values for an instance of <xref:System.Workflow.Runtime.WorkflowOwnershipException>.  \n  \n|Property|Value|  \n|--------------|-----------|  \n|<xref:System.Exception.InnerException%2A>|A null reference (`Nothing` in Visual Basic)|  \n|<xref:System.Exception.Message%2A>|A system-supplied localized description.|  \n|<xref:System.Workflow.Runtime.WorkflowOwnershipException.InstanceId%2A>|An empty <xref:System.Guid>.|","nodes":[{"pos":[0,201],"content":"This constructor initializes the <xref:System.Exception.Message%2A> property of the new instance to a system-supplied message that describes the error and takes into account the current system culture.","nodes":[{"content":"This constructor initializes the <ph id=\"ph1\">&lt;xref:System.Exception.Message%2A&gt;</ph> property of the new instance to a system-supplied message that describes the error and takes into account the current system culture.","pos":[0,201],"source":"This constructor initializes the <xref:System.Exception.Message%2A> property of the new instance to a system-supplied message that describes the error and takes into account the current system culture."}]},{"pos":[208,339],"content":"The following table shows the initial property values for an instance of <xref:System.Workflow.Runtime.WorkflowOwnershipException>.","nodes":[{"content":"The following table shows the initial property values for an instance of <ph id=\"ph1\">&lt;xref:System.Workflow.Runtime.WorkflowOwnershipException&gt;</ph>.","pos":[0,131],"source":"The following table shows the initial property values for an instance of <xref:System.Workflow.Runtime.WorkflowOwnershipException>."}]},{"pos":[346,354],"content":"Property","nodes":[{"content":"Property","pos":[0,8]}]},{"pos":[355,360],"content":"Value","nodes":[{"content":"Value","pos":[0,5]}]},{"pos":[396,437],"content":"<xref:System.Exception.InnerException%2A>","nodes":[]},{"pos":[438,482],"content":"A null reference (<ph id=\"ph1\">`Nothing`</ph> in Visual Basic)","source":"A null reference (`Nothing` in Visual Basic)"},{"pos":[487,521],"content":"<xref:System.Exception.Message%2A>","nodes":[]},{"pos":[522,562],"content":"A system-supplied localized description.","nodes":[{"content":"A system-supplied localized description.","pos":[0,40]}]},{"pos":[567,638],"content":"<xref:System.Workflow.Runtime.WorkflowOwnershipException.InstanceId%2A>","nodes":[]},{"pos":[639,667],"content":"An empty <xref:System.Guid>.","nodes":[{"content":"An empty <ph id=\"ph1\">&lt;xref:System.Guid&gt;</ph>.","pos":[0,28],"source":"An empty <xref:System.Guid>."}]}],"pos":[4843,5522],"yaml":true,"extradata":"MT"},{"content":"Initializes a new instance of the <xref href=\"System.Workflow.Runtime.WorkflowOwnershipException\"></xref> class by using a specified workflow instance <xref href=\"System.Guid\"></xref>.","nodes":[{"pos":[0,184],"content":"Initializes a new instance of the <ph id=\"ph1\">&lt;xref href=\"System.Workflow.Runtime.WorkflowOwnershipException\"&gt;&lt;/xref&gt;</ph> class by using a specified workflow instance <ph id=\"ph2\">&lt;xref href=\"System.Guid\"&gt;&lt;/xref&gt;</ph>.","source":"Initializes a new instance of the <xref href=\"System.Workflow.Runtime.WorkflowOwnershipException\"></xref> class by using a specified workflow instance <xref href=\"System.Guid\"></xref>."}],"pos":[6767,6952],"yaml":true},{"content":"`instanceId` is equivalent to the <xref:System.Workflow.Runtime.WorkflowInstance.InstanceId%2A?displayProperty=fullName> property of the workflow instance. The <xref:System.Exception.Message%2A> property of the new instance is initialized to a system-supplied message that describes the error and takes into account the current system culture.  \n  \n The following table shows the initial property values for an instance of <xref:System.Workflow.Runtime.WorkflowOwnershipException>.  \n  \n|Property|Value|  \n|--------------|-----------|  \n|<xref:System.Exception.InnerException%2A>|A null reference (`Nothing` in Visual Basic)|  \n|<xref:System.Exception.Message%2A>|A system-supplied localized description.|  \n|<xref:System.Workflow.Runtime.WorkflowOwnershipException.InstanceId%2A>|The <xref:System.Guid> of the workflow instance, specified by `instanceId`, for which this exception occurred.|","nodes":[{"pos":[0,343],"content":"`instanceId` is equivalent to the <xref:System.Workflow.Runtime.WorkflowInstance.InstanceId%2A?displayProperty=fullName> property of the workflow instance. The <xref:System.Exception.Message%2A> property of the new instance is initialized to a system-supplied message that describes the error and takes into account the current system culture.","nodes":[{"content":"<ph id=\"ph1\">`instanceId`</ph> is equivalent to the <ph id=\"ph2\">&lt;xref:System.Workflow.Runtime.WorkflowInstance.InstanceId%2A?displayProperty=fullName&gt;</ph> property of the workflow instance.","pos":[0,155],"source":"`instanceId` is equivalent to the <xref:System.Workflow.Runtime.WorkflowInstance.InstanceId%2A?displayProperty=fullName> property of the workflow instance."},{"content":"The <ph id=\"ph1\">&lt;xref:System.Exception.Message%2A&gt;</ph> property of the new instance is initialized to a system-supplied message that describes the error and takes into account the current system culture.","pos":[156,343],"source":" The <xref:System.Exception.Message%2A> property of the new instance is initialized to a system-supplied message that describes the error and takes into account the current system culture."}]},{"pos":[350,481],"content":"The following table shows the initial property values for an instance of <xref:System.Workflow.Runtime.WorkflowOwnershipException>.","nodes":[{"content":"The following table shows the initial property values for an instance of <ph id=\"ph1\">&lt;xref:System.Workflow.Runtime.WorkflowOwnershipException&gt;</ph>.","pos":[0,131],"source":"The following table shows the initial property values for an instance of <xref:System.Workflow.Runtime.WorkflowOwnershipException>."}]},{"pos":[488,496],"content":"Property","nodes":[{"content":"Property","pos":[0,8]}]},{"pos":[497,502],"content":"Value","nodes":[{"content":"Value","pos":[0,5]}]},{"pos":[538,579],"content":"<xref:System.Exception.InnerException%2A>","nodes":[]},{"pos":[580,624],"content":"A null reference (<ph id=\"ph1\">`Nothing`</ph> in Visual Basic)","source":"A null reference (`Nothing` in Visual Basic)"},{"pos":[629,663],"content":"<xref:System.Exception.Message%2A>","nodes":[]},{"pos":[664,704],"content":"A system-supplied localized description.","nodes":[{"content":"A system-supplied localized description.","pos":[0,40]}]},{"pos":[709,780],"content":"<xref:System.Workflow.Runtime.WorkflowOwnershipException.InstanceId%2A>","nodes":[]},{"pos":[781,891],"content":"The <ph id=\"ph1\">&lt;xref:System.Guid&gt;</ph> of the workflow instance, specified by <ph id=\"ph2\">`instanceId`</ph>, for which this exception occurred.","source":"The <xref:System.Guid> of the workflow instance, specified by `instanceId`, for which this exception occurred."}],"pos":[6963,7866],"yaml":true,"extradata":"MT"},{"content":"The <xref href=\"System.Guid\"></xref> of the workflow instance for which this exception occurred.","nodes":[{"pos":[0,96],"content":"The <ph id=\"ph1\">&lt;xref href=\"System.Guid\"&gt;&lt;/xref&gt;</ph> of the workflow instance for which this exception occurred.","source":"The <xref href=\"System.Guid\"></xref> of the workflow instance for which this exception occurred."}],"pos":[8022,8119],"yaml":true},{"content":"Initializes a new instance of the <xref href=\"System.Workflow.Runtime.WorkflowOwnershipException\"></xref> class by using a specified error message.","nodes":[{"pos":[0,147],"content":"Initializes a new instance of the <ph id=\"ph1\">&lt;xref href=\"System.Workflow.Runtime.WorkflowOwnershipException\"&gt;&lt;/xref&gt;</ph> class by using a specified error message.","source":"Initializes a new instance of the <xref href=\"System.Workflow.Runtime.WorkflowOwnershipException\"></xref> class by using a specified error message."}],"pos":[9296,9444],"yaml":true},{"content":"The content of the `message` parameter is intended to be understood by humans. The caller of this constructor is required to ensure that this string has been localized for the current system culture. If you use this constructor you should explicitly set <xref:System.Workflow.Runtime.WorkflowOwnershipException.InstanceId%2A> before you throw the exception.  \n  \n The following table shows the initial property values for an instance of <xref:System.Workflow.Runtime.WorkflowOwnershipException>.  \n  \n|Property|Value|  \n|--------------|-----------|  \n|<xref:System.Exception.InnerException%2A>|A null reference (`Nothing` in Visual Basic).|  \n|<xref:System.Exception.Message%2A>|The error message string.|  \n|<xref:System.Workflow.Runtime.WorkflowOwnershipException.InstanceId%2A>|An empty <xref:System.Guid>.|","nodes":[{"pos":[0,357],"content":"The content of the `message` parameter is intended to be understood by humans. The caller of this constructor is required to ensure that this string has been localized for the current system culture. If you use this constructor you should explicitly set <xref:System.Workflow.Runtime.WorkflowOwnershipException.InstanceId%2A> before you throw the exception.","nodes":[{"content":"The content of the <ph id=\"ph1\">`message`</ph> parameter is intended to be understood by humans.","pos":[0,78],"source":"The content of the `message` parameter is intended to be understood by humans."},{"content":"The caller of this constructor is required to ensure that this string has been localized for the current system culture.","pos":[79,199]},{"content":"If you use this constructor you should explicitly set <ph id=\"ph1\">&lt;xref:System.Workflow.Runtime.WorkflowOwnershipException.InstanceId%2A&gt;</ph> before you throw the exception.","pos":[200,357],"source":" If you use this constructor you should explicitly set <xref:System.Workflow.Runtime.WorkflowOwnershipException.InstanceId%2A> before you throw the exception."}]},{"pos":[364,495],"content":"The following table shows the initial property values for an instance of <xref:System.Workflow.Runtime.WorkflowOwnershipException>.","nodes":[{"content":"The following table shows the initial property values for an instance of <ph id=\"ph1\">&lt;xref:System.Workflow.Runtime.WorkflowOwnershipException&gt;</ph>.","pos":[0,131],"source":"The following table shows the initial property values for an instance of <xref:System.Workflow.Runtime.WorkflowOwnershipException>."}]},{"pos":[502,510],"content":"Property","nodes":[{"content":"Property","pos":[0,8]}]},{"pos":[511,516],"content":"Value","nodes":[{"content":"Value","pos":[0,5]}]},{"pos":[552,593],"content":"<xref:System.Exception.InnerException%2A>","nodes":[]},{"pos":[594,639],"content":"A null reference (<ph id=\"ph1\">`Nothing`</ph> in Visual Basic).","source":"A null reference (`Nothing` in Visual Basic)."},{"pos":[644,678],"content":"<xref:System.Exception.Message%2A>","nodes":[]},{"pos":[679,704],"content":"The error message string.","nodes":[{"content":"The error message string.","pos":[0,25]}]},{"pos":[709,780],"content":"<xref:System.Workflow.Runtime.WorkflowOwnershipException.InstanceId%2A>","nodes":[]},{"pos":[781,809],"content":"An empty <xref:System.Guid>.","nodes":[{"content":"An empty <ph id=\"ph1\">&lt;xref:System.Guid&gt;</ph>.","pos":[0,28],"source":"An empty <xref:System.Guid>."}]}],"pos":[9455,10276],"yaml":true,"extradata":"MT"},{"content":"The message that describes the error.","nodes":[{"pos":[0,37],"content":"The message that describes the error.","nodes":[{"content":"The message that describes the error.","pos":[0,37]}]}],"pos":[10430,10468],"yaml":true},{"content":"Initializes a new instance of the <xref href=\"System.Workflow.Runtime.WorkflowOwnershipException\"></xref> class by using a specified workflow instance <xref href=\"System.Guid\"></xref> and a specified error message.","nodes":[{"pos":[0,214],"content":"Initializes a new instance of the <ph id=\"ph1\">&lt;xref href=\"System.Workflow.Runtime.WorkflowOwnershipException\"&gt;&lt;/xref&gt;</ph> class by using a specified workflow instance <ph id=\"ph2\">&lt;xref href=\"System.Guid\"&gt;&lt;/xref&gt;</ph> and a specified error message.","source":"Initializes a new instance of the <xref href=\"System.Workflow.Runtime.WorkflowOwnershipException\"></xref> class by using a specified workflow instance <xref href=\"System.Guid\"></xref> and a specified error message."}],"pos":[11699,11914],"yaml":true},{"content":"`instanceId` is equivalent to the <xref:System.Workflow.Runtime.WorkflowInstance.InstanceId%2A?displayProperty=fullName> property of the workflow instance. The content of the `message` parameter is intended to be understood by humans. The caller of this constructor is required to ensure that this string has been localized for the current system culture.  \n  \n The following table shows the initial property values for an instance of <xref:System.Workflow.Runtime.WorkflowOwnershipException>.  \n  \n|Property|Value|  \n|--------------|-----------|  \n|<xref:System.Exception.InnerException%2A>|A null reference (`Nothing` in Visual Basic)|  \n|<xref:System.Exception.Message%2A>|The error message string.|  \n|<xref:System.Workflow.Runtime.WorkflowOwnershipException.InstanceId%2A>|The <xref:System.Guid> of the workflow instance, specified by `instanceId`, for which this exception occurred.|","nodes":[{"pos":[0,355],"content":"`instanceId` is equivalent to the <xref:System.Workflow.Runtime.WorkflowInstance.InstanceId%2A?displayProperty=fullName> property of the workflow instance. The content of the `message` parameter is intended to be understood by humans. The caller of this constructor is required to ensure that this string has been localized for the current system culture.","nodes":[{"content":"<ph id=\"ph1\">`instanceId`</ph> is equivalent to the <ph id=\"ph2\">&lt;xref:System.Workflow.Runtime.WorkflowInstance.InstanceId%2A?displayProperty=fullName&gt;</ph> property of the workflow instance.","pos":[0,155],"source":"`instanceId` is equivalent to the <xref:System.Workflow.Runtime.WorkflowInstance.InstanceId%2A?displayProperty=fullName> property of the workflow instance."},{"content":"The content of the <ph id=\"ph1\">`message`</ph> parameter is intended to be understood by humans.","pos":[156,234],"source":" The content of the `message` parameter is intended to be understood by humans."},{"content":"The caller of this constructor is required to ensure that this string has been localized for the current system culture.","pos":[235,355]}]},{"pos":[362,493],"content":"The following table shows the initial property values for an instance of <xref:System.Workflow.Runtime.WorkflowOwnershipException>.","nodes":[{"content":"The following table shows the initial property values for an instance of <ph id=\"ph1\">&lt;xref:System.Workflow.Runtime.WorkflowOwnershipException&gt;</ph>.","pos":[0,131],"source":"The following table shows the initial property values for an instance of <xref:System.Workflow.Runtime.WorkflowOwnershipException>."}]},{"pos":[500,508],"content":"Property","nodes":[{"content":"Property","pos":[0,8]}]},{"pos":[509,514],"content":"Value","nodes":[{"content":"Value","pos":[0,5]}]},{"pos":[550,591],"content":"<xref:System.Exception.InnerException%2A>","nodes":[]},{"pos":[592,636],"content":"A null reference (<ph id=\"ph1\">`Nothing`</ph> in Visual Basic)","source":"A null reference (`Nothing` in Visual Basic)"},{"pos":[641,675],"content":"<xref:System.Exception.Message%2A>","nodes":[]},{"pos":[676,701],"content":"The error message string.","nodes":[{"content":"The error message string.","pos":[0,25]}]},{"pos":[706,777],"content":"<xref:System.Workflow.Runtime.WorkflowOwnershipException.InstanceId%2A>","nodes":[]},{"pos":[778,888],"content":"The <ph id=\"ph1\">&lt;xref:System.Guid&gt;</ph> of the workflow instance, specified by <ph id=\"ph2\">`instanceId`</ph>, for which this exception occurred.","source":"The <xref:System.Guid> of the workflow instance, specified by `instanceId`, for which this exception occurred."}],"pos":[11925,12825],"yaml":true,"extradata":"MT"},{"content":"The <xref href=\"System.Guid\"></xref> of the workflow instance for which this exception occurred.","nodes":[{"pos":[0,96],"content":"The <ph id=\"ph1\">&lt;xref href=\"System.Guid\"&gt;&lt;/xref&gt;</ph> of the workflow instance for which this exception occurred.","source":"The <xref href=\"System.Guid\"></xref> of the workflow instance for which this exception occurred."}],"pos":[12997,13094],"yaml":true},{"content":"The message that describes the error.","nodes":[{"pos":[0,37],"content":"The message that describes the error.","nodes":[{"content":"The message that describes the error.","pos":[0,37]}]}],"pos":[13157,13195],"yaml":true},{"content":"Initializes a new instance of the WorkflowOwnershipException class with serialized data.","nodes":[{"pos":[0,88],"content":"Initializes a new instance of the WorkflowOwnershipException class with serialized data.","nodes":[{"content":"Initializes a new instance of the WorkflowOwnershipException class with serialized data.","pos":[0,88]}]}],"pos":[14696,14785],"yaml":true},{"content":"This constructor is called during serialization to reconstitute the exception object transmitted over a stream.  \n  \n For more information see XML and SOAP Serialization.","nodes":[{"pos":[0,111],"content":"This constructor is called during serialization to reconstitute the exception object transmitted over a stream.","nodes":[{"content":"This constructor is called during serialization to reconstitute the exception object transmitted over a stream.","pos":[0,111]}]},{"pos":[118,170],"content":"For more information see XML and SOAP Serialization.","nodes":[{"content":"For more information see XML and SOAP Serialization.","pos":[0,52]}]}],"pos":[14796,14971],"yaml":true,"extradata":"MT"},{"content":"A <xref href=\"System.Runtime.Serialization.SerializationInfo\"></xref> that holds the serialized object data about the exception being thrown.","nodes":[{"pos":[0,141],"content":"A <ph id=\"ph1\">&lt;xref href=\"System.Runtime.Serialization.SerializationInfo\"&gt;&lt;/xref&gt;</ph> that holds the serialized object data about the exception being thrown.","source":"A <xref href=\"System.Runtime.Serialization.SerializationInfo\"></xref> that holds the serialized object data about the exception being thrown."}],"pos":[15250,15392],"yaml":true},{"content":"A <xref href=\"System.Runtime.Serialization.StreamingContext\"></xref> that contains contextual information about the source or destination.","nodes":[{"pos":[0,138],"content":"A <ph id=\"ph1\">&lt;xref href=\"System.Runtime.Serialization.StreamingContext\"&gt;&lt;/xref&gt;</ph> that contains contextual information about the source or destination.","source":"A <xref href=\"System.Runtime.Serialization.StreamingContext\"></xref> that contains contextual information about the source or destination."}],"pos":[15487,15626],"yaml":true},{"content":"Initializes a new instance of the <xref href=\"System.Workflow.Runtime.WorkflowOwnershipException\"></xref> class by using a specified error message and a reference to the inner exception that is the cause of this exception.","nodes":[{"pos":[0,222],"content":"Initializes a new instance of the <ph id=\"ph1\">&lt;xref href=\"System.Workflow.Runtime.WorkflowOwnershipException\"&gt;&lt;/xref&gt;</ph> class by using a specified error message and a reference to the inner exception that is the cause of this exception.","source":"Initializes a new instance of the <xref href=\"System.Workflow.Runtime.WorkflowOwnershipException\"></xref> class by using a specified error message and a reference to the inner exception that is the cause of this exception."}],"pos":[16887,17110],"yaml":true},{"content":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property. The <xref:System.Exception.InnerException%2A> property returns the same value that is supplied to the constructor or a null reference (Nothing in Visual Basic) if the `innerException` parameter does not supply the inner exception value to the constructor. The content of the `message` parameter is intended to be understood by humans. The caller of this constructor is required to ensure that this string has been localized for the current system culture. If you use this constructor you should explicitly set <xref:System.Workflow.Runtime.WorkflowOwnershipException.InstanceId%2A> before you throw the exception.  \n  \n The following table shows the initial property values for an instance of <xref:System.Workflow.Runtime.WorkflowOwnershipException>.  \n  \n|Property|Value|  \n|--------------|-----------|  \n|<xref:System.Exception.InnerException%2A>|The inner exception reference.|  \n|<xref:System.Exception.Message%2A>|The error message string.|  \n|<xref:System.Workflow.Runtime.WorkflowOwnershipException.InstanceId%2A>|An empty <xref:System.Guid>.|","nodes":[{"pos":[0,796],"content":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property. The <xref:System.Exception.InnerException%2A> property returns the same value that is supplied to the constructor or a null reference (Nothing in Visual Basic) if the `innerException` parameter does not supply the inner exception value to the constructor. The content of the `message` parameter is intended to be understood by humans. The caller of this constructor is required to ensure that this string has been localized for the current system culture. If you use this constructor you should explicitly set <xref:System.Workflow.Runtime.WorkflowOwnershipException.InstanceId%2A> before you throw the exception.","nodes":[{"content":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <ph id=\"ph1\">&lt;xref:System.Exception.InnerException%2A&gt;</ph> property.","pos":[0,182],"source":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property."},{"content":"The <ph id=\"ph1\">&lt;xref:System.Exception.InnerException%2A&gt;</ph> property returns the same value that is supplied to the constructor or a null reference (Nothing in Visual Basic) if the <ph id=\"ph2\">`innerException`</ph> parameter does not supply the inner exception value to the constructor.","pos":[183,438],"source":" The <xref:System.Exception.InnerException%2A> property returns the same value that is supplied to the constructor or a null reference (Nothing in Visual Basic) if the `innerException` parameter does not supply the inner exception value to the constructor."},{"content":"The content of the <ph id=\"ph1\">`message`</ph> parameter is intended to be understood by humans.","pos":[439,517],"source":" The content of the `message` parameter is intended to be understood by humans."},{"content":"The caller of this constructor is required to ensure that this string has been localized for the current system culture.","pos":[518,638]},{"content":"If you use this constructor you should explicitly set <ph id=\"ph1\">&lt;xref:System.Workflow.Runtime.WorkflowOwnershipException.InstanceId%2A&gt;</ph> before you throw the exception.","pos":[639,796],"source":" If you use this constructor you should explicitly set <xref:System.Workflow.Runtime.WorkflowOwnershipException.InstanceId%2A> before you throw the exception."}]},{"pos":[803,934],"content":"The following table shows the initial property values for an instance of <xref:System.Workflow.Runtime.WorkflowOwnershipException>.","nodes":[{"content":"The following table shows the initial property values for an instance of <ph id=\"ph1\">&lt;xref:System.Workflow.Runtime.WorkflowOwnershipException&gt;</ph>.","pos":[0,131],"source":"The following table shows the initial property values for an instance of <xref:System.Workflow.Runtime.WorkflowOwnershipException>."}]},{"pos":[941,949],"content":"Property","nodes":[{"content":"Property","pos":[0,8]}]},{"pos":[950,955],"content":"Value","nodes":[{"content":"Value","pos":[0,5]}]},{"pos":[991,1032],"content":"<xref:System.Exception.InnerException%2A>","nodes":[]},{"pos":[1033,1063],"content":"The inner exception reference.","nodes":[{"content":"The inner exception reference.","pos":[0,30]}]},{"pos":[1068,1102],"content":"<xref:System.Exception.Message%2A>","nodes":[]},{"pos":[1103,1128],"content":"The error message string.","nodes":[{"content":"The error message string.","pos":[0,25]}]},{"pos":[1133,1204],"content":"<xref:System.Workflow.Runtime.WorkflowOwnershipException.InstanceId%2A>","nodes":[]},{"pos":[1205,1233],"content":"An empty <xref:System.Guid>.","nodes":[{"content":"An empty <ph id=\"ph1\">&lt;xref:System.Guid&gt;</ph>.","pos":[0,28],"source":"An empty <xref:System.Guid>."}]}],"pos":[17121,18366],"yaml":true,"extradata":"MT"},{"content":"The message that describes the error.","nodes":[{"pos":[0,37],"content":"The message that describes the error.","nodes":[{"content":"The message that describes the error.","pos":[0,37]}]}],"pos":[18546,18584],"yaml":true},{"content":"The exception that is the cause of the current exception. If the <code>innerException</code> parameter is not a null reference (`Nothing` in Visual Basic), the current exception is raised in a catch block that handles the inner exception.","nodes":[{"pos":[0,238],"content":"The exception that is the cause of the current exception. If the <code>innerException</code> parameter is not a null reference (`Nothing` in Visual Basic), the current exception is raised in a catch block that handles the inner exception.","nodes":[{"content":"The exception that is the cause of the current exception.","pos":[0,57]},{"content":"If the <bpt id=\"p1\">&lt;code&gt;</bpt><ph id=\"ph1\">innerException</ph><ept id=\"p1\">&lt;/code&gt;</ept> parameter is not a null reference (<ph id=\"ph2\">`Nothing`</ph> in Visual Basic), the current exception is raised in a catch block that handles the inner exception.","pos":[58,238],"source":" If the <code>innerException</code> parameter is not a null reference (`Nothing` in Visual Basic), the current exception is raised in a catch block that handles the inner exception."}]}],"pos":[18657,18896],"yaml":true},{"content":"Initializes a new instance of the <xref href=\"System.Workflow.Runtime.WorkflowOwnershipException\"></xref> class by using a specified workflow instance <xref href=\"System.Guid\"></xref>, a specified error message, and a reference to the inner exception that is the cause of this exception.","nodes":[{"pos":[0,287],"content":"Initializes a new instance of the <ph id=\"ph1\">&lt;xref href=\"System.Workflow.Runtime.WorkflowOwnershipException\"&gt;&lt;/xref&gt;</ph> class by using a specified workflow instance <ph id=\"ph2\">&lt;xref href=\"System.Guid\"&gt;&lt;/xref&gt;</ph>, a specified error message, and a reference to the inner exception that is the cause of this exception.","source":"Initializes a new instance of the <xref href=\"System.Workflow.Runtime.WorkflowOwnershipException\"></xref> class by using a specified workflow instance <xref href=\"System.Guid\"></xref>, a specified error message, and a reference to the inner exception that is the cause of this exception."}],"pos":[20211,20499],"yaml":true},{"content":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property. The <xref:System.Exception.InnerException%2A> property returns the same value that is supplied to the constructor or a null reference (Nothing in Visual Basic) if the `innerException` parameter does not supply the inner exception value to the constructor.  \n  \n `instanceId` is equivalent to the <xref:System.Workflow.Runtime.WorkflowInstance.InstanceId%2A?displayProperty=fullName> property of the workflow instance. The content of the `message` parameter is intended to be understood by humans. The caller of this constructor is required to ensure that this string has been localized for the current system culture.  \n  \n The following table shows the initial property values for an instance of <xref:System.Workflow.Runtime.WorkflowOwnershipException>.  \n  \n|Property|Value|  \n|--------------|-----------|  \n|<xref:System.Exception.InnerException%2A>|The inner exception reference.|  \n|<xref:System.Exception.Message%2A>|The error message string.|  \n|<xref:System.Workflow.Runtime.WorkflowOwnershipException.InstanceId%2A>|The <xref:System.Guid> of the workflow instance, specified by `instanceId`, for which this exception occurred.|","nodes":[{"pos":[0,438],"content":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property. The <xref:System.Exception.InnerException%2A> property returns the same value that is supplied to the constructor or a null reference (Nothing in Visual Basic) if the `innerException` parameter does not supply the inner exception value to the constructor.","nodes":[{"content":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <ph id=\"ph1\">&lt;xref:System.Exception.InnerException%2A&gt;</ph> property.","pos":[0,182],"source":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property."},{"content":"The <ph id=\"ph1\">&lt;xref:System.Exception.InnerException%2A&gt;</ph> property returns the same value that is supplied to the constructor or a null reference (Nothing in Visual Basic) if the <ph id=\"ph2\">`innerException`</ph> parameter does not supply the inner exception value to the constructor.","pos":[183,438],"source":" The <xref:System.Exception.InnerException%2A> property returns the same value that is supplied to the constructor or a null reference (Nothing in Visual Basic) if the `innerException` parameter does not supply the inner exception value to the constructor."}]},{"pos":[445,800],"content":"`instanceId` is equivalent to the <xref:System.Workflow.Runtime.WorkflowInstance.InstanceId%2A?displayProperty=fullName> property of the workflow instance. The content of the `message` parameter is intended to be understood by humans. The caller of this constructor is required to ensure that this string has been localized for the current system culture.","nodes":[{"content":"<ph id=\"ph1\">`instanceId`</ph> is equivalent to the <ph id=\"ph2\">&lt;xref:System.Workflow.Runtime.WorkflowInstance.InstanceId%2A?displayProperty=fullName&gt;</ph> property of the workflow instance.","pos":[0,155],"source":"`instanceId` is equivalent to the <xref:System.Workflow.Runtime.WorkflowInstance.InstanceId%2A?displayProperty=fullName> property of the workflow instance."},{"content":"The content of the <ph id=\"ph1\">`message`</ph> parameter is intended to be understood by humans.","pos":[156,234],"source":" The content of the `message` parameter is intended to be understood by humans."},{"content":"The caller of this constructor is required to ensure that this string has been localized for the current system culture.","pos":[235,355]}]},{"pos":[807,938],"content":"The following table shows the initial property values for an instance of <xref:System.Workflow.Runtime.WorkflowOwnershipException>.","nodes":[{"content":"The following table shows the initial property values for an instance of <ph id=\"ph1\">&lt;xref:System.Workflow.Runtime.WorkflowOwnershipException&gt;</ph>.","pos":[0,131],"source":"The following table shows the initial property values for an instance of <xref:System.Workflow.Runtime.WorkflowOwnershipException>."}]},{"pos":[945,953],"content":"Property","nodes":[{"content":"Property","pos":[0,8]}]},{"pos":[954,959],"content":"Value","nodes":[{"content":"Value","pos":[0,5]}]},{"pos":[995,1036],"content":"<xref:System.Exception.InnerException%2A>","nodes":[]},{"pos":[1037,1067],"content":"The inner exception reference.","nodes":[{"content":"The inner exception reference.","pos":[0,30]}]},{"pos":[1072,1106],"content":"<xref:System.Exception.Message%2A>","nodes":[]},{"pos":[1107,1132],"content":"The error message string.","nodes":[{"content":"The error message string.","pos":[0,25]}]},{"pos":[1137,1208],"content":"<xref:System.Workflow.Runtime.WorkflowOwnershipException.InstanceId%2A>","nodes":[]},{"pos":[1209,1319],"content":"The <ph id=\"ph1\">&lt;xref:System.Guid&gt;</ph> of the workflow instance, specified by <ph id=\"ph2\">`instanceId`</ph>, for which this exception occurred.","source":"The <xref:System.Guid> of the workflow instance, specified by `instanceId`, for which this exception occurred."}],"pos":[20510,21843],"yaml":true,"extradata":"MT"},{"content":"The <xref href=\"System.Guid\"></xref> of the workflow instance for which this exception occurred.","nodes":[{"pos":[0,96],"content":"The <ph id=\"ph1\">&lt;xref href=\"System.Guid\"&gt;&lt;/xref&gt;</ph> of the workflow instance for which this exception occurred.","source":"The <xref href=\"System.Guid\"></xref> of the workflow instance for which this exception occurred."}],"pos":[22041,22138],"yaml":true},{"content":"The message that describes the error.","nodes":[{"pos":[0,37],"content":"The message that describes the error.","nodes":[{"content":"The message that describes the error.","pos":[0,37]}]}],"pos":[22201,22239],"yaml":true},{"content":"The exception that is the cause of the current exception. If the <code>innerException</code> parameter is not a null reference (`Nothing` in Visual Basic), the current exception is raised in a catch block that handles the inner exception.","nodes":[{"pos":[0,238],"content":"The exception that is the cause of the current exception. If the <code>innerException</code> parameter is not a null reference (`Nothing` in Visual Basic), the current exception is raised in a catch block that handles the inner exception.","nodes":[{"content":"The exception that is the cause of the current exception.","pos":[0,57]},{"content":"If the <bpt id=\"p1\">&lt;code&gt;</bpt><ph id=\"ph1\">innerException</ph><ept id=\"p1\">&lt;/code&gt;</ept> parameter is not a null reference (<ph id=\"ph2\">`Nothing`</ph> in Visual Basic), the current exception is raised in a catch block that handles the inner exception.","pos":[58,238],"source":" If the <code>innerException</code> parameter is not a null reference (`Nothing` in Visual Basic), the current exception is raised in a catch block that handles the inner exception."}]}],"pos":[22312,22551],"yaml":true},{"content":"Sets the <xref href=\"System.Runtime.Serialization.SerializationInfo\"></xref> object with the <xref href=\"System.Guid\"></xref> of the workflow instance associated with this exception, and additional exception information.","nodes":[{"pos":[0,220],"content":"Sets the <ph id=\"ph1\">&lt;xref href=\"System.Runtime.Serialization.SerializationInfo\"&gt;&lt;/xref&gt;</ph> object with the <ph id=\"ph2\">&lt;xref href=\"System.Guid\"&gt;&lt;/xref&gt;</ph> of the workflow instance associated with this exception, and additional exception information.","source":"Sets the <xref href=\"System.Runtime.Serialization.SerializationInfo\"></xref> object with the <xref href=\"System.Guid\"></xref> of the workflow instance associated with this exception, and additional exception information."}],"pos":[24030,24251],"yaml":true},{"content":"<xref:System.Workflow.Runtime.WorkflowOwnershipException.GetObjectData%2A> sets a <xref:System.Runtime.Serialization.SerializationInfo> with all the exception object data targeted for serialization. During deserialization the exception object is reconstituted from the <xref:System.Runtime.Serialization.SerializationInfo> transmitted over the stream.  \n  \n For more information see XML and SOAP Serialization.","nodes":[{"pos":[0,351],"content":"<xref:System.Workflow.Runtime.WorkflowOwnershipException.GetObjectData%2A> sets a <xref:System.Runtime.Serialization.SerializationInfo> with all the exception object data targeted for serialization. During deserialization the exception object is reconstituted from the <xref:System.Runtime.Serialization.SerializationInfo> transmitted over the stream.","nodes":[{"content":"<xref:System.Workflow.Runtime.WorkflowOwnershipException.GetObjectData%2A> sets a <xref:System.Runtime.Serialization.SerializationInfo> with all the exception object data targeted for serialization. During deserialization the exception object is reconstituted from the <xref:System.Runtime.Serialization.SerializationInfo> transmitted over the stream.","pos":[0,351],"nodes":[{"content":"<ph id=\"ph1\">&lt;xref:System.Workflow.Runtime.WorkflowOwnershipException.GetObjectData%2A&gt;</ph> sets a <ph id=\"ph2\">&lt;xref:System.Runtime.Serialization.SerializationInfo&gt;</ph> with all the exception object data targeted for serialization.","pos":[0,198],"source":"<xref:System.Workflow.Runtime.WorkflowOwnershipException.GetObjectData%2A> sets a <xref:System.Runtime.Serialization.SerializationInfo> with all the exception object data targeted for serialization."},{"content":"During deserialization the exception object is reconstituted from the <ph id=\"ph1\">&lt;xref:System.Runtime.Serialization.SerializationInfo&gt;</ph> transmitted over the stream.","pos":[199,351],"source":" During deserialization the exception object is reconstituted from the <xref:System.Runtime.Serialization.SerializationInfo> transmitted over the stream."}]}]},{"pos":[358,410],"content":"For more information see XML and SOAP Serialization.","nodes":[{"content":"For more information see XML and SOAP Serialization.","pos":[0,52]}]}],"pos":[24262,24677],"yaml":true,"extradata":"MT"},{"content":"A <xref href=\"System.Runtime.Serialization.SerializationInfo\"></xref> that holds the serialized object data about the exception being thrown.","nodes":[{"pos":[0,141],"content":"A <ph id=\"ph1\">&lt;xref href=\"System.Runtime.Serialization.SerializationInfo\"&gt;&lt;/xref&gt;</ph> that holds the serialized object data about the exception being thrown.","source":"A <xref href=\"System.Runtime.Serialization.SerializationInfo\"></xref> that holds the serialized object data about the exception being thrown."}],"pos":[24954,25096],"yaml":true},{"content":"A <xref href=\"System.Runtime.Serialization.StreamingContext\"></xref> that contains contextual information about the source or destination.","nodes":[{"pos":[0,138],"content":"A <ph id=\"ph1\">&lt;xref href=\"System.Runtime.Serialization.StreamingContext\"&gt;&lt;/xref&gt;</ph> that contains contextual information about the source or destination.","source":"A <xref href=\"System.Runtime.Serialization.StreamingContext\"></xref> that contains contextual information about the source or destination."}],"pos":[25191,25330],"yaml":true},{"content":"<code>info</code> is a null reference (`Nothing` in Visual Basic)","nodes":[{"pos":[0,65],"content":"<ph id=\"ph1\">&lt;code&gt;info&lt;/code&gt;</ph> is a null reference (<ph id=\"ph2\">`Nothing`</ph> in Visual Basic)","source":"<code>info</code> is a null reference (`Nothing` in Visual Basic)"}],"pos":[25524,25590],"yaml":true},{"content":"Gets the <xref href=\"System.Guid\"></xref> of the workflow instance for which this exception was thrown.","nodes":[{"pos":[0,103],"content":"Gets the <ph id=\"ph1\">&lt;xref href=\"System.Guid\"&gt;&lt;/xref&gt;</ph> of the workflow instance for which this exception was thrown.","source":"Gets the <xref href=\"System.Guid\"></xref> of the workflow instance for which this exception was thrown."}],"pos":[26573,26677],"yaml":true},{"content":"<xref href=\"System.Workflow.Runtime.WorkflowOwnershipException.InstanceId\"></xref> is equivalent to the <xref href=\"System.Workflow.Runtime.WorkflowInstance.InstanceId\"></xref> property of the workflow instance.","nodes":[{"pos":[0,211],"content":"<ph id=\"ph1\">&lt;xref href=\"System.Workflow.Runtime.WorkflowOwnershipException.InstanceId\"&gt;&lt;/xref&gt;</ph> is equivalent to the <ph id=\"ph2\">&lt;xref href=\"System.Workflow.Runtime.WorkflowInstance.InstanceId\"&gt;&lt;/xref&gt;</ph> property of the workflow instance.","source":"<xref href=\"System.Workflow.Runtime.WorkflowOwnershipException.InstanceId\"></xref> is equivalent to the <xref href=\"System.Workflow.Runtime.WorkflowInstance.InstanceId\"></xref> property of the workflow instance."}],"pos":[26792,27004],"yaml":true}],"content":"### YamlMime:ManagedReference\nitems:\n- uid: System.Workflow.Runtime.WorkflowOwnershipException\n  commentId: T:System.Workflow.Runtime.WorkflowOwnershipException\n  id: WorkflowOwnershipException\n  children:\n  - System.Workflow.Runtime.WorkflowOwnershipException.#ctor\n  - System.Workflow.Runtime.WorkflowOwnershipException.#ctor(System.Guid)\n  - System.Workflow.Runtime.WorkflowOwnershipException.#ctor(System.String)\n  - System.Workflow.Runtime.WorkflowOwnershipException.#ctor(System.Guid,System.String)\n  - System.Workflow.Runtime.WorkflowOwnershipException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  - System.Workflow.Runtime.WorkflowOwnershipException.#ctor(System.String,System.Exception)\n  - System.Workflow.Runtime.WorkflowOwnershipException.#ctor(System.Guid,System.String,System.Exception)\n  - System.Workflow.Runtime.WorkflowOwnershipException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  - System.Workflow.Runtime.WorkflowOwnershipException.InstanceId\n  langs:\n  - csharp\n  name: WorkflowOwnershipException\n  nameWithType: WorkflowOwnershipException\n  fullName: System.Workflow.Runtime.WorkflowOwnershipException\n  type: Class\n  assemblies:\n  - System.Workflow.Runtime\n  namespace: System.Workflow.Runtime\n  summary: The exception that is thrown when the workflow runtime engine attempts to load a workflow instance that is currently loaded by another workflow runtime engine instance. Additionally, this exception is thrown when the workflow runtime engine attempts to save a workflow after the ownership timeout that was specified while loading the workflow has expired.\n  remarks: \"> [!NOTE]\\n>  [!INCLUDE[DeprecatedContent](~/includes/deprecatedcontent-md.md)]  \\n  \\n The <xref:System.Workflow.Runtime.WorkflowOwnershipException> is used by persistence services which support the capability for multiple applications to access the same database. In such an environment, an instance of the workflow runtime may try to load a workflow that is already loaded by another instance of the workflow runtime engine. For example, the <xref:System.Workflow.Runtime.Hosting.SqlWorkflowPersistenceService> class throws the <xref:System.Workflow.Runtime.WorkflowOwnershipException> when this situation occurs.  \\n  \\n If you implement a persistence service that throws the <xref:System.Workflow.Runtime.WorkflowOwnershipException> you should provide the <xref:System.Guid> of the workflow instance for which the exception occurs by using an appropriate constructor for the class or setting the <xref:System.Workflow.Runtime.WorkflowOwnershipException.InstanceId%2A> property before you throw the exception.\"\n  syntax:\n    content: >-\n      [System.Obsolete(\"The System.Workflow.* types are deprecated.  Instead, please use the new types from System.Activities.*\")]\n\n      public class WorkflowOwnershipException : Exception\n  inheritance:\n  - System.Object\n  - System.Exception\n  implements: []\n  inheritedMembers:\n  - System.Exception.Data\n  - System.Exception.GetBaseException\n  - System.Exception.GetType\n  - System.Exception.HelpLink\n  - System.Exception.HResult\n  - System.Exception.InnerException\n  - System.Exception.Message\n  - System.Exception.SerializeObjectState\n  - System.Exception.Source\n  - System.Exception.StackTrace\n  - System.Exception.TargetSite\n  - System.Exception.ToString\n  - System.Object.Equals(System.Object)\n  - System.Object.Equals(System.Object,System.Object)\n  - System.Object.GetHashCode\n  - System.Object.MemberwiseClone\n  - System.Object.ReferenceEquals(System.Object,System.Object)\n  attributes:\n  - type: System.ObsoleteAttribute\n  version:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  monikers:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Workflow.Runtime/WorkflowOwnershipException.xml\n  author: Erikre\n  ms.author: erikre\n  manager: erikre\n- uid: System.Workflow.Runtime.WorkflowOwnershipException.#ctor\n  commentId: M:System.Workflow.Runtime.WorkflowOwnershipException.#ctor\n  id: '#ctor'\n  parent: System.Workflow.Runtime.WorkflowOwnershipException\n  langs:\n  - csharp\n  name: WorkflowOwnershipException()\n  nameWithType: WorkflowOwnershipException.WorkflowOwnershipException()\n  fullName: WorkflowOwnershipException.WorkflowOwnershipException()\n  type: Constructor\n  assemblies:\n  - System.Workflow.Runtime\n  namespace: System.Workflow.Runtime\n  summary: Initializes a new instance of the <xref href=\"System.Workflow.Runtime.WorkflowOwnershipException\"></xref> class.\n  remarks: \"This constructor initializes the <xref:System.Exception.Message%2A> property of the new instance to a system-supplied message that describes the error and takes into account the current system culture.  \\n  \\n The following table shows the initial property values for an instance of <xref:System.Workflow.Runtime.WorkflowOwnershipException>.  \\n  \\n|Property|Value|  \\n|--------------|-----------|  \\n|<xref:System.Exception.InnerException%2A>|A null reference (`Nothing` in Visual Basic)|  \\n|<xref:System.Exception.Message%2A>|A system-supplied localized description.|  \\n|<xref:System.Workflow.Runtime.WorkflowOwnershipException.InstanceId%2A>|An empty <xref:System.Guid>.|\"\n  syntax:\n    content: public WorkflowOwnershipException ();\n    parameters: []\n  overload: System.Workflow.Runtime.WorkflowOwnershipException.#ctor*\n  exceptions: []\n  version:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  monikers:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Workflow.Runtime/WorkflowOwnershipException.xml\n  author: Erikre\n  ms.author: erikre\n  manager: erikre\n- uid: System.Workflow.Runtime.WorkflowOwnershipException.#ctor(System.Guid)\n  commentId: M:System.Workflow.Runtime.WorkflowOwnershipException.#ctor(System.Guid)\n  id: '#ctor(System.Guid)'\n  parent: System.Workflow.Runtime.WorkflowOwnershipException\n  langs:\n  - csharp\n  name: WorkflowOwnershipException(Guid)\n  nameWithType: WorkflowOwnershipException.WorkflowOwnershipException(Guid)\n  fullName: WorkflowOwnershipException.WorkflowOwnershipException(Guid)\n  type: Constructor\n  assemblies:\n  - System.Workflow.Runtime\n  namespace: System.Workflow.Runtime\n  summary: Initializes a new instance of the <xref href=\"System.Workflow.Runtime.WorkflowOwnershipException\"></xref> class by using a specified workflow instance <xref href=\"System.Guid\"></xref>.\n  remarks: \"`instanceId` is equivalent to the <xref:System.Workflow.Runtime.WorkflowInstance.InstanceId%2A?displayProperty=fullName> property of the workflow instance. The <xref:System.Exception.Message%2A> property of the new instance is initialized to a system-supplied message that describes the error and takes into account the current system culture.  \\n  \\n The following table shows the initial property values for an instance of <xref:System.Workflow.Runtime.WorkflowOwnershipException>.  \\n  \\n|Property|Value|  \\n|--------------|-----------|  \\n|<xref:System.Exception.InnerException%2A>|A null reference (`Nothing` in Visual Basic)|  \\n|<xref:System.Exception.Message%2A>|A system-supplied localized description.|  \\n|<xref:System.Workflow.Runtime.WorkflowOwnershipException.InstanceId%2A>|The <xref:System.Guid> of the workflow instance, specified by `instanceId`, for which this exception occurred.|\"\n  syntax:\n    content: public WorkflowOwnershipException (Guid instanceId);\n    parameters:\n    - id: instanceId\n      type: System.Guid\n      description: The <xref href=\"System.Guid\"></xref> of the workflow instance for which this exception occurred.\n  overload: System.Workflow.Runtime.WorkflowOwnershipException.#ctor*\n  exceptions: []\n  version:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  monikers:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Workflow.Runtime/WorkflowOwnershipException.xml\n  author: Erikre\n  ms.author: erikre\n  manager: erikre\n- uid: System.Workflow.Runtime.WorkflowOwnershipException.#ctor(System.String)\n  commentId: M:System.Workflow.Runtime.WorkflowOwnershipException.#ctor(System.String)\n  id: '#ctor(System.String)'\n  parent: System.Workflow.Runtime.WorkflowOwnershipException\n  langs:\n  - csharp\n  name: WorkflowOwnershipException(String)\n  nameWithType: WorkflowOwnershipException.WorkflowOwnershipException(String)\n  fullName: WorkflowOwnershipException.WorkflowOwnershipException(String)\n  type: Constructor\n  assemblies:\n  - System.Workflow.Runtime\n  namespace: System.Workflow.Runtime\n  summary: Initializes a new instance of the <xref href=\"System.Workflow.Runtime.WorkflowOwnershipException\"></xref> class by using a specified error message.\n  remarks: \"The content of the `message` parameter is intended to be understood by humans. The caller of this constructor is required to ensure that this string has been localized for the current system culture. If you use this constructor you should explicitly set <xref:System.Workflow.Runtime.WorkflowOwnershipException.InstanceId%2A> before you throw the exception.  \\n  \\n The following table shows the initial property values for an instance of <xref:System.Workflow.Runtime.WorkflowOwnershipException>.  \\n  \\n|Property|Value|  \\n|--------------|-----------|  \\n|<xref:System.Exception.InnerException%2A>|A null reference (`Nothing` in Visual Basic).|  \\n|<xref:System.Exception.Message%2A>|The error message string.|  \\n|<xref:System.Workflow.Runtime.WorkflowOwnershipException.InstanceId%2A>|An empty <xref:System.Guid>.|\"\n  syntax:\n    content: public WorkflowOwnershipException (string message);\n    parameters:\n    - id: message\n      type: System.String\n      description: The message that describes the error.\n  overload: System.Workflow.Runtime.WorkflowOwnershipException.#ctor*\n  exceptions: []\n  version:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  monikers:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Workflow.Runtime/WorkflowOwnershipException.xml\n  author: Erikre\n  ms.author: erikre\n  manager: erikre\n- uid: System.Workflow.Runtime.WorkflowOwnershipException.#ctor(System.Guid,System.String)\n  commentId: M:System.Workflow.Runtime.WorkflowOwnershipException.#ctor(System.Guid,System.String)\n  id: '#ctor(System.Guid,System.String)'\n  parent: System.Workflow.Runtime.WorkflowOwnershipException\n  langs:\n  - csharp\n  name: WorkflowOwnershipException(Guid, String)\n  nameWithType: WorkflowOwnershipException.WorkflowOwnershipException(Guid, String)\n  fullName: WorkflowOwnershipException.WorkflowOwnershipException(Guid, String)\n  type: Constructor\n  assemblies:\n  - System.Workflow.Runtime\n  namespace: System.Workflow.Runtime\n  summary: Initializes a new instance of the <xref href=\"System.Workflow.Runtime.WorkflowOwnershipException\"></xref> class by using a specified workflow instance <xref href=\"System.Guid\"></xref> and a specified error message.\n  remarks: \"`instanceId` is equivalent to the <xref:System.Workflow.Runtime.WorkflowInstance.InstanceId%2A?displayProperty=fullName> property of the workflow instance. The content of the `message` parameter is intended to be understood by humans. The caller of this constructor is required to ensure that this string has been localized for the current system culture.  \\n  \\n The following table shows the initial property values for an instance of <xref:System.Workflow.Runtime.WorkflowOwnershipException>.  \\n  \\n|Property|Value|  \\n|--------------|-----------|  \\n|<xref:System.Exception.InnerException%2A>|A null reference (`Nothing` in Visual Basic)|  \\n|<xref:System.Exception.Message%2A>|The error message string.|  \\n|<xref:System.Workflow.Runtime.WorkflowOwnershipException.InstanceId%2A>|The <xref:System.Guid> of the workflow instance, specified by `instanceId`, for which this exception occurred.|\"\n  syntax:\n    content: public WorkflowOwnershipException (Guid instanceId, string message);\n    parameters:\n    - id: instanceId\n      type: System.Guid\n      description: The <xref href=\"System.Guid\"></xref> of the workflow instance for which this exception occurred.\n    - id: message\n      type: System.String\n      description: The message that describes the error.\n  overload: System.Workflow.Runtime.WorkflowOwnershipException.#ctor*\n  exceptions: []\n  version:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  monikers:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Workflow.Runtime/WorkflowOwnershipException.xml\n  author: Erikre\n  ms.author: erikre\n  manager: erikre\n- uid: System.Workflow.Runtime.WorkflowOwnershipException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  commentId: M:System.Workflow.Runtime.WorkflowOwnershipException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'\n  parent: System.Workflow.Runtime.WorkflowOwnershipException\n  langs:\n  - csharp\n  name: WorkflowOwnershipException(SerializationInfo, StreamingContext)\n  nameWithType: WorkflowOwnershipException.WorkflowOwnershipException(SerializationInfo, StreamingContext)\n  fullName: WorkflowOwnershipException.WorkflowOwnershipException(SerializationInfo, StreamingContext)\n  type: Constructor\n  assemblies:\n  - System.Workflow.Runtime\n  namespace: System.Workflow.Runtime\n  summary: Initializes a new instance of the WorkflowOwnershipException class with serialized data.\n  remarks: \"This constructor is called during serialization to reconstitute the exception object transmitted over a stream.  \\n  \\n For more information see XML and SOAP Serialization.\"\n  syntax:\n    content: protected WorkflowOwnershipException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);\n    parameters:\n    - id: info\n      type: System.Runtime.Serialization.SerializationInfo\n      description: A <xref href=\"System.Runtime.Serialization.SerializationInfo\"></xref> that holds the serialized object data about the exception being thrown.\n    - id: context\n      type: System.Runtime.Serialization.StreamingContext\n      description: A <xref href=\"System.Runtime.Serialization.StreamingContext\"></xref> that contains contextual information about the source or destination.\n  overload: System.Workflow.Runtime.WorkflowOwnershipException.#ctor*\n  exceptions: []\n  version:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  monikers:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Workflow.Runtime/WorkflowOwnershipException.xml\n  author: Erikre\n  ms.author: erikre\n  manager: erikre\n- uid: System.Workflow.Runtime.WorkflowOwnershipException.#ctor(System.String,System.Exception)\n  commentId: M:System.Workflow.Runtime.WorkflowOwnershipException.#ctor(System.String,System.Exception)\n  id: '#ctor(System.String,System.Exception)'\n  parent: System.Workflow.Runtime.WorkflowOwnershipException\n  langs:\n  - csharp\n  name: WorkflowOwnershipException(String, Exception)\n  nameWithType: WorkflowOwnershipException.WorkflowOwnershipException(String, Exception)\n  fullName: WorkflowOwnershipException.WorkflowOwnershipException(String, Exception)\n  type: Constructor\n  assemblies:\n  - System.Workflow.Runtime\n  namespace: System.Workflow.Runtime\n  summary: Initializes a new instance of the <xref href=\"System.Workflow.Runtime.WorkflowOwnershipException\"></xref> class by using a specified error message and a reference to the inner exception that is the cause of this exception.\n  remarks: \"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property. The <xref:System.Exception.InnerException%2A> property returns the same value that is supplied to the constructor or a null reference (Nothing in Visual Basic) if the `innerException` parameter does not supply the inner exception value to the constructor. The content of the `message` parameter is intended to be understood by humans. The caller of this constructor is required to ensure that this string has been localized for the current system culture. If you use this constructor you should explicitly set <xref:System.Workflow.Runtime.WorkflowOwnershipException.InstanceId%2A> before you throw the exception.  \\n  \\n The following table shows the initial property values for an instance of <xref:System.Workflow.Runtime.WorkflowOwnershipException>.  \\n  \\n|Property|Value|  \\n|--------------|-----------|  \\n|<xref:System.Exception.InnerException%2A>|The inner exception reference.|  \\n|<xref:System.Exception.Message%2A>|The error message string.|  \\n|<xref:System.Workflow.Runtime.WorkflowOwnershipException.InstanceId%2A>|An empty <xref:System.Guid>.|\"\n  syntax:\n    content: public WorkflowOwnershipException (string message, Exception innerException);\n    parameters:\n    - id: message\n      type: System.String\n      description: The message that describes the error.\n    - id: innerException\n      type: System.Exception\n      description: The exception that is the cause of the current exception. If the <code>innerException</code> parameter is not a null reference (`Nothing` in Visual Basic), the current exception is raised in a catch block that handles the inner exception.\n  overload: System.Workflow.Runtime.WorkflowOwnershipException.#ctor*\n  exceptions: []\n  version:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  monikers:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Workflow.Runtime/WorkflowOwnershipException.xml\n  author: Erikre\n  ms.author: erikre\n  manager: erikre\n- uid: System.Workflow.Runtime.WorkflowOwnershipException.#ctor(System.Guid,System.String,System.Exception)\n  commentId: M:System.Workflow.Runtime.WorkflowOwnershipException.#ctor(System.Guid,System.String,System.Exception)\n  id: '#ctor(System.Guid,System.String,System.Exception)'\n  parent: System.Workflow.Runtime.WorkflowOwnershipException\n  langs:\n  - csharp\n  name: WorkflowOwnershipException(Guid, String, Exception)\n  nameWithType: WorkflowOwnershipException.WorkflowOwnershipException(Guid, String, Exception)\n  fullName: WorkflowOwnershipException.WorkflowOwnershipException(Guid, String, Exception)\n  type: Constructor\n  assemblies:\n  - System.Workflow.Runtime\n  namespace: System.Workflow.Runtime\n  summary: Initializes a new instance of the <xref href=\"System.Workflow.Runtime.WorkflowOwnershipException\"></xref> class by using a specified workflow instance <xref href=\"System.Guid\"></xref>, a specified error message, and a reference to the inner exception that is the cause of this exception.\n  remarks: \"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property. The <xref:System.Exception.InnerException%2A> property returns the same value that is supplied to the constructor or a null reference (Nothing in Visual Basic) if the `innerException` parameter does not supply the inner exception value to the constructor.  \\n  \\n `instanceId` is equivalent to the <xref:System.Workflow.Runtime.WorkflowInstance.InstanceId%2A?displayProperty=fullName> property of the workflow instance. The content of the `message` parameter is intended to be understood by humans. The caller of this constructor is required to ensure that this string has been localized for the current system culture.  \\n  \\n The following table shows the initial property values for an instance of <xref:System.Workflow.Runtime.WorkflowOwnershipException>.  \\n  \\n|Property|Value|  \\n|--------------|-----------|  \\n|<xref:System.Exception.InnerException%2A>|The inner exception reference.|  \\n|<xref:System.Exception.Message%2A>|The error message string.|  \\n|<xref:System.Workflow.Runtime.WorkflowOwnershipException.InstanceId%2A>|The <xref:System.Guid> of the workflow instance, specified by `instanceId`, for which this exception occurred.|\"\n  syntax:\n    content: public WorkflowOwnershipException (Guid instanceId, string message, Exception innerException);\n    parameters:\n    - id: instanceId\n      type: System.Guid\n      description: The <xref href=\"System.Guid\"></xref> of the workflow instance for which this exception occurred.\n    - id: message\n      type: System.String\n      description: The message that describes the error.\n    - id: innerException\n      type: System.Exception\n      description: The exception that is the cause of the current exception. If the <code>innerException</code> parameter is not a null reference (`Nothing` in Visual Basic), the current exception is raised in a catch block that handles the inner exception.\n  overload: System.Workflow.Runtime.WorkflowOwnershipException.#ctor*\n  exceptions: []\n  version:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  monikers:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Workflow.Runtime/WorkflowOwnershipException.xml\n  author: Erikre\n  ms.author: erikre\n  manager: erikre\n- uid: System.Workflow.Runtime.WorkflowOwnershipException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  commentId: M:System.Workflow.Runtime.WorkflowOwnershipException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  id: GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  parent: System.Workflow.Runtime.WorkflowOwnershipException\n  langs:\n  - csharp\n  name: GetObjectData(SerializationInfo, StreamingContext)\n  nameWithType: WorkflowOwnershipException.GetObjectData(SerializationInfo, StreamingContext)\n  fullName: WorkflowOwnershipException.GetObjectData(SerializationInfo, StreamingContext)\n  type: Method\n  assemblies:\n  - System.Workflow.Runtime\n  namespace: System.Workflow.Runtime\n  summary: Sets the <xref href=\"System.Runtime.Serialization.SerializationInfo\"></xref> object with the <xref href=\"System.Guid\"></xref> of the workflow instance associated with this exception, and additional exception information.\n  remarks: \"<xref:System.Workflow.Runtime.WorkflowOwnershipException.GetObjectData%2A> sets a <xref:System.Runtime.Serialization.SerializationInfo> with all the exception object data targeted for serialization. During deserialization the exception object is reconstituted from the <xref:System.Runtime.Serialization.SerializationInfo> transmitted over the stream.  \\n  \\n For more information see XML and SOAP Serialization.\"\n  syntax:\n    content: public override void GetObjectData (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);\n    parameters:\n    - id: info\n      type: System.Runtime.Serialization.SerializationInfo\n      description: A <xref href=\"System.Runtime.Serialization.SerializationInfo\"></xref> that holds the serialized object data about the exception being thrown.\n    - id: context\n      type: System.Runtime.Serialization.StreamingContext\n      description: A <xref href=\"System.Runtime.Serialization.StreamingContext\"></xref> that contains contextual information about the source or destination.\n  overload: System.Workflow.Runtime.WorkflowOwnershipException.GetObjectData*\n  exceptions:\n  - type: System.ArgumentNullException\n    commentId: T:System.ArgumentNullException\n    description: <code>info</code> is a null reference (`Nothing` in Visual Basic)\n  version:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  monikers:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Workflow.Runtime/WorkflowOwnershipException.xml\n  author: Erikre\n  ms.author: erikre\n  manager: erikre\n- uid: System.Workflow.Runtime.WorkflowOwnershipException.InstanceId\n  commentId: P:System.Workflow.Runtime.WorkflowOwnershipException.InstanceId\n  id: InstanceId\n  parent: System.Workflow.Runtime.WorkflowOwnershipException\n  langs:\n  - csharp\n  name: InstanceId\n  nameWithType: WorkflowOwnershipException.InstanceId\n  fullName: WorkflowOwnershipException.InstanceId\n  type: Property\n  assemblies:\n  - System.Workflow.Runtime\n  namespace: System.Workflow.Runtime\n  summary: Gets the <xref href=\"System.Guid\"></xref> of the workflow instance for which this exception was thrown.\n  syntax:\n    content: public Guid InstanceId { get; set; }\n    return:\n      type: System.Guid\n      description: <xref href=\"System.Workflow.Runtime.WorkflowOwnershipException.InstanceId\"></xref> is equivalent to the <xref href=\"System.Workflow.Runtime.WorkflowInstance.InstanceId\"></xref> property of the workflow instance.\n  overload: System.Workflow.Runtime.WorkflowOwnershipException.InstanceId*\n  exceptions: []\n  version:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  monikers:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Workflow.Runtime/WorkflowOwnershipException.xml\n  author: Erikre\n  ms.author: erikre\n  manager: erikre\nreferences:\n- uid: System.Exception\n  parent: System\n  isExternal: false\n  name: Exception\n  nameWithType: Exception\n  fullName: System.Exception\n- uid: System.ArgumentNullException\n  parent: System\n  isExternal: false\n  name: ArgumentNullException\n  nameWithType: ArgumentNullException\n  fullName: System.ArgumentNullException\n- uid: System.Workflow.Runtime.WorkflowOwnershipException.#ctor\n  parent: System.Workflow.Runtime.WorkflowOwnershipException\n  isExternal: false\n  name: WorkflowOwnershipException()\n  nameWithType: WorkflowOwnershipException.WorkflowOwnershipException()\n  fullName: WorkflowOwnershipException.WorkflowOwnershipException()\n- uid: System.Workflow.Runtime.WorkflowOwnershipException.#ctor(System.Guid)\n  parent: System.Workflow.Runtime.WorkflowOwnershipException\n  isExternal: false\n  name: WorkflowOwnershipException(Guid)\n  nameWithType: WorkflowOwnershipException.WorkflowOwnershipException(Guid)\n  fullName: WorkflowOwnershipException.WorkflowOwnershipException(Guid)\n- uid: System.Guid\n  parent: System\n  isExternal: false\n  name: Guid\n  nameWithType: Guid\n  fullName: System.Guid\n- uid: System.Workflow.Runtime.WorkflowOwnershipException.#ctor(System.String)\n  parent: System.Workflow.Runtime.WorkflowOwnershipException\n  isExternal: false\n  name: WorkflowOwnershipException(String)\n  nameWithType: WorkflowOwnershipException.WorkflowOwnershipException(String)\n  fullName: WorkflowOwnershipException.WorkflowOwnershipException(String)\n- uid: System.String\n  parent: System\n  isExternal: false\n  name: String\n  nameWithType: String\n  fullName: System.String\n- uid: System.Workflow.Runtime.WorkflowOwnershipException.#ctor(System.Guid,System.String)\n  parent: System.Workflow.Runtime.WorkflowOwnershipException\n  isExternal: false\n  name: WorkflowOwnershipException(Guid, String)\n  nameWithType: WorkflowOwnershipException.WorkflowOwnershipException(Guid, String)\n  fullName: WorkflowOwnershipException.WorkflowOwnershipException(Guid, String)\n- uid: System.Workflow.Runtime.WorkflowOwnershipException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  parent: System.Workflow.Runtime.WorkflowOwnershipException\n  isExternal: false\n  name: WorkflowOwnershipException(SerializationInfo, StreamingContext)\n  nameWithType: WorkflowOwnershipException.WorkflowOwnershipException(SerializationInfo, StreamingContext)\n  fullName: WorkflowOwnershipException.WorkflowOwnershipException(SerializationInfo, StreamingContext)\n- uid: System.Runtime.Serialization.SerializationInfo\n  parent: System.Runtime.Serialization\n  isExternal: false\n  name: SerializationInfo\n  nameWithType: SerializationInfo\n  fullName: System.Runtime.Serialization.SerializationInfo\n- uid: System.Runtime.Serialization.StreamingContext\n  parent: System.Runtime.Serialization\n  isExternal: false\n  name: StreamingContext\n  nameWithType: StreamingContext\n  fullName: System.Runtime.Serialization.StreamingContext\n- uid: System.Workflow.Runtime.WorkflowOwnershipException.#ctor(System.String,System.Exception)\n  parent: System.Workflow.Runtime.WorkflowOwnershipException\n  isExternal: false\n  name: WorkflowOwnershipException(String, Exception)\n  nameWithType: WorkflowOwnershipException.WorkflowOwnershipException(String, Exception)\n  fullName: WorkflowOwnershipException.WorkflowOwnershipException(String, Exception)\n- uid: System.Workflow.Runtime.WorkflowOwnershipException.#ctor(System.Guid,System.String,System.Exception)\n  parent: System.Workflow.Runtime.WorkflowOwnershipException\n  isExternal: false\n  name: WorkflowOwnershipException(Guid, String, Exception)\n  nameWithType: WorkflowOwnershipException.WorkflowOwnershipException(Guid, String, Exception)\n  fullName: WorkflowOwnershipException.WorkflowOwnershipException(Guid, String, Exception)\n- uid: System.Workflow.Runtime.WorkflowOwnershipException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  parent: System.Workflow.Runtime.WorkflowOwnershipException\n  isExternal: false\n  name: GetObjectData(SerializationInfo, StreamingContext)\n  nameWithType: WorkflowOwnershipException.GetObjectData(SerializationInfo, StreamingContext)\n  fullName: WorkflowOwnershipException.GetObjectData(SerializationInfo, StreamingContext)\n- uid: System.Workflow.Runtime.WorkflowOwnershipException.InstanceId\n  parent: System.Workflow.Runtime.WorkflowOwnershipException\n  isExternal: false\n  name: InstanceId\n  nameWithType: WorkflowOwnershipException.InstanceId\n  fullName: WorkflowOwnershipException.InstanceId\n- uid: System.Workflow.Runtime.WorkflowOwnershipException.#ctor*\n  parent: System.Workflow.Runtime.WorkflowOwnershipException\n  isExternal: false\n  name: WorkflowOwnershipException\n  nameWithType: WorkflowOwnershipException.WorkflowOwnershipException\n  fullName: WorkflowOwnershipException.WorkflowOwnershipException\n  monikers:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Workflow.Runtime/WorkflowOwnershipException.xml\n- uid: System.Workflow.Runtime.WorkflowOwnershipException.GetObjectData*\n  parent: System.Workflow.Runtime.WorkflowOwnershipException\n  isExternal: false\n  name: GetObjectData\n  nameWithType: WorkflowOwnershipException.GetObjectData\n  fullName: WorkflowOwnershipException.GetObjectData\n  monikers:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Workflow.Runtime/WorkflowOwnershipException.xml\n- uid: System.Workflow.Runtime.WorkflowOwnershipException.InstanceId*\n  parent: System.Workflow.Runtime.WorkflowOwnershipException\n  isExternal: false\n  name: InstanceId\n  nameWithType: WorkflowOwnershipException.InstanceId\n  fullName: WorkflowOwnershipException.InstanceId\n  monikers:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Workflow.Runtime/WorkflowOwnershipException.xml\n- uid: System.Object.Equals(System.Object)\n  parent: System.Object\n  isExternal: false\n  name: Equals(Object)\n  nameWithType: Object.Equals(Object)\n  fullName: Object.Equals(Object)\n- uid: System.Object.Equals(System.Object,System.Object)\n  parent: System.Object\n  isExternal: false\n  name: Equals(Object, Object)\n  nameWithType: Object.Equals(Object, Object)\n  fullName: Object.Equals(Object, Object)\n- uid: System.Object.GetHashCode\n  parent: System.Object\n  isExternal: false\n  name: GetHashCode()\n  nameWithType: Object.GetHashCode()\n  fullName: Object.GetHashCode()\n- uid: System.Exception.GetType\n  parent: System.Exception\n  isExternal: false\n  name: GetType()\n  nameWithType: Exception.GetType()\n  fullName: Exception.GetType()\n- uid: System.Object.MemberwiseClone\n  parent: System.Object\n  isExternal: false\n  name: MemberwiseClone()\n  nameWithType: Object.MemberwiseClone()\n  fullName: Object.MemberwiseClone()\n- uid: System.Object.ReferenceEquals(System.Object,System.Object)\n  parent: System.Object\n  isExternal: false\n  name: ReferenceEquals(Object, Object)\n  nameWithType: Object.ReferenceEquals(Object, Object)\n  fullName: Object.ReferenceEquals(Object, Object)\n- uid: System.Exception.ToString\n  parent: System.Exception\n  isExternal: false\n  name: ToString()\n  nameWithType: Exception.ToString()\n  fullName: Exception.ToString()\n- uid: System.Exception.Data\n  parent: System.Exception\n  isExternal: false\n  name: Data\n  nameWithType: Exception.Data\n  fullName: Exception.Data\n- uid: System.Exception.GetBaseException\n  parent: System.Exception\n  isExternal: false\n  name: GetBaseException()\n  nameWithType: Exception.GetBaseException()\n  fullName: Exception.GetBaseException()\n- uid: System.Exception.HelpLink\n  parent: System.Exception\n  isExternal: false\n  name: HelpLink\n  nameWithType: Exception.HelpLink\n  fullName: Exception.HelpLink\n- uid: System.Exception.HResult\n  parent: System.Exception\n  isExternal: false\n  name: HResult\n  nameWithType: Exception.HResult\n  fullName: Exception.HResult\n- uid: System.Exception.InnerException\n  parent: System.Exception\n  isExternal: false\n  name: InnerException\n  nameWithType: Exception.InnerException\n  fullName: Exception.InnerException\n- uid: System.Exception.Message\n  parent: System.Exception\n  isExternal: false\n  name: Message\n  nameWithType: Exception.Message\n  fullName: Exception.Message\n- uid: System.Exception.SerializeObjectState\n  parent: System.Exception\n  isExternal: false\n  name: SerializeObjectState\n  nameWithType: Exception.SerializeObjectState\n  fullName: Exception.SerializeObjectState\n- uid: System.Exception.Source\n  parent: System.Exception\n  isExternal: false\n  name: Source\n  nameWithType: Exception.Source\n  fullName: Exception.Source\n- uid: System.Exception.StackTrace\n  parent: System.Exception\n  isExternal: false\n  name: StackTrace\n  nameWithType: Exception.StackTrace\n  fullName: Exception.StackTrace\n- uid: System.Exception.TargetSite\n  parent: System.Exception\n  isExternal: false\n  name: TargetSite\n  nameWithType: Exception.TargetSite\n  fullName: Exception.TargetSite\n"}