{"nodes":[{"content":"The exception that is thrown when the server or the client cannot be reached for a previously specified period of time.","nodes":[{"pos":[0,119],"content":"The exception that is thrown when the server or the client cannot be reached for a previously specified period of time.","nodes":[{"content":"The exception that is thrown when the server or the client cannot be reached for a previously specified period of time.","pos":[0,119]}]}],"pos":[667,787],"yaml":true},{"content":"The <xref:System.Runtime.Remoting.RemotingTimeoutException> is thrown when a remoting call does not complete in the specified timeout time.  \n  \n <xref:System.Runtime.Remoting.RemotingTimeoutException> uses the HRESULT COR_E_REMOTING, which has the value 0x8013150B.  \n  \n <xref:System.Runtime.Remoting.RemotingTimeoutException> uses the default <xref:System.Object.Equals%2A> implementation, which supports reference equality.  \n  \n For a list of initial property values for an instance of <xref:System.Runtime.Remoting.RemotingTimeoutException>, see the <xref:System.Runtime.Remoting.RemotingTimeoutException> constructors.","nodes":[{"pos":[0,139],"content":"The <xref:System.Runtime.Remoting.RemotingTimeoutException> is thrown when a remoting call does not complete in the specified timeout time.","nodes":[{"content":"The <ph id=\"ph1\">&lt;xref:System.Runtime.Remoting.RemotingTimeoutException&gt;</ph> is thrown when a remoting call does not complete in the specified timeout time.","pos":[0,139],"source":"The <xref:System.Runtime.Remoting.RemotingTimeoutException> is thrown when a remoting call does not complete in the specified timeout time."}]},{"pos":[146,266],"content":"<xref:System.Runtime.Remoting.RemotingTimeoutException> uses the HRESULT COR_E_REMOTING, which has the value 0x8013150B.","nodes":[{"content":"<ph id=\"ph1\">&lt;xref:System.Runtime.Remoting.RemotingTimeoutException&gt;</ph> uses the HRESULT COR_E_REMOTING, which has the value 0x8013150B.","pos":[0,120],"source":"<xref:System.Runtime.Remoting.RemotingTimeoutException> uses the HRESULT COR_E_REMOTING, which has the value 0x8013150B."}]},{"pos":[273,427],"content":"<xref:System.Runtime.Remoting.RemotingTimeoutException> uses the default <xref:System.Object.Equals%2A> implementation, which supports reference equality.","nodes":[{"content":"<ph id=\"ph1\">&lt;xref:System.Runtime.Remoting.RemotingTimeoutException&gt;</ph> uses the default <ph id=\"ph2\">&lt;xref:System.Object.Equals%2A&gt;</ph> implementation, which supports reference equality.","pos":[0,154],"source":"<xref:System.Runtime.Remoting.RemotingTimeoutException> uses the default <xref:System.Object.Equals%2A> implementation, which supports reference equality."}]},{"pos":[434,625],"content":"For a list of initial property values for an instance of <xref:System.Runtime.Remoting.RemotingTimeoutException>, see the <xref:System.Runtime.Remoting.RemotingTimeoutException> constructors.","nodes":[{"content":"For a list of initial property values for an instance of <ph id=\"ph1\">&lt;xref:System.Runtime.Remoting.RemotingTimeoutException&gt;</ph>, see the <ph id=\"ph2\">&lt;xref:System.Runtime.Remoting.RemotingTimeoutException&gt;</ph> constructors.","pos":[0,191],"source":"For a list of initial property values for an instance of <xref:System.Runtime.Remoting.RemotingTimeoutException>, see the <xref:System.Runtime.Remoting.RemotingTimeoutException> constructors."}]}],"pos":[798,1432],"yaml":true,"extradata":"MT"},{"content":"Initializes a new instance of the <xref href=\"System.Runtime.Remoting.RemotingTimeoutException\"></xref> class with default properties.","nodes":[{"pos":[0,134],"content":"Initializes a new instance of the <ph id=\"ph1\">&lt;xref href=\"System.Runtime.Remoting.RemotingTimeoutException\"&gt;&lt;/xref&gt;</ph> class with default properties.","source":"Initializes a new instance of the <xref href=\"System.Runtime.Remoting.RemotingTimeoutException\"></xref> class with default properties."}],"pos":[3691,3826],"yaml":true},{"content":"<xref:System.Runtime.Remoting.RemotingTimeoutException> inherits from the <xref:System.Exception> class. The following table shows initial property values for an instance of the <xref:System.Runtime.Remoting.RemotingTimeoutException> class:  \n  \n|Property|Value|  \n|--------------|-----------|  \n|<xref:System.Exception.InnerException%2A>|`null`|  \n|<xref:System.Exception.Message%2A>|Localized error message for <xref:System.Runtime.Remoting.RemotingTimeoutException>|","nodes":[{"pos":[0,240],"content":"<xref:System.Runtime.Remoting.RemotingTimeoutException> inherits from the <xref:System.Exception> class. The following table shows initial property values for an instance of the <xref:System.Runtime.Remoting.RemotingTimeoutException> class:","nodes":[{"content":"<xref:System.Runtime.Remoting.RemotingTimeoutException> inherits from the <xref:System.Exception> class. The following table shows initial property values for an instance of the <xref:System.Runtime.Remoting.RemotingTimeoutException> class:","pos":[0,240],"nodes":[{"content":"<ph id=\"ph1\">&lt;xref:System.Runtime.Remoting.RemotingTimeoutException&gt;</ph> inherits from the <ph id=\"ph2\">&lt;xref:System.Exception&gt;</ph> class.","pos":[0,104],"source":"<xref:System.Runtime.Remoting.RemotingTimeoutException> inherits from the <xref:System.Exception> class."},{"content":"The following table shows initial property values for an instance of the <ph id=\"ph1\">&lt;xref:System.Runtime.Remoting.RemotingTimeoutException&gt;</ph> class:","pos":[105,240],"source":" The following table shows initial property values for an instance of the <xref:System.Runtime.Remoting.RemotingTimeoutException> class:"}]}]},{"pos":[247,255],"content":"Property","nodes":[{"content":"Property","pos":[0,8]}]},{"pos":[256,261],"content":"Value","nodes":[{"content":"Value","pos":[0,5]}]},{"pos":[297,338],"content":"<xref:System.Exception.InnerException%2A>","nodes":[]},{"pos":[350,384],"content":"<xref:System.Exception.Message%2A>","nodes":[]},{"pos":[385,468],"content":"Localized error message for <xref:System.Runtime.Remoting.RemotingTimeoutException>","nodes":[{"content":"Localized error message for <ph id=\"ph1\">&lt;xref:System.Runtime.Remoting.RemotingTimeoutException&gt;</ph>","pos":[0,83],"source":"Localized error message for <xref:System.Runtime.Remoting.RemotingTimeoutException>"}]}],"pos":[3837,4314],"yaml":true,"extradata":"MT"},{"content":"Initializes a new instance of <xref href=\"System.Runtime.Remoting.RemotingTimeoutException\"></xref> class with a specified message.","nodes":[{"pos":[0,131],"content":"Initializes a new instance of <ph id=\"ph1\">&lt;xref href=\"System.Runtime.Remoting.RemotingTimeoutException\"&gt;&lt;/xref&gt;</ph> class with a specified message.","source":"Initializes a new instance of <xref href=\"System.Runtime.Remoting.RemotingTimeoutException\"></xref> class with a specified message."}],"pos":[5658,5790],"yaml":true},{"content":"<xref:System.Runtime.Remoting.RemotingTimeoutException> inherits from the <xref:System.Exception> class. The following table shows initial property values for an instance of the <xref:System.Runtime.Remoting.RemotingTimeoutException> class:  \n  \n|Property Type|Condition|  \n|-------------------|---------------|  \n|<xref:System.Exception.InnerException%2A>|`null`|  \n|<xref:System.Exception.Message%2A>|The `message` string|","nodes":[{"pos":[0,240],"content":"<xref:System.Runtime.Remoting.RemotingTimeoutException> inherits from the <xref:System.Exception> class. The following table shows initial property values for an instance of the <xref:System.Runtime.Remoting.RemotingTimeoutException> class:","nodes":[{"content":"<xref:System.Runtime.Remoting.RemotingTimeoutException> inherits from the <xref:System.Exception> class. The following table shows initial property values for an instance of the <xref:System.Runtime.Remoting.RemotingTimeoutException> class:","pos":[0,240],"nodes":[{"content":"<ph id=\"ph1\">&lt;xref:System.Runtime.Remoting.RemotingTimeoutException&gt;</ph> inherits from the <ph id=\"ph2\">&lt;xref:System.Exception&gt;</ph> class.","pos":[0,104],"source":"<xref:System.Runtime.Remoting.RemotingTimeoutException> inherits from the <xref:System.Exception> class."},{"content":"The following table shows initial property values for an instance of the <ph id=\"ph1\">&lt;xref:System.Runtime.Remoting.RemotingTimeoutException&gt;</ph> class:","pos":[105,240],"source":" The following table shows initial property values for an instance of the <xref:System.Runtime.Remoting.RemotingTimeoutException> class:"}]}]},{"pos":[247,260],"content":"Property Type","nodes":[{"content":"Property Type","pos":[0,13]}]},{"pos":[261,270],"content":"Condition","nodes":[{"content":"Condition","pos":[0,9]}]},{"pos":[315,356],"content":"<xref:System.Exception.InnerException%2A>","nodes":[]},{"pos":[368,402],"content":"<xref:System.Exception.Message%2A>","nodes":[]},{"pos":[403,423],"content":"The <ph id=\"ph1\">`message`</ph> string","source":"The `message` string"}],"pos":[5801,6233],"yaml":true,"extradata":"MT"},{"content":"The message that indicates the reason why the exception occurred.","nodes":[{"pos":[0,65],"content":"The message that indicates the reason why the exception occurred.","nodes":[{"content":"The message that indicates the reason why the exception occurred.","pos":[0,65]}]}],"pos":[6385,6451],"yaml":true},{"content":"Initializes a new instance of the <xref href=\"System.Runtime.Remoting.RemotingTimeoutException\"></xref> class with a specified error message and a reference to the inner exception that is the cause of this exception.","nodes":[{"pos":[0,216],"content":"Initializes a new instance of the <ph id=\"ph1\">&lt;xref href=\"System.Runtime.Remoting.RemotingTimeoutException\"&gt;&lt;/xref&gt;</ph> class with a specified error message and a reference to the inner exception that is the cause of this exception.","source":"Initializes a new instance of the <xref href=\"System.Runtime.Remoting.RemotingTimeoutException\"></xref> class with a specified error message and a reference to the inner exception that is the cause of this exception."}],"pos":[7801,8018],"yaml":true},{"content":"An exception that is thrown as a direct result of a previous exception must include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property. The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or `null` if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor.  \n  \n The following table shows initial property values for an instance of the <xref:System.Runtime.Remoting.RemotingTimeoutException> class:  \n  \n|Property|Value|  \n|--------------|-----------|  \n|<xref:System.Exception.InnerException%2A>|The inner exception reference|  \n|<xref:System.Exception.Message%2A>|The error message string|","nodes":[{"pos":[0,425],"content":"An exception that is thrown as a direct result of a previous exception must include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property. The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or `null` if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor.","nodes":[{"content":"An exception that is thrown as a direct result of a previous exception must include a reference to the previous exception in the <ph id=\"ph1\">&lt;xref:System.Exception.InnerException%2A&gt;</ph> property.","pos":[0,180],"source":"An exception that is thrown as a direct result of a previous exception must include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property."},{"content":"The <ph id=\"ph1\">&lt;xref:System.Exception.InnerException%2A&gt;</ph> property returns the same value that is passed into the constructor, or <ph id=\"ph2\">`null`</ph> if the <ph id=\"ph3\">&lt;xref:System.Exception.InnerException%2A&gt;</ph> property does not supply the inner exception value to the constructor.","pos":[181,425],"source":" The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or `null` if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor."}]},{"pos":[432,567],"content":"The following table shows initial property values for an instance of the <xref:System.Runtime.Remoting.RemotingTimeoutException> class:","nodes":[{"content":"The following table shows initial property values for an instance of the <ph id=\"ph1\">&lt;xref:System.Runtime.Remoting.RemotingTimeoutException&gt;</ph> class:","pos":[0,135],"source":"The following table shows initial property values for an instance of the <xref:System.Runtime.Remoting.RemotingTimeoutException> class:"}]},{"pos":[574,582],"content":"Property","nodes":[{"content":"Property","pos":[0,8]}]},{"pos":[583,588],"content":"Value","nodes":[{"content":"Value","pos":[0,5]}]},{"pos":[624,665],"content":"<xref:System.Exception.InnerException%2A>","nodes":[]},{"pos":[666,695],"content":"The inner exception reference","nodes":[{"content":"The inner exception reference","pos":[0,29]}]},{"pos":[700,734],"content":"<xref:System.Exception.Message%2A>","nodes":[]},{"pos":[735,759],"content":"The error message string","nodes":[{"content":"The error message string","pos":[0,24]}]}],"pos":[8029,8799],"yaml":true,"extradata":"MT"},{"content":"The error message that explains the reason for the exception.","nodes":[{"pos":[0,61],"content":"The error message that explains the reason for the exception.","nodes":[{"content":"The error message that explains the reason for the exception.","pos":[0,61]}]}],"pos":[8977,9039],"yaml":true},{"content":"The exception that is the cause of the current exception. If the <code>InnerException</code> parameter is not `null`, the current exception is raised in a `catch` block that handles the inner exception.","nodes":[{"pos":[0,202],"content":"The exception that is the cause of the current exception. If the <code>InnerException</code> parameter is not `null`, the current exception is raised in a `catch` block that handles the inner exception.","nodes":[{"content":"The exception that is the cause of the current exception.","pos":[0,57]},{"content":"If the <bpt id=\"p1\">&lt;code&gt;</bpt><ph id=\"ph1\">InnerException</ph><ept id=\"p1\">&lt;/code&gt;</ept> parameter is not <ph id=\"ph2\">`null`</ph>, the current exception is raised in a <ph id=\"ph3\">`catch`</ph> block that handles the inner exception.","pos":[58,202],"source":" If the <code>InnerException</code> parameter is not `null`, the current exception is raised in a `catch` block that handles the inner exception."}]}],"pos":[9112,9315],"yaml":true}],"content":"### YamlMime:ManagedReference\nitems:\n- uid: System.Runtime.Remoting.RemotingTimeoutException\n  commentId: T:System.Runtime.Remoting.RemotingTimeoutException\n  id: RemotingTimeoutException\n  children:\n  - System.Runtime.Remoting.RemotingTimeoutException.#ctor\n  - System.Runtime.Remoting.RemotingTimeoutException.#ctor(System.String)\n  - System.Runtime.Remoting.RemotingTimeoutException.#ctor(System.String,System.Exception)\n  langs:\n  - csharp\n  name: RemotingTimeoutException\n  nameWithType: RemotingTimeoutException\n  fullName: System.Runtime.Remoting.RemotingTimeoutException\n  type: Class\n  assemblies:\n  - mscorlib\n  namespace: System.Runtime.Remoting\n  summary: The exception that is thrown when the server or the client cannot be reached for a previously specified period of time.\n  remarks: \"The <xref:System.Runtime.Remoting.RemotingTimeoutException> is thrown when a remoting call does not complete in the specified timeout time.  \\n  \\n <xref:System.Runtime.Remoting.RemotingTimeoutException> uses the HRESULT COR_E_REMOTING, which has the value 0x8013150B.  \\n  \\n <xref:System.Runtime.Remoting.RemotingTimeoutException> uses the default <xref:System.Object.Equals%2A> implementation, which supports reference equality.  \\n  \\n For a list of initial property values for an instance of <xref:System.Runtime.Remoting.RemotingTimeoutException>, see the <xref:System.Runtime.Remoting.RemotingTimeoutException> constructors.\"\n  syntax:\n    content: >-\n      [System.Runtime.InteropServices.ComVisible(true)]\n\n      public class RemotingTimeoutException : System.Runtime.Remoting.RemotingException\n  inheritance:\n  - System.Object\n  - System.Exception\n  - System.SystemException\n  - System.Runtime.Remoting.RemotingException\n  implements: []\n  inheritedMembers:\n  - System.Exception.Data\n  - System.Exception.GetBaseException\n  - System.Exception.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  - System.Exception.GetType\n  - System.Exception.HelpLink\n  - System.Exception.HResult\n  - System.Exception.InnerException\n  - System.Exception.Message\n  - System.Exception.SerializeObjectState\n  - System.Exception.Source\n  - System.Exception.StackTrace\n  - System.Exception.TargetSite\n  - System.Exception.ToString\n  - System.Object.Equals(System.Object)\n  - System.Object.Equals(System.Object,System.Object)\n  - System.Object.GetHashCode\n  - System.Object.MemberwiseClone\n  - System.Object.ReferenceEquals(System.Object,System.Object)\n  attributes:\n  - type: System.Runtime.InteropServices.ComVisibleAttribute\n  version:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  monikers:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Runtime.Remoting/RemotingTimeoutException.xml\n  ms.technology:\n  - dotnet-standard\n  manager: ghogen\n- uid: System.Runtime.Remoting.RemotingTimeoutException.#ctor\n  commentId: M:System.Runtime.Remoting.RemotingTimeoutException.#ctor\n  id: '#ctor'\n  parent: System.Runtime.Remoting.RemotingTimeoutException\n  langs:\n  - csharp\n  name: RemotingTimeoutException()\n  nameWithType: RemotingTimeoutException.RemotingTimeoutException()\n  fullName: RemotingTimeoutException.RemotingTimeoutException()\n  type: Constructor\n  assemblies:\n  - mscorlib\n  namespace: System.Runtime.Remoting\n  summary: Initializes a new instance of the <xref href=\"System.Runtime.Remoting.RemotingTimeoutException\"></xref> class with default properties.\n  remarks: \"<xref:System.Runtime.Remoting.RemotingTimeoutException> inherits from the <xref:System.Exception> class. The following table shows initial property values for an instance of the <xref:System.Runtime.Remoting.RemotingTimeoutException> class:  \\n  \\n|Property|Value|  \\n|--------------|-----------|  \\n|<xref:System.Exception.InnerException%2A>|`null`|  \\n|<xref:System.Exception.Message%2A>|Localized error message for <xref:System.Runtime.Remoting.RemotingTimeoutException>|\"\n  syntax:\n    content: public RemotingTimeoutException ();\n    parameters: []\n  overload: System.Runtime.Remoting.RemotingTimeoutException.#ctor*\n  exceptions: []\n  version:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  monikers:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Runtime.Remoting/RemotingTimeoutException.xml\n  ms.technology:\n  - dotnet-standard\n  manager: ghogen\n- uid: System.Runtime.Remoting.RemotingTimeoutException.#ctor(System.String)\n  commentId: M:System.Runtime.Remoting.RemotingTimeoutException.#ctor(System.String)\n  id: '#ctor(System.String)'\n  parent: System.Runtime.Remoting.RemotingTimeoutException\n  langs:\n  - csharp\n  name: RemotingTimeoutException(String)\n  nameWithType: RemotingTimeoutException.RemotingTimeoutException(String)\n  fullName: RemotingTimeoutException.RemotingTimeoutException(String)\n  type: Constructor\n  assemblies:\n  - mscorlib\n  namespace: System.Runtime.Remoting\n  summary: Initializes a new instance of <xref href=\"System.Runtime.Remoting.RemotingTimeoutException\"></xref> class with a specified message.\n  remarks: \"<xref:System.Runtime.Remoting.RemotingTimeoutException> inherits from the <xref:System.Exception> class. The following table shows initial property values for an instance of the <xref:System.Runtime.Remoting.RemotingTimeoutException> class:  \\n  \\n|Property Type|Condition|  \\n|-------------------|---------------|  \\n|<xref:System.Exception.InnerException%2A>|`null`|  \\n|<xref:System.Exception.Message%2A>|The `message` string|\"\n  syntax:\n    content: public RemotingTimeoutException (string message);\n    parameters:\n    - id: message\n      type: System.String\n      description: The message that indicates the reason why the exception occurred.\n  overload: System.Runtime.Remoting.RemotingTimeoutException.#ctor*\n  exceptions: []\n  version:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  monikers:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Runtime.Remoting/RemotingTimeoutException.xml\n  ms.technology:\n  - dotnet-standard\n  manager: ghogen\n- uid: System.Runtime.Remoting.RemotingTimeoutException.#ctor(System.String,System.Exception)\n  commentId: M:System.Runtime.Remoting.RemotingTimeoutException.#ctor(System.String,System.Exception)\n  id: '#ctor(System.String,System.Exception)'\n  parent: System.Runtime.Remoting.RemotingTimeoutException\n  langs:\n  - csharp\n  name: RemotingTimeoutException(String, Exception)\n  nameWithType: RemotingTimeoutException.RemotingTimeoutException(String, Exception)\n  fullName: RemotingTimeoutException.RemotingTimeoutException(String, Exception)\n  type: Constructor\n  assemblies:\n  - mscorlib\n  namespace: System.Runtime.Remoting\n  summary: Initializes a new instance of the <xref href=\"System.Runtime.Remoting.RemotingTimeoutException\"></xref> class with a specified error message and a reference to the inner exception that is the cause of this exception.\n  remarks: \"An exception that is thrown as a direct result of a previous exception must include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property. The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or `null` if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor.  \\n  \\n The following table shows initial property values for an instance of the <xref:System.Runtime.Remoting.RemotingTimeoutException> class:  \\n  \\n|Property|Value|  \\n|--------------|-----------|  \\n|<xref:System.Exception.InnerException%2A>|The inner exception reference|  \\n|<xref:System.Exception.Message%2A>|The error message string|\"\n  syntax:\n    content: public RemotingTimeoutException (string message, Exception InnerException);\n    parameters:\n    - id: message\n      type: System.String\n      description: The error message that explains the reason for the exception.\n    - id: InnerException\n      type: System.Exception\n      description: The exception that is the cause of the current exception. If the <code>InnerException</code> parameter is not `null`, the current exception is raised in a `catch` block that handles the inner exception.\n  overload: System.Runtime.Remoting.RemotingTimeoutException.#ctor*\n  exceptions: []\n  version:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  monikers:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Runtime.Remoting/RemotingTimeoutException.xml\n  ms.technology:\n  - dotnet-standard\n  manager: ghogen\nreferences:\n- uid: System.Runtime.Remoting.RemotingException\n  parent: System.Runtime.Remoting\n  isExternal: false\n  name: RemotingException\n  nameWithType: RemotingException\n  fullName: System.Runtime.Remoting.RemotingException\n- uid: System.Runtime.Remoting.RemotingTimeoutException.#ctor\n  parent: System.Runtime.Remoting.RemotingTimeoutException\n  isExternal: false\n  name: RemotingTimeoutException()\n  nameWithType: RemotingTimeoutException.RemotingTimeoutException()\n  fullName: RemotingTimeoutException.RemotingTimeoutException()\n- uid: System.Runtime.Remoting.RemotingTimeoutException.#ctor(System.String)\n  parent: System.Runtime.Remoting.RemotingTimeoutException\n  isExternal: false\n  name: RemotingTimeoutException(String)\n  nameWithType: RemotingTimeoutException.RemotingTimeoutException(String)\n  fullName: RemotingTimeoutException.RemotingTimeoutException(String)\n- uid: System.String\n  parent: System\n  isExternal: false\n  name: String\n  nameWithType: String\n  fullName: System.String\n- uid: System.Runtime.Remoting.RemotingTimeoutException.#ctor(System.String,System.Exception)\n  parent: System.Runtime.Remoting.RemotingTimeoutException\n  isExternal: false\n  name: RemotingTimeoutException(String, Exception)\n  nameWithType: RemotingTimeoutException.RemotingTimeoutException(String, Exception)\n  fullName: RemotingTimeoutException.RemotingTimeoutException(String, Exception)\n- uid: System.Exception\n  parent: System\n  isExternal: false\n  name: Exception\n  nameWithType: Exception\n  fullName: System.Exception\n- uid: System.Runtime.Remoting.RemotingTimeoutException.#ctor*\n  parent: System.Runtime.Remoting.RemotingTimeoutException\n  isExternal: false\n  name: RemotingTimeoutException\n  nameWithType: RemotingTimeoutException.RemotingTimeoutException\n  fullName: RemotingTimeoutException.RemotingTimeoutException\n  monikers:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Runtime.Remoting/RemotingTimeoutException.xml\n- uid: System.Object.Equals(System.Object)\n  parent: System.Object\n  isExternal: false\n  name: Equals(Object)\n  nameWithType: Object.Equals(Object)\n  fullName: Object.Equals(Object)\n- uid: System.Object.Equals(System.Object,System.Object)\n  parent: System.Object\n  isExternal: false\n  name: Equals(Object, Object)\n  nameWithType: Object.Equals(Object, Object)\n  fullName: Object.Equals(Object, Object)\n- uid: System.Object.GetHashCode\n  parent: System.Object\n  isExternal: false\n  name: GetHashCode()\n  nameWithType: Object.GetHashCode()\n  fullName: Object.GetHashCode()\n- uid: System.Exception.GetType\n  parent: System.Exception\n  isExternal: false\n  name: GetType()\n  nameWithType: Exception.GetType()\n  fullName: Exception.GetType()\n- uid: System.Object.MemberwiseClone\n  parent: System.Object\n  isExternal: false\n  name: MemberwiseClone()\n  nameWithType: Object.MemberwiseClone()\n  fullName: Object.MemberwiseClone()\n- uid: System.Object.ReferenceEquals(System.Object,System.Object)\n  parent: System.Object\n  isExternal: false\n  name: ReferenceEquals(Object, Object)\n  nameWithType: Object.ReferenceEquals(Object, Object)\n  fullName: Object.ReferenceEquals(Object, Object)\n- uid: System.Exception.ToString\n  parent: System.Exception\n  isExternal: false\n  name: ToString()\n  nameWithType: Exception.ToString()\n  fullName: Exception.ToString()\n- uid: System.Exception.Data\n  parent: System.Exception\n  isExternal: false\n  name: Data\n  nameWithType: Exception.Data\n  fullName: Exception.Data\n- uid: System.Exception.GetBaseException\n  parent: System.Exception\n  isExternal: false\n  name: GetBaseException()\n  nameWithType: Exception.GetBaseException()\n  fullName: Exception.GetBaseException()\n- uid: System.Exception.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  parent: System.Exception\n  isExternal: false\n  name: GetObjectData(SerializationInfo, StreamingContext)\n  nameWithType: Exception.GetObjectData(SerializationInfo, StreamingContext)\n  fullName: Exception.GetObjectData(SerializationInfo, StreamingContext)\n- uid: System.Exception.HelpLink\n  parent: System.Exception\n  isExternal: false\n  name: HelpLink\n  nameWithType: Exception.HelpLink\n  fullName: Exception.HelpLink\n- uid: System.Exception.HResult\n  parent: System.Exception\n  isExternal: false\n  name: HResult\n  nameWithType: Exception.HResult\n  fullName: Exception.HResult\n- uid: System.Exception.InnerException\n  parent: System.Exception\n  isExternal: false\n  name: InnerException\n  nameWithType: Exception.InnerException\n  fullName: Exception.InnerException\n- uid: System.Exception.Message\n  parent: System.Exception\n  isExternal: false\n  name: Message\n  nameWithType: Exception.Message\n  fullName: Exception.Message\n- uid: System.Exception.SerializeObjectState\n  parent: System.Exception\n  isExternal: false\n  name: SerializeObjectState\n  nameWithType: Exception.SerializeObjectState\n  fullName: Exception.SerializeObjectState\n- uid: System.Exception.Source\n  parent: System.Exception\n  isExternal: false\n  name: Source\n  nameWithType: Exception.Source\n  fullName: Exception.Source\n- uid: System.Exception.StackTrace\n  parent: System.Exception\n  isExternal: false\n  name: StackTrace\n  nameWithType: Exception.StackTrace\n  fullName: Exception.StackTrace\n- uid: System.Exception.TargetSite\n  parent: System.Exception\n  isExternal: false\n  name: TargetSite\n  nameWithType: Exception.TargetSite\n  fullName: Exception.TargetSite\n"}